import Link from "next/link";
import { notFound } from "next/navigation";
import { AccountStatus, prisma, SystemRole } from "@popwam/db";
import { assignUserPlan, deleteAdminUser, repairUserAccount, resetUserPassword, updateAdminUser, updateUserLimits } from "@/app/actions";
import { PageHeading } from "@/components/page-heading";
import { Badge } from "@/components/badge";
import { ConfirmSubmit } from "@/components/confirm-submit";
import { getUserEntitlements, getUserUsage } from "@/lib/plans";
import { getLegacyTagUrl as getTagUrl } from "@popwam/shared";
import { ExternalLink, Wrench } from "lucide-react";

const limitFields = ["maxProfiles","maxLinks","maxCustomFields","maxTags","maxUploads","maxStorageBytes"] as const;
const featureFields = ["allowCustomSlug","allowThemes","allowCustomTheme","allowAnalytics","allowFileUploads"] as const;
export default async function AdminUserDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [user, plans, entitlements, usage] = await Promise.all([
    prisma.user.findUnique({ where: { id }, include: { accounts: true, profiles: { include: { fields: true, uploads: true } }, destinations: true, ownedTags: { include: { activeDestination: true }, orderBy: { createdAt: "desc" } }, memberships: { include: { organization: true } }, auditLogs: { orderBy: { createdAt: "desc" }, take: 20 } } }),
    prisma.plan.findMany({ where: { isActive: true }, orderBy: { maxLinks: "asc" } }), getUserEntitlements(id), getUserUsage(id),
  ]);
  if (!user) notFound(); const profile = user.profiles[0]; const effective = entitlements.effective;
  return <><PageHeading eyebrow="User management" title={user.name || user.email} description={user.email} action={<div className="flex gap-2"><Badge value={user.role}/><Badge value={user.status}/></div>}/>
    <div className="mb-6 flex flex-wrap gap-2"><a href={profile?.slug ? `/p/${profile.slug}` : profile ? `/p/id/${profile.id}` : "#"} target="_blank" className="btn-secondary">Open profile <ExternalLink size={14}/></a><Link href={`/admin/links?user=${id}`} className="btn-secondary">Manage links</Link><Link href={`/admin/uploads?user=${id}`} className="btn-secondary">Manage files</Link><Link href={`/admin/tags?user=${id}`} className="btn-secondary">Manage tags</Link></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="card p-5"><h2 className="font-bold">Account information</h2><form action={updateAdminUser} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="id" value={id}/><label><span className="label">Name</span><input className="input" name="name" defaultValue={user.name || ""}/></label><label><span className="label">Email</span><input className="input" name="email" type="email" defaultValue={user.email} required/></label><label><span className="label">Role</span><select className="input" name="role" defaultValue={user.role}>{Object.values(SystemRole).map(v => <option key={v}>{v}</option>)}</select></label><label><span className="label">Status</span><select className="input" name="status" defaultValue={user.status}>{Object.values(AccountStatus).map(v => <option key={v}>{v}</option>)}</select></label><button className="btn-primary sm:col-span-2 sm:justify-self-start">Save account</button></form><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Provider</dt><dd>{user.accounts.map(a => a.provider).join(", ") || "credentials"}</dd></div><div><dt className="text-slate-500">Last login</dt><dd>{user.lastLoginAt?.toLocaleString() || "Never"}</dd></div><div><dt className="text-slate-500">Created</dt><dd>{user.createdAt.toLocaleString()}</dd></div><div><dt className="text-slate-500">Organization</dt><dd>{user.memberships[0]?.organization.name || "Missing"}</dd></div></dl></section>
      <section className="card p-5"><h2 className="font-bold">Plan</h2><p className="mt-2 text-sm text-slate-400">Current: <strong className="text-white">{entitlements.plan.name}</strong></p><form action={assignUserPlan} className="mt-4 flex gap-3"><input type="hidden" name="userId" value={id}/><select className="input" name="planId" defaultValue={entitlements.plan.id}>{plans.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><ConfirmSubmit className="btn-primary" message="Assign this plan to the user?">Assign plan</ConfirmSubmit></form><h3 className="mt-6 font-semibold">Usage statistics</h3><div className="mt-3 grid grid-cols-2 gap-3 text-sm">{[["Profiles",usage.profiles,effective.maxProfiles],["Links",usage.links,effective.maxLinks],["Custom fields",usage.customFields,effective.maxCustomFields],["Tags",usage.tags,effective.maxTags],["Uploads",usage.uploads,effective.maxUploads]].map(([label,value,max]) => <div className="rounded-xl bg-white/5 p-3" key={String(label)}><p className="text-slate-500">{String(label)}</p><strong>{String(value)} / {String(max)}</strong></div>)}</div></section>
      <section className="card p-5 xl:col-span-2"><h2 className="font-bold">Per-user limit overrides</h2><p className="mt-1 text-sm text-slate-500">Leave a value blank to inherit it from the plan.</p><form action={updateUserLimits} className="mt-4 grid gap-4 sm:grid-cols-3"><input type="hidden" name="userId" value={id}/>{limitFields.map(key => <label key={key}><span className="label">{key}</span><input className="input" name={key} type="number" min="0" defaultValue={entitlements.override?.[key]?.toString() || ""}/></label>)}{featureFields.map(key => <label key={key}><span className="label">{key}</span><select className="input" name={key} defaultValue={entitlements.override?.[key] == null ? "" : String(entitlements.override[key])}><option value="">Inherit</option><option value="true">Allow</option><option value="false">Deny</option></select></label>)}<button className="btn-primary sm:col-span-3 sm:justify-self-start">Save overrides</button></form></section>
      <section className="card p-5"><h2 className="font-bold">Profile, fields and files</h2>{profile ? <div className="mt-4 space-y-2 text-sm"><p><span className="text-slate-500">Profile:</span> {profile.displayName}</p><p><span className="text-slate-500">Theme:</span> {profile.theme}</p><p><span className="text-slate-500">Custom fields:</span> {profile.fields.length}</p><p><span className="text-slate-500">Files:</span> {profile.uploads.length}</p></div> : <p className="mt-3 text-amber-300">Profile relation is missing.</p>}<div className="mt-4 divide-y divide-white/10">{profile?.fields.map(field => <p className="py-2 text-sm" key={field.id}>{field.label}: <span className="text-slate-400">{field.value}</span></p>)}</div></section>
      <section className="card p-5"><h2 className="font-bold">Tags</h2><div className="mt-3 space-y-3">{user.ownedTags.map(tag => <div className="rounded-xl bg-white/5 p-3 text-sm" key={tag.id}><div className="flex justify-between"><strong>{tag.name}</strong><Badge value={tag.status}/></div><p className="mt-2 text-slate-400">Opens: {tag.activeDestination?.title || "Not configured"}</p><a href={getTagUrl(tag.token)} target="_blank" className="mt-2 block text-xs text-brand-400">{getTagUrl(tag.token)}</a></div>)}</div></section>
      <section className="card p-5 xl:col-span-2"><h2 className="font-bold">Repair and security</h2><div className="mt-4 flex flex-wrap gap-3"><form action={repairUserAccount}><input type="hidden" name="userId" value={id}/><ConfirmSubmit className="btn-secondary" message="Repair missing profile, workspace, membership, profile destination and FREE plan?"><Wrench size={15}/> Repair account</ConfirmSubmit></form><form action={resetUserPassword} className="flex gap-2"><input type="hidden" name="userId" value={id}/><input className="input" name="password" minLength={8} placeholder="Temporary password" required/><ConfirmSubmit className="btn-secondary" message="Reset this user’s password?">Reset password</ConfirmSubmit></form><form action={deleteAdminUser}><input type="hidden" name="userId" value={id}/><ConfirmSubmit message="Permanently delete this user and all owned data? This cannot be undone.">Delete user safely</ConfirmSubmit></form></div></section>
      <section className="card p-5 xl:col-span-2"><h2 className="font-bold">Activity</h2><div className="mt-3 divide-y divide-white/10">{user.auditLogs.map(log => <div className="flex justify-between gap-4 py-3 text-sm" key={log.id}><span>{log.operation}</span><time className="text-slate-500">{log.createdAt.toLocaleString()}</time></div>)}{!user.auditLogs.length && <p className="text-sm text-slate-500">No audited activity yet.</p>}</div></section>
    </div>
  </>;
}
