import "dotenv/config";import {prisma} from "../src";
const catalog=[
 {category:["nfc-cards","كروت NFC","NFC Cards"],slug:"pop-nfc-card",nameAr:"كارت POP NFC",nameEn:"POP NFC Card",sku:"POP-CARD-DEFAULT",price:499,image:"/brand/pop/card-landscape-front.svg"},
 {category:["stickers","ملصقات","Stickers"],slug:"pop-nfc-sticker",nameAr:"ملصق POP NFC",nameEn:"POP NFC Sticker",sku:"POP-STICKER-DEFAULT",price:199,image:"/brand/pop/logo-form.svg"},
 {category:["wearables","أجهزة قابلة للارتداء","Wearables"],slug:"pop-bracelet",nameAr:"سوار POP",nameEn:"POP Bracelet",sku:"POP-BRACELET-DEFAULT",price:399,image:"/brand/pop/logo-form.svg"},
 {category:["accessories","إكسسوارات","Accessories"],slug:"pop-keychain",nameAr:"ميدالية POP",nameEn:"POP Keychain",sku:"POP-KEYCHAIN-DEFAULT",price:249,image:"/brand/pop/logo-form.svg"},
];
async function main(){for(const item of catalog){const [categorySlug,categoryAr,categoryEn]=item.category;const category=await prisma.productCategory.upsert({where:{slug:categorySlug},update:{nameAr:categoryAr,nameEn:categoryEn,isActive:true},create:{slug:categorySlug,nameAr:categoryAr,nameEn:categoryEn}});const product=await prisma.product.upsert({where:{slug:item.slug},update:{categoryId:category.id,nameAr:item.nameAr,nameEn:item.nameEn},create:{categoryId:category.id,slug:item.slug,nameAr:item.nameAr,nameEn:item.nameEn,status:"DRAFT"}});const variant=await prisma.productVariant.upsert({where:{sku:item.sku},update:{productId:product.id,nameAr:item.nameAr,nameEn:item.nameEn},create:{productId:product.id,sku:item.sku,nameAr:item.nameAr,nameEn:item.nameEn,isDefault:true}});await prisma.productInventory.upsert({where:{variantId:variant.id},update:{},create:{variantId:variant.id,quantity:0,status:"OUT_OF_STOCK"}});if(!await prisma.productPrice.findFirst({where:{productId:product.id,variantId:variant.id,isActive:true}}))await prisma.productPrice.create({data:{productId:product.id,variantId:variant.id,amount:item.price,currency:"EGP"}});if(!await prisma.productImage.findFirst({where:{productId:product.id,url:item.image}}))await prisma.productImage.create({data:{productId:product.id,variantId:variant.id,url:item.image,isPrimary:true}});await prisma.productSlug.upsert({where:{slug:item.slug},update:{productId:product.id,isCanonical:true},create:{productId:product.id,slug:item.slug,isCanonical:true}});}console.log(`POP catalog backfill complete (${catalog.length} draft products; no product was auto-published).`)}
main().finally(()=>prisma.$disconnect());
