import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@popwam/db";
import { updateStoreOrder } from "@/app/commerce-actions";
import { Badge } from "@/components/badge";
import { ConfirmSubmit } from "@/components/confirm-submit";
import { PageHeading } from "@/components/page-heading";
import { ORDER_TRANSITIONS } from "@/lib/commerce";

export default async function OrderPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const order=await prisma.order.findUnique({where:{id},include:{customer:true,items:{include:{card:true,inventoryItem:true}}}});if(!order)notFound();return <><div className="mb-4"><Link className="btn-secondary" href="/admin/orders">Back to orders</Link></div><PageHeading eyebrow="Store order" title={`${order.customer.name} · ${order.createdAt.toLocaleDateString()}`} description="Customer-created order. Payment and fulfilment transitions require an explicit administrator action." action={<div className="flex gap-2"><Badge value={order.status}/><Badge value={order.paymentStatus}/></div>}/><div className="grid gap-5 lg:grid-cols-2"><section className="card p-5"><h2 className="font-bold">Items / البنود</h2>{order.items.map(item=><div className="mt-3 rounded-xl bg-white/5 p-4" key={item.id}><div className="flex justify-between"><strong>{item.description}</strong><strong>{String(item.total)}</strong></div><p className="mt-1 text-xs text-slate-500">{item.quantity} × {String(item.unitPrice)} · {item.card?.serialNumber||item.inventoryItem?.sku||"Product"}</p></div>)}</section><div className="space-y-5"><section className="card p-5"><h2 className="font-bold">Totals / الإجماليات</h2><dl className="mt-4 grid grid-cols-2 gap-4">{[["Subtotal",order.subtotal],["Discount",order.discount],["Shipping",order.shippingCost],["Total",order.total],["Paid",order.paidAmount]].map(([key,value])=><div key={String(key)}><dt className="text-xs text-slate-500">{String(key)}</dt><dd className="font-bold">{String(value)}</dd></div>)}</dl></section><section className="card p-5"><h2 className="font-bold">Process order / معالجة الطلب</h2><p className="mt-2 text-sm text-slate-500">Only valid next states are shown. Stock is released when a reserving order is cancelled.</p><form action={updateStoreOrder} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="orderId" value={order.id}/>{(ORDER_TRANSITIONS[order.status]||[]).map(status=><ConfirmSubmit name="status" value={status} className={status==="CANCELLED"||status==="REFUNDED"?"btn-danger":"btn-secondary"} message={`Move this order to ${status}?`} key={status}>{status.replaceAll("_"," ")}</ConfirmSubmit>)}</form></section></div></div></>}
