import Link from "next/link";
import { AccountDeletionRequestStatus, FeatureRequestStatus, Prisma, QuotaRequestStatus, SubscriptionStatus, prisma } from "@popwam/db";
import { CalendarDays, ChevronDown, ClipboardList, HardDrive, Lightbulb, ShieldAlert, Sparkles } from "lucide-react";
import { updateSubscriptionRequest } from "@/app/commerce-actions";
import { reviewQuotaRequest } from "@/app/quota-actions";
import { updateFeatureRequest } from "@/app/social-actions";
import { DashboardPageHeader, EmptyState, FilterBar, SearchField, StatusBadge, UserIdentityCell } from "@/components/admin-ui";
import { ConfirmSubmit } from "@/components/confirm-submit";
import { SUBSCRIPTION_TRANSITIONS } from "@/lib/commerce";
import { getI18n } from "@/lib/i18n";
import { formatStorageBytes } from "@/lib/plans";
import { requireAdmin } from "@/lib/session";

const PAGE_SIZE=24;
const requestTypes=["subscription","limit","feature","general"] as const;
type RequestType=typeof requestTypes[number];
const statusValues=[...Object.values(SubscriptionStatus),...Object.values(QuotaRequestStatus),...Object.values(FeatureRequestStatus),...Object.values(AccountDeletionRequestStatus)].filter((value,index,array)=>array.indexOf(value)===index);
const validDate=(value?:string)=>value&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(`${value}T00:00:00.000Z`):undefined;

export default async function RequestsCenterPage({searchParams}:{searchParams:Promise<{type?:string;status?:string;q?:string;from?:string;to?:string;plan?:string;page?:string}>}){
  await requireAdmin();
  const [{locale},filters,plans]=await Promise.all([getI18n(),searchParams,prisma.plan.findMany({orderBy:{sortOrder:"asc"},select:{slug:true,name:true,nameAr:true,nameEn:true}})]);
  const ar=locale==="ar",type=requestTypes.includes(filters.type as RequestType)?filters.type as RequestType:undefined,status=statusValues.includes(filters.status as never)?filters.status:undefined;
  const q=filters.q?.trim().slice(0,100)||"",page=Math.max(1,Math.min(50,Number.parseInt(filters.page||"1",10)||1)),skip=(page-1)*PAGE_SIZE,take=skip+PAGE_SIZE;
  const from=validDate(filters.from),to=validDate(filters.to);if(to)to.setUTCHours(23,59,59,999);
  const userSearch:Prisma.UserWhereInput|undefined=q?{OR:[{name:{contains:q,mode:"insensitive"}},{email:{contains:q,mode:"insensitive"}}]}:undefined;
  const dateRange={...(from?{gte:from}:{}),...(to?{lte:to}:{})};
  const includeType=(value:RequestType)=>!type||type===value;
  const subscriptionWhere:Prisma.UserPlanWhereInput={...(status&&Object.values(SubscriptionStatus).includes(status as SubscriptionStatus)?{status:status as SubscriptionStatus}:status?{id:"__none__"}:{}),...(filters.plan?{plan:{slug:filters.plan}}:{}),...(q?{OR:[{id:{contains:q,mode:"insensitive"}},{user:userSearch}]}:{}),...((from||to)?{createdAt:dateRange}:{})};
  const quotaWhere:Prisma.QuotaIncreaseRequestWhereInput={...(status&&Object.values(QuotaRequestStatus).includes(status as QuotaRequestStatus)?{status:status as QuotaRequestStatus}:status?{id:"__none__"}:{}),...(q?{OR:[{id:{contains:q,mode:"insensitive"}},{user:userSearch}]}:{}),...((from||to)?{createdAt:dateRange}:{})};
  const featureWhere:Prisma.FeatureRequestWhereInput={...(status&&Object.values(FeatureRequestStatus).includes(status as FeatureRequestStatus)?{status:status as FeatureRequestStatus}:status?{id:"__none__"}:{}),...(q?{OR:[{id:{contains:q,mode:"insensitive"}},{title:{contains:q,mode:"insensitive"}},{author:userSearch}]}:{}),...((from||to)?{createdAt:dateRange}:{})};
  const generalWhere:Prisma.AccountDeletionRequestWhereInput={...(status&&Object.values(AccountDeletionRequestStatus).includes(status as AccountDeletionRequestStatus)?{status:status as AccountDeletionRequestStatus}:status?{id:"__none__"}:{}),...(q?{OR:[{id:{contains:q,mode:"insensitive"}},{user:userSearch}]}:{}),...((from||to)?{requestedAt:dateRange}:{})};
  const subscriptionsOn=includeType("subscription"),quotaOn=includeType("limit")&&!filters.plan,featureOn=includeType("feature")&&!filters.plan,generalOn=includeType("general")&&!filters.plan;
  const [subscriptions,quotas,features,general,subscriptionCount,quotaCount,featureCount,generalCount,featureTargets]=await Promise.all([
    subscriptionsOn?prisma.userPlan.findMany({where:subscriptionWhere,orderBy:{createdAt:"desc"},take,include:{plan:true,user:{select:{id:true,name:true,email:true,image:true,profiles:{take:1,select:{avatarUrl:true}}}}}}):[],
    quotaOn?prisma.quotaIncreaseRequest.findMany({where:quotaWhere,orderBy:{createdAt:"desc"},take,include:{user:{select:{id:true,name:true,email:true,image:true,profiles:{take:1,select:{avatarUrl:true}}}},reviewedBy:{select:{name:true,email:true}}}}):[],
    featureOn?prisma.featureRequest.findMany({where:featureWhere,orderBy:{createdAt:"desc"},take,include:{author:{select:{id:true,name:true,email:true,image:true,profiles:{take:1,select:{avatarUrl:true}}}},mergedInto:{select:{title:true}},_count:{select:{votes:true,comments:true}}}}):[],
    generalOn?prisma.accountDeletionRequest.findMany({where:generalWhere,orderBy:{requestedAt:"desc"},take,include:{user:{select:{id:true,name:true,email:true,image:true,profiles:{take:1,select:{avatarUrl:true}}}}}}):[],
    subscriptionsOn?prisma.userPlan.count({where:subscriptionWhere}):0,quotaOn?prisma.quotaIncreaseRequest.count({where:quotaWhere}):0,featureOn?prisma.featureRequest.count({where:featureWhere}):0,generalOn?prisma.accountDeletionRequest.count({where:generalWhere}):0,
    featureOn?prisma.featureRequest.findMany({orderBy:{createdAt:"desc"},take:100,select:{id:true,title:true}}):[],
  ]);
  const items=[
    ...subscriptions.map(item=>({kind:"subscription" as const,id:item.id,status:item.status,createdAt:item.createdAt,updatedAt:item.updatedAt,user:item.user,title:ar?item.plan.nameAr||item.plan.nameEn||item.plan.name:item.plan.nameEn||item.plan.nameAr||item.plan.name,data:item})),
    ...quotas.map(item=>({kind:"limit" as const,id:item.id,status:item.status,createdAt:item.createdAt,updatedAt:item.updatedAt,user:item.user,title:item.resource==="MAX_STORAGE_BYTES"?(ar?"زيادة مساحة التخزين":"Storage increase"):(ar?"زيادة عدد الروابط":"Link limit increase"),data:item})),
    ...features.map(item=>({kind:"feature" as const,id:item.id,status:item.status,createdAt:item.createdAt,updatedAt:item.updatedAt,user:item.author,title:item.title,data:item})),
    ...general.map(item=>({kind:"general" as const,id:item.id,status:item.status,createdAt:item.requestedAt,updatedAt:item.completedAt||item.cancelledAt||item.reviewedAt||item.requestedAt,user:item.user,title:ar?"طلب حذف الحساب":"Account deletion request",data:item})),
  ].sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).slice(skip,skip+PAGE_SIZE);
  const total=subscriptionCount+quotaCount+featureCount+generalCount,pages=Math.max(1,Math.ceil(total/PAGE_SIZE));
  const hrefFor=(next:number)=>{const params=new URLSearchParams();for(const [key,value] of Object.entries(filters))if(value&&key!=="page")params.set(key,value);params.set("page",String(next));return `/admin/requests?${params}`};
  const copy=ar?{eyebrow:"مركز الطلبات",title:"الطلبات",description:"مكان واحد لمراجعة طلبات الاشتراك والحدود والميزات والطلبات العامة.",search:"ابحث بالمستخدم أو البريد أو رقم الطلب",allTypes:"كل الأنواع",allStatus:"كل الحالات",allPlans:"كل الباقات",apply:"تطبيق",subscription:"اشتراك",limit:"زيادة حد",feature:"ميزة",general:"عام",request:"الطلب",created:"أُرسل",updated:"آخر تحديث",details:"التفاصيل",transition:"تغيير الحالة",update:"تنفيذ",terminal:"لا توجد انتقالات متاحة",reason:"الملاحظة أو السبب",reviewer:"راجعه",requested:"القيمة المطلوبة",plan:"الباقة",dates:"مدة الاشتراك",response:"رد الإدارة",votes:"تصويت",comments:"تعليق",generalNote:"يتطلب هذا الطلب مسار الأمان الحالي؛ لا توجد إجراءات إدارية آمنة معرفة في النظام لتغييره من هنا.",empty:"لا توجد طلبات مطابقة",emptyHelp:"جرّب تغيير الفلاتر أو نطاق التاريخ.",results:"طلب",page:"صفحة"}: {eyebrow:"Requests center",title:"Requests",description:"One place to review subscription, limit, feature, and existing general requests.",search:"Search user, email, or request reference",allTypes:"All types",allStatus:"All statuses",allPlans:"All plans",apply:"Apply",subscription:"Subscription",limit:"Limit increase",feature:"Feature",general:"General",request:"Request",created:"Submitted",updated:"Updated",details:"Details",transition:"Change status",update:"Apply",terminal:"No transitions available",reason:"Note or reason",reviewer:"Reviewed by",requested:"Requested value",plan:"Plan",dates:"Subscription period",response:"Admin response",votes:"votes",comments:"comments",generalNote:"This request follows the existing security workflow; no safe admin transition is currently defined for it here.",empty:"No matching requests",emptyHelp:"Try changing the filters or date range.",results:"requests",page:"Page"};
  const kindLabel={subscription:copy.subscription,limit:copy.limit,feature:copy.feature,general:copy.general};
  const kindIcon={subscription:Sparkles,limit:HardDrive,feature:Lightbulb,general:ShieldAlert};
  return <>
    <DashboardPageHeader eyebrow={copy.eyebrow} title={copy.title} description={copy.description}/>
    <form action="/admin/requests"><FilterBar><SearchField defaultValue={q} placeholder={copy.search}/><select className="input md:max-w-44" name="type" defaultValue={type||""}><option value="">{copy.allTypes}</option>{requestTypes.map(value=><option value={value} key={value}>{kindLabel[value]}</option>)}</select><select className="input md:max-w-44" name="status" defaultValue={status||""}><option value="">{copy.allStatus}</option>{statusValues.map(value=><option key={value}>{value.replaceAll("_"," ")}</option>)}</select><select className="input md:max-w-44" name="plan" defaultValue={filters.plan||""}><option value="">{copy.allPlans}</option>{plans.map(plan=><option value={plan.slug} key={plan.slug}>{(ar?plan.nameAr||plan.nameEn:plan.nameEn||plan.nameAr)||plan.name}</option>)}</select><label className="relative"><CalendarDays className="absolute start-3 top-1/2 -translate-y-1/2 text-slate-500" size={15}/><input className="input ps-9" type="date" name="from" defaultValue={filters.from}/></label><label className="relative"><CalendarDays className="absolute start-3 top-1/2 -translate-y-1/2 text-slate-500" size={15}/><input className="input ps-9" type="date" name="to" defaultValue={filters.to}/></label><button className="btn-primary">{copy.apply}</button></FilterBar></form>
    <div className="grid gap-3">{items.map(item=>{const Icon=kindIcon[item.kind];const avatar=item.user.profiles[0]?.avatarUrl||item.user.image;return <article className="admin-section-card" key={`${item.kind}-${item.id}`}>
      <div className="grid items-center gap-4 xl:grid-cols-[minmax(13rem,1fr)_minmax(12rem,1.5fr)_auto_auto]"><UserIdentityCell name={item.user.name} email={item.user.email} imageUrl={avatar}/><div className="min-w-0"><div className="flex items-center gap-2 text-xs font-bold text-brand-400"><Icon size={15}/>{kindLabel[item.kind]}</div><h2 className="mt-1 truncate">{item.title}</h2><p className="mt-1 truncate font-mono text-[10px] text-slate-600" dir="ltr">{item.id}</p></div><div><StatusBadge value={item.status}/><time className="mt-1 block text-[10px] text-slate-500">{item.createdAt.toLocaleString(locale)}</time></div><div className="min-w-0">{item.kind==="subscription"&&<form action={updateSubscriptionRequest} className="flex gap-2"><input type="hidden" name="subscriptionId" value={item.id}/><input type="hidden" name="startsAt" value={item.data.startsAt.toISOString().slice(0,10)}/><input type="hidden" name="endsAt" value={item.data.endsAt?.toISOString().slice(0,10)||""}/><input type="hidden" name="reason" value={item.data.adminNote||""}/><select className="input min-w-0" name="status" defaultValue="" required><option value="" disabled>{item.status.replaceAll("_"," ")} · {copy.transition}</option>{(SUBSCRIPTION_TRANSITIONS[item.status]||[]).map(value=><option key={value}>{value}</option>)}</select>{(SUBSCRIPTION_TRANSITIONS[item.status]||[]).length>0&&<ConfirmSubmit className="btn-secondary px-3" message="Apply this valid subscription transition?">{copy.update}</ConfirmSubmit>}</form>}{item.kind==="limit"&&item.status==="PENDING"&&<form action={reviewQuotaRequest} className="flex gap-2"><input type="hidden" name="requestId" value={item.id}/><select className="input min-w-0" name="status" defaultValue="" required><option value="" disabled>{item.status} · {copy.transition}</option><option>APPROVED</option><option>REJECTED</option></select><ConfirmSubmit className="btn-secondary px-3" message="Apply this quota decision and its domain effects?">{copy.update}</ConfirmSubmit></form>}{item.kind==="feature"&&<form action={updateFeatureRequest} className="flex gap-2"><input type="hidden" name="featureRequestId" value={item.id}/><input type="hidden" name="adminResponse" value={item.data.adminResponse||""}/><input type="hidden" name="mergedIntoId" value={item.data.mergedIntoId||""}/><select className="input min-w-0" name="status" defaultValue="" required><option value="" disabled>{item.status.replaceAll("_"," ")} · {copy.transition}</option>{Object.values(FeatureRequestStatus).filter(value=>value!==item.status).map(value=><option key={value}>{value}</option>)}</select><ConfirmSubmit className="btn-secondary px-3" message="Apply this feature request status?">{copy.update}</ConfirmSubmit></form>}{item.kind==="general"&&<span className="text-xs text-slate-500">{copy.terminal}</span>}{item.kind==="limit"&&item.status!=="PENDING"&&<span className="text-xs text-slate-500">{copy.terminal}</span>}</div></div>
      <details className="mt-4 border-t border-white/10 pt-3"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-bold text-slate-500">{copy.details}<ChevronDown size={14}/></summary><div className="mt-4 grid gap-4 rounded-xl bg-white/[.025] p-4 text-sm md:grid-cols-2"><div><span className="text-xs text-slate-500">{copy.created}</span><p>{item.createdAt.toLocaleString(locale)}</p></div><div><span className="text-xs text-slate-500">{copy.updated}</span><p>{item.updatedAt.toLocaleString(locale)}</p></div>{item.kind==="subscription"&&<><div><span className="text-xs text-slate-500">{copy.plan}</span><p>{item.title}</p></div><div><span className="text-xs text-slate-500">{copy.dates}</span><p>{item.data.startsAt.toLocaleDateString(locale)} — {item.data.endsAt?.toLocaleDateString(locale)||"—"}</p></div>{item.data.adminNote&&<div className="md:col-span-2"><span className="text-xs text-slate-500">{copy.reason}</span><p>{item.data.adminNote}</p></div>}</>}{item.kind==="limit"&&<><div><span className="text-xs text-slate-500">{copy.requested}</span><p>{item.data.resource==="MAX_STORAGE_BYTES"?formatStorageBytes(item.data.requestedValue):item.data.requestedValue.toString()}</p></div><div><span className="text-xs text-slate-500">{copy.reviewer}</span><p>{item.data.reviewedBy?.name||item.data.reviewedBy?.email||"—"}</p></div>{item.data.reason&&<div><span className="text-xs text-slate-500">{copy.reason}</span><p>{item.data.reason}</p></div>}{item.data.adminNote&&<div><span className="text-xs text-slate-500">Admin note</span><p>{item.data.adminNote}</p></div>}</>}{item.kind==="feature"&&<><p className="whitespace-pre-wrap md:col-span-2">{item.data.description}</p><p>{item.data._count.votes} {copy.votes} · {item.data._count.comments} {copy.comments}</p>{item.data.adminResponse&&<div><span className="text-xs text-slate-500">{copy.response}</span><p>{item.data.adminResponse}</p></div>}<form action={updateFeatureRequest} className="grid gap-3 md:col-span-2 md:grid-cols-2"><input type="hidden" name="featureRequestId" value={item.id}/><select className="input" name="status" defaultValue={item.status}>{Object.values(FeatureRequestStatus).map(value=><option key={value}>{value}</option>)}</select><select className="input" name="mergedIntoId" defaultValue={item.data.mergedIntoId||""}><option value="">Not a duplicate</option>{featureTargets.filter(target=>target.id!==item.id).map(target=><option value={target.id} key={target.id}>{target.title}</option>)}</select><textarea className="input min-h-24 md:col-span-2" name="adminResponse" defaultValue={item.data.adminResponse||""} placeholder={copy.response}/><button className="btn-primary md:col-span-2 md:justify-self-start">{copy.update}</button></form></>}{item.kind==="general"&&<p className="md:col-span-2 text-amber-300">{copy.generalNote}</p>}</div></details>
    </article>})}{!items.length&&<div className="admin-table-shell"><EmptyState title={copy.empty} description={copy.emptyHelp}/></div>}</div>
    <footer className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{total} {copy.results} · {copy.page} {page}/{pages}</span><div className="flex gap-2">{page>1&&<Link className="btn-secondary" href={hrefFor(page-1)}>←</Link>}{page<pages&&<Link className="btn-secondary" href={hrefFor(page+1)}>→</Link>}</div></footer>
  </>;
}
