import Link from "next/link";
import { PageHeading } from "@/components/page-heading";
import { getPlatformReadiness } from "@/lib/platform-readiness";
import { requireAdmin } from "@/lib/session";

export default async function PlatformReadinessPage() {
  await requireAdmin();
  const readiness = await getPlatformReadiness();
  return <><PageHeading eyebrow="Platform Settings" title="Platform Readiness" description="Derived from live language, country and legal configuration. It is never a manually editable boolean." />
    <section className={`card p-5 ${readiness.ready ? "ring-1 ring-emerald-500/50" : "ring-1 ring-rose-500/50"}`}><p className="text-sm text-slate-400">Platform status</p><h2 className={`mt-1 text-3xl font-black ${readiness.ready ? "text-emerald-400" : "text-rose-400"}`}>{readiness.ready ? "READY" : "INCOMPLETE"}</h2><div className="mt-4 space-y-2">{readiness.issues.length ? readiness.issues.map((issue, index) => <p key={index} className={issue.level === "BLOCKER" ? "text-rose-300" : "text-amber-300"}><b>{issue.level}:</b> {issue.message}</p>) : <p className="text-emerald-300">All mandatory platform onboarding prerequisites are configured.</p>}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="card p-5"><div className="flex justify-between gap-3"><div><h2 className="font-black">Languages & translations</h2><p className="text-sm text-slate-400">Default {readiness.config.defaultLocale} · {readiness.config.translationVersion} translation version · {readiness.keyCount} canonical keys</p></div><Link className="btn-secondary" href="/admin/localization">Manage</Link></div><div className="mt-4 space-y-3">{readiness.locales.map(locale => <div className="rounded-xl bg-white/5 p-3" key={locale.code}><div className="flex justify-between"><b>{locale.nativeName} ({locale.code})</b><span>{locale.published ? "Published" : "Draft"} · {locale.rtl ? "RTL" : "LTR"}</span></div><p className="mt-1 text-sm text-slate-400">{locale.coverage.percentage}% coverage · {locale.coverage.missing} missing {locale.isDefault ? "· Default" : ""}</p></div>)}</div></section>
      <section className="card p-5"><div className="flex justify-between"><div><h2 className="font-black">Phone countries</h2><p className="text-sm text-slate-400">{readiness.enabledCountries.length} enabled · {readiness.countries.length - readiness.enabledCountries.length} disabled</p></div><Link className="btn-secondary" href="/admin/phone-countries">Manage</Link></div><div className="mt-4 space-y-2">{readiness.enabledCountries.map(country => <p className="rounded-xl bg-white/5 p-3" key={country.id}>{country.flagEmoji} <b>{country.name}</b> · {country.iso2} · {country.dialCode} · {country.phonePlaceholder || "No placeholder"}</p>)}{!readiness.enabledCountries.length && <p className="text-rose-300">No countries are currently exposed to mobile authentication.</p>}</div></section></div>
    <section className="card mt-5 p-5"><div className="flex justify-between"><div><h2 className="font-black">Legal & Agreements</h2><p className="text-sm text-slate-400">Each published locale must have the current required, acceptance-required, active, published and effective Terms and Privacy.</p></div><Link className="btn-secondary" href="/admin/legal">Manage</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{readiness.locales.map(locale => <div className="rounded-xl bg-white/5 p-4" key={locale.code}><div className="flex justify-between"><b>{locale.nativeName}</b><span className={locale.legalReady ? "text-emerald-300" : "text-rose-300"}>{locale.legalReady ? "Legal ready" : "Not ready"}</span></div>{locale.legal.map(item => <p className="mt-2 text-sm" key={item.type}><b>{item.type === "TERMS" ? "Terms" : "Privacy"}:</b> {item.document ? `Published v${item.document.version}` : "Missing, draft, archived, inactive or not yet effective"}</p>)}</div>)}</div></section>
  </>;
}
