"use server";

import { OrderStatus, PaymentStatus, Prisma, SubscriptionStatus, prisma } from "@popwam/db";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin, requireUser } from "@/lib/session";
import { ORDER_TRANSITIONS, SUBSCRIPTION_TRANSITIONS, storeAvailability, transitionAllowed } from "@/lib/commerce";

const text=(data:FormData,key:string)=>String(data.get(key)||"").trim();
const producedTypes=new Set(["BLANK_CARD","BLANK_STICKER","BLANK_WRISTBAND","QR_PRODUCT"]);

export async function requestPlan(data:FormData){const user=await requireUser();const plan=await prisma.plan.findFirst({where:{id:text(data,"planId"),isActive:true}});if(!plan)throw new Error("PLAN_NOT_FOUND");const pending=await prisma.userPlan.findFirst({where:{userId:user.id,status:{in:["REQUESTED","PAYMENT_PENDING","PAYMENT_VERIFICATION","APPROVED"]}}});if(pending)throw new Error("SUBSCRIPTION_REQUEST_EXISTS");await prisma.$transaction([prisma.userPlan.create({data:{userId:user.id,planId:plan.id,status:"REQUESTED"}}),prisma.customer.upsert({where:{userId:user.id},create:{userId:user.id,name:user.name||user.email,phone:user.phone,email:user.email},update:{name:user.name||user.email,phone:user.phone,email:user.email}}),prisma.auditLog.create({data:{actorId:user.id,operation:"subscription.request"}})]);revalidatePath("/dashboard/plans");revalidatePath("/admin/subscriptions");}

export async function updateSubscriptionRequest(data:FormData){const admin=await requireAdmin();const id=text(data,"subscriptionId");const target=text(data,"status") as SubscriptionStatus;if(!Object.values(SubscriptionStatus).includes(target))throw new Error("SUBSCRIPTION_TRANSITION_INVALID");await prisma.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "UserPlan" WHERE "id" = ${id} FOR UPDATE`);const request=await tx.userPlan.findUnique({where:{id}});if(!request||!transitionAllowed(SUBSCRIPTION_TRANSITIONS,request.status,target))throw new Error("SUBSCRIPTION_TRANSITION_INVALID");const startsAt=text(data,"startsAt")?new Date(`${text(data,"startsAt")}T00:00:00.000Z`):request.startsAt;const endsAt=text(data,"endsAt")?new Date(`${text(data,"endsAt")}T23:59:59.999Z`):request.endsAt;if(target==="ACTIVE")await tx.userPlan.updateMany({where:{userId:request.userId,status:"ACTIVE",id:{not:id}},data:{status:"EXPIRED",endsAt:new Date()}});await tx.userPlan.update({where:{id},data:{status:target,startsAt,endsAt,adminNote:text(data,"reason")||null}});await tx.auditLog.create({data:{actorId:admin.id,operation:`subscription.${target.toLowerCase()}`,targetId:id,metadata:{userId:request.userId}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});revalidatePath("/admin/subscriptions");revalidatePath("/admin/customers");}

type CartLine={productId:string;quantity:number};
function parseCart(raw:string){let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("CART_INVALID")};if(!Array.isArray(value)||value.length<1||value.length>50)throw new Error("CART_INVALID");return value.map(line=>{const item=line as Partial<CartLine>;const quantity=Number(item.quantity);if(typeof item.productId!=="string"||!Number.isSafeInteger(quantity)||quantity<1||quantity>100)throw new Error("CART_INVALID");return{productId:item.productId,quantity};});}

export async function createStoreOrder(data:FormData){const user=await requireUser();const lines=parseCart(text(data,"cart"));await prisma.$transaction(async tx=>{const products=await tx.inventoryItem.findMany({where:{id:{in:lines.map(line=>line.productId)},isActive:true}});if(products.length!==new Set(lines.map(line=>line.productId)).size)throw new Error("PRODUCT_NOT_FOUND");const productById=new Map(products.map(product=>[product.id,product]));for(const line of lines){const product=productById.get(line.productId)!;const produced=await tx.inventoryBatch.aggregate({where:{productId:product.id},_sum:{availableQuantity:true}});const available=storeAvailability({type:product.type,rawAvailable:product.quantityOnHand-product.quantityReserved,producedAvailable:produced._sum.availableQuantity||0});if(available<line.quantity)throw new Error("INSUFFICIENT_STOCK");if(producedTypes.has(product.type)){let remaining=line.quantity;const batches=await tx.inventoryBatch.findMany({where:{productId:product.id,availableQuantity:{gt:0}},orderBy:{createdAt:"asc"}});for(const batch of batches){const take=Math.min(remaining,batch.availableQuantity);if(take>0){const updated=await tx.inventoryBatch.updateMany({where:{id:batch.id,availableQuantity:{gte:take}},data:{availableQuantity:{decrement:take}}});if(updated.count!==1)throw new Error("INSUFFICIENT_STOCK");remaining-=take;}if(!remaining)break;}if(remaining)throw new Error("INSUFFICIENT_STOCK");}else await tx.inventoryItem.update({where:{id:product.id},data:{quantityReserved:{increment:line.quantity}}});}
    const customer=await tx.customer.upsert({where:{userId:user.id},create:{userId:user.id,name:user.name||user.email,phone:user.phone,email:user.email},update:{name:user.name||user.email,phone:user.phone,email:user.email}});let subtotal=new Prisma.Decimal(0);const orderItems=lines.map(line=>{const product=productById.get(line.productId)!;const total=product.sellingPrice.mul(line.quantity);subtotal=subtotal.plus(total);return{inventoryItemId:product.id,description:product.nameEn,quantity:line.quantity,unitPrice:product.sellingPrice,total};});const order=await tx.order.create({data:{customerId:customer.id,status:"NEW",subtotal,total:subtotal,paidAmount:0,paymentStatus:"UNPAID",notes:text(data,"notes")||null,createdBy:user.id,items:{create:orderItems}}});await tx.auditLog.create({data:{actorId:user.id,operation:"store.order.create",targetId:order.id,metadata:{itemCount:orderItems.length}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});revalidatePath("/dashboard/products");revalidatePath("/admin/orders");redirect("/dashboard/products?ordered=1");}

export async function updateStoreOrder(data:FormData){const admin=await requireAdmin();const id=text(data,"orderId");const target=text(data,"status") as OrderStatus;if(!Object.values(OrderStatus).includes(target))throw new Error("ORDER_TRANSITION_INVALID");await prisma.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Order" WHERE "id" = ${id} FOR UPDATE`);const order=await tx.order.findUnique({where:{id},include:{items:{include:{inventoryItem:true}}}});if(!order||!transitionAllowed(ORDER_TRANSITIONS,order.status,target))throw new Error("ORDER_TRANSITION_INVALID");if(target==="CANCELLED"){for(const item of order.items){if(!item.inventoryItem)continue;if(producedTypes.has(item.inventoryItem.type)){let remaining=item.quantity;const batches=await tx.inventoryBatch.findMany({where:{productId:item.inventoryItem.id},orderBy:{createdAt:"asc"}});for(const batch of batches){const capacity=batch.producedQuantity-batch.availableQuantity-batch.assignedQuantity-batch.damagedQuantity;const giveBack=Math.min(remaining,Math.max(0,capacity));if(giveBack){await tx.inventoryBatch.update({where:{id:batch.id},data:{availableQuantity:{increment:giveBack}}});remaining-=giveBack;}if(!remaining)break;}}else await tx.inventoryItem.update({where:{id:item.inventoryItem.id},data:{quantityReserved:{decrement:item.quantity}}});}}const paid=target==="PAID";const refunded=target==="REFUNDED";await tx.order.update({where:{id},data:{status:target,paymentStatus:paid?PaymentStatus.PAID:refunded?PaymentStatus.REFUNDED:order.paymentStatus,paidAmount:paid?order.total:refunded?0:order.paidAmount}});await tx.auditLog.create({data:{actorId:admin.id,operation:`order.${target.toLowerCase()}`,targetId:id}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});revalidatePath("/admin/orders");revalidatePath(`/admin/orders/${id}`);}
