import Link from "next/link";
import { ArrowUpLeft, BarChart3, Check, Download, FileText, Link2, Nfc, QrCode, ShieldCheck, Smartphone, UserRound, Zap } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { getI18n } from "@/lib/i18n";
import { LocaleSwitcher } from "@/components/locale-switcher";

export default async function HomePage() {
  const { locale, dictionary: d } = await getI18n(); const ar = locale === "ar";
  const copy = ar ? { signIn:"لدي حساب", download:"تحميل التطبيق", activate:"تفعيل كارت", badge:"بطاقتك. هويتك. لمسة واحدة.", title:"بطاقتك الذكية في لمسة واحدة", description:"شارك بياناتك، روابطك، ملفك التعريفي وبيانات التواصل باستخدام NFC وQR.", how:"كيف يعمل POPWAM Tap؟", howText:"من فتح العبوة إلى مشاركة بياناتك في خمس خطوات بسيطة وآمنة.", features:"كل ما تحتاجه في بطاقة واحدة", app:"تطبيقك معك أينما كنت", appText:"أدر بطاقاتك وملفاتك وروابطك من تطبيق POPWAM Tap على Android." } : { signIn:"I have an account", download:"Download app", activate:"Activate a card", badge:"Your card. Your identity. One tap.", title:"Your smart card in one tap", description:"Share your details, links, profile and contact information using NFC and QR.", how:"How does POPWAM Tap work?", howText:"From opening the box to sharing your details in five simple, secure steps.", features:"Everything you need in one card", app:"Your app, wherever you go", appText:"Manage cards, profiles and links from POPWAM Tap for Android." };
  const steps = ar ? ["المس الكارت بالموبايل","امسح QR التفعيل","تحقق برقم الهاتف","اختر ما يفتحه الكارت","شارك بياناتك فورًا"] : ["Tap the card on a phone","Scan the activation QR","Verify your phone","Choose what the card opens","Share instantly"];
  const features = [[UserRound, ar?"ملف شخصي أو شركة":"Personal or business profile"],[Nfc,"NFC"],[QrCode,"QR"],[FileText,"vCard & files"],[Link2,ar?"روابط التواصل":"Social links"],[Zap,ar?"تغيير الوجهة فورًا":"Change destination instantly"],[BarChart3,ar?"تحليلات بسيطة":"Simple analytics"],[ShieldCheck,ar?"تفعيل آمن":"Secure activation"]] as const;
  return <main className="landing-shell overflow-hidden"><header className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-5 sm:px-8"><Link href="/" className="text-xl font-black tracking-tight"><span className="text-brand-400">POPWAM</span> Tap</Link><nav className="flex items-center gap-2"><LocaleSwitcher locale={locale} label={d.common.language}/><Link href="/login/phone" className="hidden rounded-xl px-3 py-2 text-sm text-slate-300 hover:bg-white/5 sm:block">{copy.signIn}</Link><Link href="/download" className="btn-primary px-3 sm:px-4"><Download size={16}/><span className="hidden sm:inline">{copy.download}</span></Link></nav></header>
    <section className="mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><p className="inline-flex rounded-full border border-brand-400/20 bg-brand-400/10 px-4 py-2 text-xs font-bold text-brand-400">{copy.badge}</p><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[1.08] tracking-[-.045em] sm:text-7xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400 sm:text-xl">{copy.description}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/activate/scan" className="btn-primary px-6 py-3.5"><QrCode size={18}/>{copy.activate}</Link><Link href="/download" className="btn-secondary px-6 py-3.5"><Download size={18}/>{copy.download}</Link><Link href="/login/phone" className="btn-secondary px-6 py-3.5">{copy.signIn}</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500">{(ar?["دون كلمات مرور","تفعيل لمرة واحدة","تغيير الوجهة في أي وقت"]:["Passwordless","One-time activation","Change anytime"]).map(item=><span className="flex items-center gap-2" key={item}><Check size={15} className="text-brand-400"/>{item}</span>)}</div></div>
      <div className="hero-visual relative mx-auto w-full max-w-[580px]" aria-label={ar?"نموذج بطاقة POPWAM وهاتف وQR":"POPWAM card, phone and QR mockup"}><div className="smart-card-mock relative z-10 aspect-[1.58/1] w-[78%] overflow-hidden rounded-[2rem] border border-white/15 p-7 shadow-2xl"><div className="flex justify-between"><span className="text-lg font-black">POPWAM</span><Nfc className="text-brand-400"/></div><div className="absolute bottom-7 start-7"><p className="text-xs text-slate-400">POPWAM Tap</p><p className="mt-1 font-mono text-sm">PW •••• 0142</p></div></div><div className="phone-mock absolute -bottom-44 end-0 z-20 w-[48%] rounded-[2.4rem] border-[7px] border-[#262a31] bg-[#0b0d12] p-3 shadow-2xl"><div className="mx-auto h-1.5 w-16 rounded-full bg-white/15"/><div className="mt-5 rounded-3xl bg-gradient-to-b from-brand-500/20 to-white/[.03] p-4 text-center"><div className="mx-auto h-16 w-16 rounded-full border-2 border-brand-400 bg-slate-800"/><p className="mt-3 font-bold">Mamdouh</p><p className="text-xs text-slate-400">POPWAM</p><div className="mx-auto mt-4 w-fit rounded-xl bg-white p-2"><QRCodeSVG value="https://app.popwam.com" size={76} bgColor="#ffffff" fgColor="#080a0d"/></div></div></div><div className="absolute -bottom-32 start-3 z-30 rounded-2xl border border-white/10 bg-[#151820]/95 p-4 shadow-xl"><p className="text-xs font-bold text-brand-400">NFC READY</p><p className="mt-1 text-sm text-slate-300">{ar?"قرّب الهاتف للمشاركة":"Tap to share"}</p></div></div>
    </section><section className="mx-auto max-w-7xl px-5 pb-24 pt-32 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-bold text-brand-400">01 — NFC + QR</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">{copy.how}</h2><p className="mt-4 text-slate-400">{copy.howText}</p></div><div className="mt-10 grid gap-3 md:grid-cols-5">{steps.map((step,index)=><div className="card relative p-5" key={step}><span className="text-4xl font-black text-white/10">0{index+1}</span><p className="mt-5 font-bold leading-7">{step}</p></div>)}</div></section>
    <section className="border-y border-white/[.06] bg-white/[.02]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><h2 className="text-center text-3xl font-black sm:text-5xl">{copy.features}</h2><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,label])=><div className="flex items-center gap-4 rounded-2xl border border-white/[.08] bg-black/20 p-5" key={label}><span className="rounded-xl bg-brand-400/10 p-3 text-brand-400"><Icon size={22}/></span><p className="font-semibold">{label}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-24 sm:px-8 lg:grid-cols-2"><div><p className="text-sm font-bold text-brand-400">ANDROID</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">{copy.app}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-400">{copy.appText}</p><Link href="/download" className="btn-primary mt-8 px-6 py-3.5">{copy.download}<ArrowUpLeft className="directional-icon" size={17}/></Link></div><div className="card flex items-center justify-center gap-7 p-8"><Smartphone size={100} strokeWidth={1} className="text-brand-400"/><div><p className="text-xl font-black">POPWAM Tap</p><p className="mt-2 text-sm text-slate-400">Android • Secure • Fast</p><div className="mt-5 rounded-xl bg-white p-2"><QRCodeSVG value="https://app.popwam.com/download" size={110} bgColor="#ffffff" fgColor="#080a0d"/></div></div></div></section>
    <footer className="border-t border-white/[.06]"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p>© {new Date().getFullYear()} POPWAM. {ar?"جميع الحقوق محفوظة.":"All rights reserved."}</p><div className="flex flex-wrap gap-5"><Link href="/privacy">{ar?"سياسة الخصوصية":"Privacy"}</Link><Link href="/terms">{ar?"الشروط":"Terms"}</Link><a href="mailto:support@popwam.com">{ar?"الدعم":"Support"}</a><a href="mailto:hello@popwam.com">{ar?"تواصل معنا":"Contact"}</a></div></div></footer></main>;
}
