"use server";

import {FeatureRequestStatus,FriendPrivacyLevel,FriendshipStatus,MessageReportStatus,Prisma,prisma} from "@popwam/db";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {requireAdmin,requireUser} from "@/lib/session";
import {canonicalUserPair,directChatKey,otherFriendId} from "@/lib/social";

const text=(data:FormData,key:string)=>String(data.get(key)||"").trim();
const cleanUsername=(value:string)=>value.toLowerCase().replace(/^@/,"");
const usernameValid=(value:string)=>/^[a-z0-9][a-z0-9._-]{2,31}$/.test(value);

async function acceptedFriendship(userId:string,friendId:string){const pair=canonicalUserPair(userId,friendId);return prisma.friendship.findFirst({where:{...pair,status:"ACCEPTED"}});}

export async function requestFriend(data:FormData){const user=await requireUser();const username=cleanUsername(text(data,"username"));if(!usernameValid(username))throw new Error("USERNAME_INVALID");const friend=await prisma.user.findUnique({where:{username},select:{id:true,status:true}});if(!friend||friend.id===user.id||friend.status!=="ACTIVE")throw new Error("USER_NOT_AVAILABLE");const pair=canonicalUserPair(user.id,friend.id);await prisma.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "User" WHERE "id" IN (${user.id}, ${friend.id}) ORDER BY "id" FOR UPDATE`);const existing=await tx.friendship.findUnique({where:{userAId_userBId:pair}});if(existing?.status==="BLOCKED"||existing?.status==="ACCEPTED")throw new Error("FRIEND_REQUEST_NOT_ALLOWED");await tx.friendship.upsert({where:{userAId_userBId:pair},create:{...pair,requestedById:user.id},update:{requestedById:user.id,blockedById:null,status:"PENDING"}});await tx.auditLog.create({data:{actorId:user.id,operation:"friend.request",targetId:friend.id}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});revalidatePath("/dashboard/friends");}

export async function respondFriend(data:FormData){const user=await requireUser();const id=text(data,"friendshipId");const response=text(data,"response");if(!["accept","reject"].includes(response))throw new Error("FRIEND_RESPONSE_INVALID");await prisma.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Friendship" WHERE "id" = ${id} FOR UPDATE`);const friendship=await tx.friendship.findUnique({where:{id}});if(!friendship||friendship.status!=="PENDING"||friendship.requestedById===user.id||![friendship.userAId,friendship.userBId].includes(user.id))throw new Error("FRIEND_REQUEST_NOT_AVAILABLE");const status:FriendshipStatus=response==="accept"?"ACCEPTED":"REJECTED";await tx.friendship.update({where:{id},data:{status}});await tx.auditLog.create({data:{actorId:user.id,operation:`friend.${response}`,targetId:id}});});revalidatePath("/dashboard/friends");}

export async function updateFriendship(data:FormData){const user=await requireUser();const id=text(data,"friendshipId");const action=text(data,"friendAction");await prisma.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Friendship" WHERE "id" = ${id} FOR UPDATE`);const friendship=await tx.friendship.findUnique({where:{id}});if(!friendship||![friendship.userAId,friendship.userBId].includes(user.id))throw new Error("FRIENDSHIP_ACCESS_DENIED");const friendId=otherFriendId(friendship,user.id);if(action==="favorite"&&friendship.status==="ACCEPTED")await tx.friendship.update({where:{id},data:friendship.userAId===user.id?{favoriteA:!friendship.favoriteA}:{favoriteB:!friendship.favoriteB}});else if(action==="block")await tx.friendship.update({where:{id},data:{status:"BLOCKED",blockedById:user.id}});else if(action==="remove"&&friendship.status!=="BLOCKED"){await tx.friendPrivacyRule.deleteMany({where:{OR:[{ownerId:user.id,friendId},{ownerId:friendId,friendId:user.id}]}});await tx.friendship.delete({where:{id}});}else throw new Error("FRIEND_ACTION_INVALID");await tx.auditLog.create({data:{actorId:user.id,operation:`friend.${action}`,targetId:friendId}});});revalidatePath("/dashboard/friends");}

export async function updateFriendPrivacy(data:FormData){const user=await requireUser();const friendId=text(data,"friendId");const level=text(data,"level") as FriendPrivacyLevel;if(!Object.values(FriendPrivacyLevel).includes(level)||!(await acceptedFriendship(user.id,friendId)))throw new Error("PRIVACY_RULE_INVALID");let selectedDestinationIds=data.getAll("destinationId").map(String);if(level==="SELECTED_LINKS"){const count=await prisma.destination.count({where:{id:{in:selectedDestinationIds},userId:user.id}});if(count!==new Set(selectedDestinationIds).size)throw new Error("PRIVACY_LINK_INVALID");}else selectedDestinationIds=[];await prisma.$transaction([prisma.friendPrivacyRule.upsert({where:{ownerId_friendId:{ownerId:user.id,friendId}},create:{ownerId:user.id,friendId,level,selectedDestinationIds},update:{level,selectedDestinationIds}}),prisma.auditLog.create({data:{actorId:user.id,operation:"friend.privacy.update",targetId:friendId,metadata:{level}}})]);revalidatePath("/dashboard/friends");}

export async function startChat(data:FormData){const user=await requireUser();const username=cleanUsername(text(data,"username"));if(!usernameValid(username))throw new Error("USERNAME_INVALID");const friend=await prisma.user.findUnique({where:{username},select:{id:true}});if(!friend||!(await acceptedFriendship(user.id,friend.id)))throw new Error("CHAT_REQUIRES_FRIEND");const directKey=directChatKey(user.id,friend.id);const chat=await prisma.chat.upsert({where:{directKey},create:{directKey,members:{create:[{userId:user.id},{userId:friend.id}]}},update:{}});redirect(`/dashboard/chats/${chat.id}`);}

export async function sendMessage(data:FormData){const user=await requireUser();const chatId=text(data,"chatId");const body=text(data,"body").slice(0,4000);const attachmentFileId=text(data,"attachmentFileId")||null;const membership=await prisma.chatMember.findUnique({where:{chatId_userId:{chatId,userId:user.id}}});if(!membership)throw new Error("CHAT_ACCESS_DENIED");if(attachmentFileId&&!await prisma.uploadedFile.findFirst({where:{id:attachmentFileId,uploaderUserId:user.id}}))throw new Error("ATTACHMENT_ACCESS_DENIED");if(!body&&!attachmentFileId)throw new Error("MESSAGE_EMPTY");await prisma.$transaction([prisma.message.create({data:{chatId,senderId:user.id,body:body||null,attachmentFileId}}),prisma.chat.update({where:{id:chatId},data:{updatedAt:new Date()}}),prisma.chatMember.update({where:{chatId_userId:{chatId,userId:user.id}},data:{lastReadAt:new Date()}})]);revalidatePath(`/dashboard/chats/${chatId}`);revalidatePath("/dashboard/chats");}

export async function markChatRead(data:FormData){const user=await requireUser();const chatId=text(data,"chatId");const result=await prisma.chatMember.updateMany({where:{chatId,userId:user.id},data:{lastReadAt:new Date()}});if(result.count!==1)throw new Error("CHAT_ACCESS_DENIED");revalidatePath("/dashboard/chats");}

export async function reportMessage(data:FormData){const user=await requireUser();const messageId=text(data,"messageId");const reason=text(data,"reason").slice(0,1000);const message=await prisma.message.findUnique({where:{id:messageId},select:{chatId:true}});if(!message||!reason||!await prisma.chatMember.findUnique({where:{chatId_userId:{chatId:message.chatId,userId:user.id}}}))throw new Error("MESSAGE_REPORT_INVALID");await prisma.$transaction([prisma.messageReport.upsert({where:{messageId_reporterId:{messageId,reporterId:user.id}},create:{messageId,reporterId:user.id,reason},update:{reason,status:"OPEN",reviewedById:null,reviewNote:null}}),prisma.auditLog.create({data:{actorId:user.id,operation:"message.report",targetId:messageId}})]);revalidatePath(`/dashboard/chats/${message.chatId}`);revalidatePath("/admin/reports");}

export async function updateMessageReport(data:FormData){const admin=await requireAdmin();const id=text(data,"reportId");const status=text(data,"status") as MessageReportStatus;if(!Object.values(MessageReportStatus).includes(status))throw new Error("REPORT_STATUS_INVALID");await prisma.$transaction([prisma.messageReport.update({where:{id},data:{status,reviewedById:admin.id,reviewNote:text(data,"reviewNote").slice(0,2000)||null}}),prisma.auditLog.create({data:{actorId:admin.id,operation:"moderation.report.update",targetId:id,metadata:{status}}})]);revalidatePath("/admin/reports");revalidatePath(`/admin/reports/${id}`);}

export async function createFeatureRequest(data:FormData){const user=await requireUser();const title=text(data,"title").slice(0,160);const description=text(data,"description").slice(0,5000);if(title.length<4||description.length<10)throw new Error("FEATURE_REQUEST_INVALID");await prisma.$transaction([prisma.featureRequest.create({data:{authorId:user.id,title,description}}),prisma.auditLog.create({data:{actorId:user.id,operation:"feature.request.create"}})]);revalidatePath("/ideas");revalidatePath("/admin/feature-requests");}

export async function toggleFeatureVote(data:FormData){const user=await requireUser();const featureRequestId=text(data,"featureRequestId");await prisma.$transaction(async tx=>{if(!await tx.featureRequest.findUnique({where:{id:featureRequestId}}))throw new Error("FEATURE_REQUEST_NOT_FOUND");const key={featureRequestId_userId:{featureRequestId,userId:user.id}};const existing=await tx.featureVote.findUnique({where:key});if(existing)await tx.featureVote.delete({where:key});else await tx.featureVote.create({data:{featureRequestId,userId:user.id}});});revalidatePath("/ideas");}

export async function commentFeatureRequest(data:FormData){const user=await requireUser();const featureRequestId=text(data,"featureRequestId");const body=text(data,"body").slice(0,2000);if(body.length<2)throw new Error("COMMENT_INVALID");await prisma.featureComment.create({data:{featureRequestId,authorId:user.id,body}});revalidatePath("/ideas");}

export async function updateFeatureRequest(data:FormData){const admin=await requireAdmin();const id=text(data,"featureRequestId");const status=text(data,"status") as FeatureRequestStatus;const mergedIntoId=text(data,"mergedIntoId")||null;if(!Object.values(FeatureRequestStatus).includes(status)||mergedIntoId===id)throw new Error("FEATURE_STATUS_INVALID");if(mergedIntoId&&!await prisma.featureRequest.findUnique({where:{id:mergedIntoId}}) )throw new Error("MERGE_TARGET_INVALID");await prisma.$transaction([prisma.featureRequest.update({where:{id},data:{status,adminResponse:text(data,"adminResponse").slice(0,3000)||null,mergedIntoId}}),prisma.auditLog.create({data:{actorId:admin.id,operation:"feature.request.update",targetId:id,metadata:{status,merged:Boolean(mergedIntoId)}}})]);revalidatePath("/ideas");revalidatePath("/admin/feature-requests");}
