import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@popwam/db";
import { CreditCard, QrCode, ShieldCheck } from "lucide-react";
import { getI18n } from "@/lib/i18n";

export default async function CardActivationPage({ params }: { params: Promise<{ publicSlug: string }> }) {
  const { publicSlug } = await params; const [{ locale }, card] = await Promise.all([getI18n(), prisma.card.findUnique({ where: { publicSlug: publicSlug.toLowerCase() }, select: { serialNumber: true, cardType: true, cardStatus: true, assignmentStatus: true, ownerId: true, publicSlug: true } })]);
  if (!card) notFound(); const ar = locale === "ar"; const claimed = Boolean(card.ownerId) || card.assignmentStatus !== "UNASSIGNED"; const suspended = ["PAUSED","LOST","DISABLED","ARCHIVED"].includes(card.cardStatus);
  return <main className="landing-shell flex min-h-screen items-center justify-center px-5 py-10"><div className="card w-full max-w-xl overflow-hidden"><div className="smart-card-mock m-5 aspect-[1.7/1] rounded-3xl border border-white/10 p-6"><div className="flex items-center justify-between"><strong>POPWAM</strong><CreditCard className="text-brand-400"/></div><p className="mt-20 font-mono text-sm" dir="ltr">{card.serialNumber.slice(0,4)} •••• {card.serialNumber.slice(-4)}</p></div><div className="p-6 pt-1 text-center"><p className="text-xs font-black text-brand-400">POPWAM Tap</p><h1 className="mt-3 text-2xl font-black">{suspended?(ar?"هذا الكارت موقوف":"This card is suspended"):claimed?(ar?"تم تفعيل هذا الكارت":"This card is already activated"):(ar?"هذا الكارت غير مفعّل":"This card is not activated")}</h1><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-slate-400">{suspended?(ar?"لا يمكن بدء التفعيل حاليًا. تواصل مع الدعم إن كنت مالك الكارت.":"Activation is unavailable. Contact support if you own this card."):claimed?(ar?"تم تفعيل هذا الكارت بواسطة حساب آخر ولا يمكن المطالبة به مرة ثانية.":"Another account has activated this card; it cannot be claimed again."):(ar?"ستمسح QR الموجود داخل العبوة، ثم تتحقق من رقم هاتفك قبل ربط الكارت بحسابك.":"Scan the QR inside the package, verify your phone, then confirm the card claim.")}</p>{!claimed&&!suspended&&<Link href={`/activate/scan?card=${encodeURIComponent(card.publicSlug)}`} className="btn-primary mt-6 w-full py-3.5"><QrCode size={18}/>{ar?"ابدأ التفعيل":"Start activation"}</Link>}<div className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-500"><ShieldCheck size={15}/>{ar?"المسح وحده لا يربط الكارت — يلزم OTP وتأكيد نهائي":"Scanning alone never claims a card — OTP and confirmation are required"}</div></div></div></main>;
}
