import { prisma } from "@popwam/db";
import { saveLinkPlatform, toggleLinkPlatform } from "@/app/catalog-actions";
import { Badge } from "@/components/badge";
import { PageHeading } from "@/components/page-heading";

function PlatformFields({ platform }: { platform?: Awaited<ReturnType<typeof prisma.linkPlatform.findFirst>> }) {
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    {platform && <input type="hidden" name="id" value={platform.id}/>}<input className="input" name="nameEn" defaultValue={platform?.nameEn} placeholder="English name" required/><input className="input" name="nameAr" defaultValue={platform?.nameAr} placeholder="الاسم العربي" required/><input className="input" name="slug" defaultValue={platform?.slug} placeholder="slug" pattern="[a-z0-9-]+" required/><input className="input" name="category" defaultValue={platform?.category || "SOCIAL"} placeholder="Category"/>
    <select className="input" name="inputType" defaultValue={platform?.inputType || "FULL_URL"}>{[["USERNAME","Username"],["PHONE","Phone number"],["EMAIL","Email"],["FULL_URL","Full URL"],["USERNAME_OR_URL","Username or URL"],["CHANNEL_ID","Channel ID"],["CUSTOM_TEXT","Custom text"]].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>
    <input className="input" name="placeholder" defaultValue={platform?.placeholder} placeholder="User input placeholder" required/><input className="input xl:col-span-2" name="urlTemplate" defaultValue={platform?.urlTemplate || ""} placeholder="https://example.com/{value}" dir="ltr"/>
    <input className="input" name="iconKey" defaultValue={platform?.iconKey || "link"} placeholder="Default icon key"/><input className="input" name="sortOrder" type="number" min="0" defaultValue={platform?.sortOrder || 0}/><input className="input xl:col-span-2" name="validationPattern" defaultValue={platform?.validationPattern || ""} placeholder="Optional validation regex" dir="ltr"/>
    <input className="input xl:col-span-2" name="androidAppUrl" defaultValue={platform?.androidAppUrl || ""} placeholder="Android app opening link" dir="ltr"/><input className="input xl:col-span-2" name="iosAppUrl" defaultValue={platform?.iosAppUrl || ""} placeholder="iOS app opening link" dir="ltr"/><input className="input xl:col-span-2" name="webFallback" defaultValue={platform?.webFallback || ""} placeholder="Web fallback URL" dir="ltr"/>
    <textarea className="input min-h-24 xl:col-span-2" name="helpEn" defaultValue={platform?.helpEn || ""} placeholder="English help: open your profile, copy its link, return here, and paste it."/><textarea className="input min-h-24 xl:col-span-2" name="helpAr" defaultValue={platform?.helpAr || ""} placeholder="تعليمات المساعدة بالعربية"/>
    <input className="input xl:col-span-2" name="customIconUrl" defaultValue={platform?.customIconUrl || ""} placeholder="Existing custom icon URL" dir="ltr"/><label className="input flex items-center gap-2 xl:col-span-2">Upload icon<input type="file" name="iconFile" accept="image/jpeg,image/png,image/webp"/></label>
    <label className="flex items-center gap-2"><input type="checkbox" name="isActive" defaultChecked={platform?.isActive ?? true}/>Active</label><label className="flex items-center gap-2"><input type="checkbox" name="allowCustomLabel" defaultChecked={platform?.allowCustomLabel}/>Allow custom label</label><label className="flex items-center gap-2"><input type="checkbox" name="allowCustomIcon" defaultChecked={platform?.allowCustomIcon}/>Allow uploaded custom icon</label>
  </div>;
}

export default async function LinkPlatformsPage() {
  const platforms = await prisma.linkPlatform.findMany({ orderBy: [{ sortOrder: "asc" }, { nameEn: "asc" }] });
  return <><PageHeading eyebrow="Catalog" title="Link platforms / منصات الروابط" description="Configure username builders, safe app-opening helpers, manual paste instructions, validation, and fallback behavior without collecting social passwords or pretending to copy from another app."/><details className="card mb-6 p-5"><summary className="cursor-pointer font-bold">Add platform</summary><form action={saveLinkPlatform} className="mt-4"><PlatformFields/><button className="btn-primary mt-4">Save platform</button></form></details><div className="space-y-3">{platforms.map(platform => <details className="card p-5" key={platform.id}><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><strong>{platform.nameEn} / {platform.nameAr}</strong><span className="ms-3 font-mono text-xs text-slate-500">{platform.slug} · {platform.inputType}</span></span><Badge value={platform.isActive ? "ACTIVE" : "DISABLED"}/></summary><form action={saveLinkPlatform} className="mt-4 border-t border-white/10 pt-4"><PlatformFields platform={platform}/><button className="btn-secondary mt-4">Save changes</button></form><form action={toggleLinkPlatform} className="mt-3"><input type="hidden" name="id" value={platform.id}/><button className="btn-secondary">{platform.isActive ? "Deactivate" : "Activate"}</button></form></details>)}</div></>;
}
