import { prisma } from "@popwam/db";
import { saveLinkPlatform, toggleLinkPlatform } from "@/app/catalog-actions";
import { Badge } from "@/components/badge";
import { PageHeading } from "@/components/page-heading";

function PlatformFields({ platform }: { platform?: Awaited<ReturnType<typeof prisma.linkPlatform.findFirst>> }) {
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{platform && <input type="hidden" name="id" value={platform.id}/>}<input className="input" name="nameEn" defaultValue={platform?.nameEn} placeholder="English name" required/><input className="input" name="nameAr" defaultValue={platform?.nameAr} placeholder="الاسم العربي" required/><input className="input" name="slug" defaultValue={platform?.slug} placeholder="slug" pattern="[a-z0-9-]+" required/><input className="input" name="iconKey" defaultValue={platform?.iconKey || "link"} placeholder="Icon key"/><input className="input" name="placeholder" defaultValue={platform?.placeholder} placeholder="User input placeholder" required/><input className="input" name="validationPattern" defaultValue={platform?.validationPattern || ""} placeholder="Optional validation regex" dir="ltr"/><input className="input" name="category" defaultValue={platform?.category || "SOCIAL"} placeholder="Category"/><input className="input" name="sortOrder" type="number" min="0" defaultValue={platform?.sortOrder || 0}/><input className="input xl:col-span-2" name="customIconUrl" defaultValue={platform?.customIconUrl || ""} placeholder="Existing custom icon URL" dir="ltr"/><label className="input flex items-center gap-2 xl:col-span-2">Upload icon<input type="file" name="iconFile" accept="image/jpeg,image/png,image/webp"/></label><label className="flex items-center gap-2"><input type="checkbox" name="isActive" defaultChecked={platform?.isActive ?? true}/>Active</label><label className="flex items-center gap-2"><input type="checkbox" name="allowCustomLabel" defaultChecked={platform?.allowCustomLabel}/>Allow custom label</label></div>;
}

export default async function LinkPlatformsPage() {
  const platforms = await prisma.linkPlatform.findMany({ orderBy: [{ sortOrder: "asc" }, { nameEn: "asc" }] });
  return <><PageHeading eyebrow="Catalog" title="Link platforms / منصات الروابط" description="This database catalog drives onboarding. Add Anghami or any supported platform here instead of hardcoding it in the client."/><details className="card mb-6 p-5"><summary className="cursor-pointer font-bold">Add platform</summary><form action={saveLinkPlatform} className="mt-4"><PlatformFields/><button className="btn-primary mt-4">Save platform</button></form></details><div className="space-y-3">{platforms.map(platform => <details className="card p-5" key={platform.id}><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><strong>{platform.nameEn} / {platform.nameAr}</strong><span className="ms-3 font-mono text-xs text-slate-500">{platform.slug}</span></span><Badge value={platform.isActive ? "ACTIVE" : "DISABLED"}/></summary><form action={saveLinkPlatform} className="mt-4 border-t border-white/10 pt-4"><PlatformFields platform={platform}/><button className="btn-secondary mt-4">Save changes</button></form><form action={toggleLinkPlatform} className="mt-3"><input type="hidden" name="id" value={platform.id}/><button className="btn-secondary">{platform.isActive ? "Deactivate" : "Activate"}</button></form></details>)}</div></>;
}
