import { DestinationType, prisma } from "@popwam/db";
import { requireUser } from "@/lib/session";
import { getI18n } from "@/lib/i18n";
import { getUserEntitlements, getUserUsage } from "@/lib/plans";
import { createDestination, deleteDestination, updateDestination } from "@/app/actions";
import { PageHeading } from "@/components/page-heading";
import { DestinationIcon } from "@/components/destination-icon";
import { IconSelector } from "@/components/icon-selector";
import { ExternalLink, Plus, Trash2 } from "lucide-react";

type Item = { title: string; titleAr:string|null;titleEn:string|null;type:DestinationType;url:string;iconKey:string|null;customIconUrl:string|null;isOfflineCapable:boolean;isActive:boolean };
function DestinationFields({item,locale}:{item?:Item;locale:"ar"|"en"}){const ar=locale==="ar";return <div className="grid gap-4 sm:grid-cols-2"><label><span className="label">{ar?"العنوان الأساسي":"Default title"}</span><input className="input" name="title" required defaultValue={item?.title}/></label><label><span className="label">{ar?"النوع":"Type"}</span><select className="input" name="type" defaultValue={item?.type||"WEBSITE"}>{Object.values(DestinationType).map(type=><option key={type}>{type}</option>)}</select></label><label><span className="label">العنوان بالعربية</span><input className="input" name="titleAr" defaultValue={item?.titleAr||""}/></label><label><span className="label">English title</span><input className="input" name="titleEn" defaultValue={item?.titleEn||""}/></label><label className="sm:col-span-2"><span className="label">{ar?"الوجهة":"Destination"}</span><input className="input" name="url" required={item?.type!=="PROFILE"} defaultValue={item?.url} placeholder="Website, email, phone, or safe URL" dir="ltr"/></label><IconSelector value={item?.iconKey} locale={locale}/><label><span className="label">{ar?"رابط أيقونة مخصصة (حسب الخطة)":"Custom icon URL (plan permitting)"}</span><input className="input" name="customIconUrl" defaultValue={item?.customIconUrl||""} dir="ltr"/></label><label className="flex items-end gap-2 pb-2 text-sm text-slate-300"><input type="checkbox" name="isActive" defaultChecked={item?.isActive??true} className="size-4 accent-brand-400"/> {ar?"وجهة نشطة":"Active destination"}</label></div>}
export default async function CardsPage(){const user=await requireUser();const [{locale},destinations,{effective},usage]=await Promise.all([getI18n(),prisma.destination.findMany({where:{userId:user.id},orderBy:{createdAt:"asc"}}),getUserEntitlements(user.id),getUserUsage(user.id)]);const ar=locale==="ar";return <><PageHeading eyebrow="Routing" title={ar?"الروابط والوجهات":"Links & destinations"} description={ar?"اختر أيقونة آمنة ووجّه بطاقتك إلى الملف أو الرابط المطلوب.":"Choose a safe icon and route a card to the intended profile or link."}/><p className="mb-5 text-sm text-slate-400">{ar?"الروابط":"Links"}: <strong className="text-white">{usage.links} / {effective.maxLinks}</strong></p><details className="card mb-6 p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-bold"><Plus size={18} className="text-brand-400"/> {ar?"وجهة جديدة":"New destination"}</summary><form action={createDestination} className="mt-5"><DestinationFields locale={locale}/><button className="btn-primary mt-5">{ar?"إنشاء الوجهة":"Create destination"}</button></form></details><div className="grid gap-4 xl:grid-cols-2">{destinations.map(item=><details className="card p-5" key={item.id}><summary className="flex cursor-pointer list-none items-center gap-4"><div className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-white/5">{item.customIconUrl?<img src={item.customIconUrl} alt="" className="size-6 object-contain"/>:<DestinationIcon type={item.type} iconKey={item.iconKey}/>}</div><div className="min-w-0 flex-1"><h2 className="font-bold">{locale==="ar"?item.titleAr||item.titleEn||item.title:item.titleEn||item.titleAr||item.title}</h2><p className="truncate text-xs text-slate-500" dir="ltr">{item.url}</p></div><span className={item.isActive?"text-xs text-emerald-300":"text-xs text-slate-600"}>{item.isActive?"ACTIVE":"HIDDEN"}</span><ExternalLink size={16} className="text-slate-600"/></summary><form action={updateDestination} className="mt-5 border-t border-white/10 pt-5"><input type="hidden" name="id" value={item.id}/><DestinationFields item={item} locale={locale}/><button className="btn-primary mt-5">{ar?"حفظ التغييرات":"Save changes"}</button></form><form action={deleteDestination} className="mt-3"><input type="hidden" name="id" value={item.id}/><button className="btn-danger" disabled={item.type==="PROFILE"||item.type==="VCF"}><Trash2 size={14}/> {ar?"حذف":"Delete"}</button></form></details>)}</div></>}
