"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Image as ImageIcon, Keyboard, RefreshCw, ScanLine, Zap } from "lucide-react";
type Detector = { detect(source: ImageBitmapSource): Promise<Array<{ rawValue: string }>> }; type DetectorCtor = new(options: { formats: string[] }) => Detector;

export function ActivationScanner({ publicSlug = "", locale }: { publicSlug?: string; locale: "ar" | "en" }) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const timer = useRef<number | null>(null); const locked = useRef(false);
  const [mode, setMode] = useState<"choice"|"camera"|"manual">("choice"); const [manual, setManual] = useState(""); const [status, setStatus] = useState(""); const [facingMode, setFacingMode] = useState<"environment"|"user">("environment"); const ar = locale === "ar";
  function stop() { if (timer.current) window.clearInterval(timer.current); timer.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; }
  useEffect(() => stop, []);
  async function submit(value: string) {
    if (locked.current || !value.trim()) return; locked.current = true; setStatus(ar ? "جارٍ التحقق…" : "Verifying…");
    const response = await fetch("/api/activation/start", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ publicSlug, activationValue:value }) }); const result = await response.json().catch(() => ({}));
    if (response.ok) { stop(); window.location.assign(result.nextUrl); return; } locked.current = false;
    const messages: Record<string,string> = ar ? { ACTIVATION_RATE_LIMITED:"محاولات كثيرة. حاول لاحقًا.", ACTIVATION_CARD_MISMATCH:"رمز QR يخص كارتًا مختلفًا.", CARD_ALREADY_ACTIVATED:"تم تفعيل هذا الكارت بالفعل بواسطة حساب آخر.", CARD_SUSPENDED:"هذا الكارت موقوف ولا يمكن تفعيله.", ACTIVATION_INVALID:"QR منتهي أو غير صحيح." } : { ACTIVATION_RATE_LIMITED:"Too many attempts. Try later.", ACTIVATION_CARD_MISMATCH:"This QR belongs to a different card.", CARD_ALREADY_ACTIVATED:"Another account has already activated this card.", CARD_SUSPENDED:"This card is suspended and cannot be activated.", ACTIVATION_INVALID:"This QR is expired or invalid." };
    setStatus(messages[result.error] || (ar ? "تعذر التحقق من QR." : "The QR could not be verified."));
  }
  async function camera(nextFacing = facingMode) {
    const Ctor = (window as unknown as { BarcodeDetector?: DetectorCtor }).BarcodeDetector;
    if (!navigator.mediaDevices?.getUserMedia) { setStatus(ar?"هذا الجهاز لا يحتوي على كاميرا متاحة.":"No camera is available on this device."); return; }
    if (!Ctor) { setStatus(ar?"المسح المباشر غير مدعوم في هذا المتصفح. ارفع صورة أو أدخل الكود يدويًا.":"Live scanning is unavailable in this browser. Upload an image or enter the code."); return; }
    try { stop(); setMode("camera"); stream.current = await navigator.mediaDevices.getUserMedia({ video:{ facingMode:{ ideal:nextFacing } }, audio:false }); if (video.current) { video.current.srcObject = stream.current; await video.current.play(); } const detector = new Ctor({formats:["qr_code"]}); timer.current = window.setInterval(async () => { if (!video.current || video.current.readyState < 2 || locked.current) return; const found = await detector.detect(video.current).catch(() => []); if (found[0]?.rawValue) submit(found[0].rawValue); }, 450); }
    catch { setStatus(ar?"تعذر فتح الكاميرا. اسمح بالوصول إليها أو استخدم صورة QR.":"Camera access failed. Allow access or use a QR image."); setMode("choice"); stop(); }
  }
  async function toggleTorch() { const track = stream.current?.getVideoTracks()[0]; if (!track) return; const capabilities = track.getCapabilities() as MediaTrackCapabilities & { torch?:boolean }; if (!capabilities.torch) { setStatus(ar?"الفلاش غير متاح على هذا الجهاز.":"Flash is unavailable on this device."); return; } const settings = track.getSettings() as MediaTrackSettings & { torch?:boolean }; await track.applyConstraints({ advanced:[{ torch:!settings.torch } as MediaTrackConstraintSet] }).catch(() => setStatus(ar?"تعذر تشغيل الفلاش.":"Could not toggle flash.")); }
  async function switchCamera() { const next = facingMode === "environment" ? "user" : "environment"; setFacingMode(next); await camera(next); }
  async function image(file?: File) { if (!file) return; const Ctor = (window as unknown as { BarcodeDetector?:DetectorCtor }).BarcodeDetector; if (!Ctor) { setStatus(ar?"قراءة الصور غير مدعومة هنا. استخدم الإدخال اليدوي.":"Image QR reading is unavailable here. Use manual entry."); return; } const bitmap = await createImageBitmap(file); const found = await new Ctor({formats:["qr_code"]}).detect(bitmap).catch(() => []); bitmap.close(); if (found[0]?.rawValue) submit(found[0].rawValue); else setStatus(ar?"لم يتم العثور على QR صالح في الصورة.":"No valid QR code was found in the image."); }
  return <div className="card mt-7 overflow-hidden p-4 sm:p-6"><div className="relative flex aspect-square max-h-[460px] items-center justify-center overflow-hidden rounded-3xl bg-black/60"><video ref={video} playsInline muted className={`h-full w-full object-cover ${mode==="camera"?"block":"hidden"}`}/>{mode!=="camera"&&<div className="text-center text-slate-600"><ScanLine className="mx-auto" size={88} strokeWidth={1}/><p className="mt-3 text-sm">{ar?"وجّه الكاميرا نحو QR":"Point the camera at the QR"}</p></div>}<div className="scan-frame pointer-events-none absolute inset-[14%] rounded-[2rem] border border-brand-400/70"><span className="scan-beam absolute start-[6%] top-1/2 h-px w-[88%] bg-brand-400 shadow-[0_0_14px_#53e0b3]"/></div>{mode==="camera"&&<div className="absolute bottom-4 flex gap-2"><button type="button" onClick={toggleTorch} className="rounded-full bg-black/60 p-3" aria-label={ar?"الفلاش":"Flash"}><Zap size={19}/></button><button type="button" onClick={switchCamera} className="rounded-full bg-black/60 p-3" aria-label={ar?"تبديل الكاميرا":"Switch camera"}><RefreshCw size={19}/></button></div>}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><button type="button" onClick={()=>camera()} className="btn-primary"><Camera size={17}/>{ar?"تشغيل الكاميرا":"Open camera"}</button><label className="btn-secondary cursor-pointer"><ImageIcon size={17}/>{ar?"اختيار صورة":"Choose image"}<input className="hidden" type="file" accept="image/*" onChange={event=>image(event.target.files?.[0])}/></label><button type="button" onClick={()=>{stop();setMode("manual")}} className="btn-secondary"><Keyboard size={17}/>{ar?"إدخال يدوي":"Manual code"}</button></div>{mode==="manual"&&<form className="mt-4 flex gap-2" onSubmit={event=>{event.preventDefault();submit(manual)}}><input className="input font-mono" dir="ltr" value={manual} onChange={event=>setManual(event.target.value)} autoComplete="off" placeholder="Activation code or URL" required/><button className="btn-primary">{ar?"تحقق":"Verify"}</button></form>}{status&&<p role="status" className="mt-4 rounded-xl border border-amber-400/10 bg-amber-400/10 p-3 text-sm text-amber-100">{status}</p>}</div>;
}
