"use client";

import { useMemo, useState } from "react";
import { Bell, Plus, Send, X } from "lucide-react";
import { ConfirmSubmit } from "@/components/confirm-submit";

type UserOption = { id: string; name: string | null; email: string; locale: string | null };
type Estimates = Record<"ALL_ACTIVE"|"LOCALE_EN"|"LOCALE_AR"|"LOCALE_FR"|"PUBLISHED_PROFILE",number>;

export function AdminNotificationComposer({ action, users, locale, estimates }: { action: (data: FormData) => Promise<void>; users: UserOption[]; locale: "ar"|"en"; estimates: Estimates }) {
  const ar=locale==="ar",[open,setOpen]=useState(false),[audience,setAudience]=useState("TEST"),[audienceValue,setAudienceValue]=useState("self"),[query,setQuery]=useState(""),[selected,setSelected]=useState<string[]>([]),[title,setTitle]=useState(""),[body,setBody]=useState(""),[deepLink,setDeepLink]=useState("");
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return users.filter(user=>!term||user.email.toLowerCase().includes(term)||user.name?.toLowerCase().includes(term)).slice(0,60)},[query,users]);
  const estimate=audience==="TEST"||audience==="USER"?1:audience==="SELECTED"?selected.length:estimates[audienceValue as keyof Estimates]||0;
  const chooseAudience=(next:string)=>{setAudience(next);setSelected([]);setAudienceValue(next==="TEST"?"self":next==="SEGMENT"?"ALL_ACTIVE":"")};
  const copy=ar?{add:"إنشاء إشعار",close:"إغلاق",title:"إشعار جديد",audience:"الجمهور",test:"اختبار — حسابي",one:"مستخدم واحد",selected:"مستخدمون محددون",segment:"شريحة",recipient:"المستلم",select:"اختر مستخدمًا",all:"كل الحسابات النشطة",en:"اللغة الإنجليزية",arabic:"اللغة العربية",french:"اللغة الفرنسية",published:"لديه ملف منشور",estimated:"المستلمون المتوقعون",search:"ابحث عن مستخدمين",fallback:"لغة المحتوى الافتراضية",content:"المحتوى المحلي",category:"فئة التفضيلات",destination:"وجهة التطبيق",image:"رابط صورة HTTPS اختياري",preview:"معاينة داخل POP",draft:"حفظ كمسودة",send:"إرسال الآن",sendConfirm:"إرسال هذا الإشعار الآن إلى الجمهور المحدد؟",safe:"الإرسال يحترم تفضيلات المستخدم ورموز الأجهزة النشطة. قبول FCM لا يعني وصولًا أو قراءة."}:{add:"Create notification",close:"Close",title:"New notification",audience:"Audience",test:"Test — my account",one:"One user",selected:"Selected users",segment:"Segment",recipient:"Recipient",select:"Select user",all:"All active accounts",en:"English locale",arabic:"Arabic locale",french:"French locale",published:"Has a published profile",estimated:"Estimated recipients",search:"Search users",fallback:"Default content locale",content:"Localized content",category:"Preference category",destination:"App destination",image:"Optional HTTPS image URL",preview:"Preview inside POP",draft:"Save draft",send:"Send now",sendConfirm:"Send this notification now to the selected audience?",safe:"Sending respects user preferences and active device tokens. FCM acceptance does not mean device delivery or a read."};
  return <><button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>{copy.add}</button>{open&&<div className="fixed inset-0 z-50 grid items-end bg-slate-950/75 backdrop-blur-sm sm:place-items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="notification-compose-title" onMouseDown={event=>{if(event.currentTarget===event.target)setOpen(false)}}><div className="max-h-[96dvh] w-full overflow-y-auto rounded-t-3xl border border-white/10 bg-[color:var(--app-surface)] p-5 shadow-2xl sm:max-w-5xl sm:rounded-3xl sm:p-7"><header className="mb-6 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-500/15 text-brand-300"><Bell size={22}/></span><div><p className="admin-eyebrow">Notifications</p><h2 id="notification-compose-title" className="text-xl">{copy.title}</h2></div></div><button className="btn-secondary px-3" onClick={()=>setOpen(false)} aria-label={copy.close}><X size={18}/></button></header>
    <form action={async data=>{await action(data);setOpen(false)}} className="grid gap-5"><section className="admin-section-card"><h3 className="mb-4 font-bold">{copy.audience}</h3><div className="grid gap-4 lg:grid-cols-3"><label><span className="label">{copy.audience}</span><select className="input" name="audienceType" value={audience} onChange={event=>chooseAudience(event.target.value)}><option value="TEST">{copy.test}</option><option value="USER">{copy.one}</option><option value="SELECTED">{copy.selected}</option><option value="SEGMENT">{copy.segment}</option></select></label>{audience==="USER"&&<label className="lg:col-span-2"><span className="label">{copy.recipient}</span><select className="input" name="audienceValue" required value={audienceValue} onChange={event=>setAudienceValue(event.target.value)}><option value="">{copy.select}</option>{users.map(user=><option value={user.id} key={user.id}>{user.name||"Unnamed"} · {user.email}</option>)}</select></label>}{audience==="SEGMENT"&&<label className="lg:col-span-2"><span className="label">{copy.segment}</span><select className="input" name="audienceValue" value={audienceValue} onChange={event=>setAudienceValue(event.target.value)}><option value="ALL_ACTIVE">{copy.all}</option><option value="LOCALE_EN">{copy.en}</option><option value="LOCALE_AR">{copy.arabic}</option><option value="PUBLISHED_PROFILE">{copy.published}</option></select></label>}{audience==="TEST"&&<input type="hidden" name="audienceValue" value="self"/>}{audience==="SELECTED"&&<div className="lg:col-span-2"><input type="hidden" name="audienceValue" value={selected.join(",")}/><span className="label">{copy.selected} ({selected.length})</span><input className="input" value={query} onChange={event=>setQuery(event.target.value)} placeholder={copy.search}/><div className="mt-2 max-h-44 overflow-y-auto rounded-xl border border-white/10 p-2">{visible.map(user=><label className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-white/5" key={user.id}><input type="checkbox" checked={selected.includes(user.id)} onChange={event=>setSelected(value=>event.target.checked?[...value,user.id]:value.filter(id=>id!==user.id))}/><span className="min-w-0 truncate"><b>{user.name||"Unnamed"}</b><small className="ms-2 text-slate-500" dir="ltr">{user.email} · {user.locale||"system"}</small></span></label>)}</div></div>}</div><div className="mt-4 rounded-xl bg-brand-500/10 p-3 text-sm text-brand-200"><strong>{copy.estimated}: {Math.min(estimate,500).toLocaleString(locale)}</strong><span className="ms-2 text-xs opacity-70">{estimate>500?"(send cap: 500)":""}</span></div></section>
      <section className="admin-section-card"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">{copy.content}</h3><label className="flex items-center gap-2 text-xs"><span>{copy.fallback}</span><select className="input py-2" name="defaultLocale" defaultValue="en"><option value="en">English</option><option value="ar">العربية</option><option value="fr">Français</option></select></label></div><div className="grid gap-3 lg:grid-cols-3"><fieldset className="grid gap-3 rounded-xl border border-white/10 p-4"><legend className="px-2 font-bold">English *</legend><input className="input" name="titleEn" maxLength={120} required placeholder="Title" onChange={event=>setTitle(event.target.value)}/><textarea className="input min-h-24" name="bodyEn" maxLength={500} required placeholder="Body" onChange={event=>setBody(event.target.value)}/></fieldset><fieldset className="grid gap-3 rounded-xl border border-white/10 p-4" dir="rtl"><legend className="px-2 font-bold">العربية</legend><input className="input" name="titleAr" maxLength={120} placeholder="العنوان"/><textarea className="input min-h-24" name="bodyAr" maxLength={500} placeholder="النص"/></fieldset><fieldset className="grid gap-3 rounded-xl border border-white/10 p-4"><legend className="px-2 font-bold">Français</legend><input className="input" name="titleFr" maxLength={120} placeholder="Titre"/><textarea className="input min-h-24" name="bodyFr" maxLength={500} placeholder="Message"/></fieldset></div><div className="mt-4 grid gap-3 md:grid-cols-3"><label><span className="label">{copy.category}</span><select className="input" name="category"><option>GENERAL</option><option>PRODUCTS</option><option>SECURITY</option><option>MARKETING</option></select></label><label><span className="label">{copy.destination}</span><input className="input" name="deepLink" placeholder="home, my-profile, menu" maxLength={180} onChange={event=>setDeepLink(event.target.value)} dir="ltr"/></label><label><span className="label">{copy.image}</span><input className="input" name="imageUrl" type="url" placeholder="https://…" dir="ltr"/></label></div></section>
      <section className="grid gap-4 lg:grid-cols-[1fr_22rem]"><p className="text-xs text-slate-500">{copy.safe}</p><div><p className="label">{copy.preview}</p><div className="rounded-2xl border border-white/10 bg-slate-900 p-4 shadow-xl"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-400 font-black text-slate-950">POP</span><div className="min-w-0"><strong className="block truncate">{title||"POP by POPWAM"}</strong><p className="mt-1 line-clamp-2 text-xs text-slate-400">{body||"Notification preview"}</p>{deepLink&&<p className="mt-2 truncate text-[10px] text-brand-300" dir="ltr">{deepLink}</p>}</div></div></div></div></section>
      <footer className="sticky bottom-0 -mx-5 -mb-5 flex justify-end gap-2 border-t border-white/10 bg-[color:var(--app-surface)] px-5 py-4 sm:-mx-7 sm:-mb-7 sm:px-7"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>{copy.close}</button><button className="btn-secondary" name="operation" value="draft">{copy.draft}</button><ConfirmSubmit className="btn-primary" name="operation" value="send" message={copy.sendConfirm}><Send size={15}/>{copy.send}</ConfirmSubmit></footer></form></div></div>}</>;
}
