"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Crop, Upload } from "lucide-react";

type Asset = { key:string; title:string; description:string; dimensions:string; url:string; square?:boolean };
async function squareWebp(file:File){const image=await createImageBitmap(file);const size=Math.min(image.width,image.height);const canvas=document.createElement("canvas");canvas.width=1024;canvas.height=1024;const context=canvas.getContext("2d")!;context.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,1024,1024);image.close();return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("CROP_FAILED")),"image/webp",.9));}
export function BrandingManager({assets}:{assets:Asset[]}){const router=useRouter();const [status,setStatus]=useState<Record<string,string>>({});const refs=useRef<Record<string,HTMLInputElement|null>>({});async function upload(asset:Asset,file?:File){if(!file)return;setStatus(v=>({...v,[asset.key]:"جاري الرفع… / Uploading…"}));try{const blob=asset.square?await squareWebp(file):file;const body=new FormData();body.set("asset",asset.key);body.set("file",new File([blob],asset.square?`${asset.key}.webp`:file.name,{type:blob.type||file.type}));const response=await fetch("/api/upload/branding",{method:"POST",body});const result=await response.json();if(!response.ok)throw new Error(result.error||"UPLOAD_FAILED");setStatus(v=>({...v,[asset.key]:"تم الحفظ / Saved"}));router.refresh();}catch(error){setStatus(v=>({...v,[asset.key]:error instanceof Error?error.message:"UPLOAD_FAILED"}));}}
return <div className="grid gap-4 lg:grid-cols-2">{assets.map(asset=><article className="card p-5" key={asset.key}><div className="flex gap-4"><div className="flex size-24 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-white/5 p-2"><img src={asset.url} alt="" className="max-h-full max-w-full object-contain"/></div><div className="min-w-0"><h2 className="font-bold">{asset.title}</h2><p className="mt-1 text-xs text-slate-400">{asset.description}</p><p className="mt-2 text-xs font-semibold text-brand-400">{asset.dimensions}</p></div></div><input ref={node=>{refs.current[asset.key]=node}} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={event=>upload(asset,event.target.files?.[0])}/><button type="button" className="btn-secondary mt-4" onClick={()=>refs.current[asset.key]?.click()}>{asset.square?<Crop size={15}/>:<Upload size={15}/>} {asset.square?"قص ورفع / Crop & upload":"استبدال / Replace"}</button>{status[asset.key]&&<p className="mt-2 text-xs text-amber-300">{status[asset.key]}</p>}</article>)}</div>}
