"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";
import { Building2, CreditCard, FileText, Gauge, Layers3, Link2, LogOut, MessageSquareText, Nfc, Package, Palette, Receipt, ScrollText, Settings, Shield, ShoppingCart, SlidersHorizontal, Truck, Upload, UserRound, Users, WalletCards } from "lucide-react";
import { LocaleSwitcher } from "@/components/locale-switcher";
import { ProfileAvatar } from "@/components/profile-avatar";

type NavCopy = { overview:string; profile:string; destinations:string; tags:string; uploads:string; admin:string; signOut:string; users:string; organizations:string; plans:string; limits:string; profiles:string; links:string; themes:string; settings:string; audit:string;home:string;myProfiles:string;imageEditor:string;myLinks:string;myFiles:string;myCards:string;appearance:string;cardsBatches:string;inventory:string;suppliers:string;purchases:string;expenses:string;customers:string;orders:string;branding:string;sms:string;userDashboard:string };
export function DashboardShell({ children,user,locale,labels,languageLabel }: { children:React.ReactNode; user:{ name?:string|null;email?:string|null;image?:string|null;role:string };locale:"ar"|"en";labels:NavCopy;languageLabel:string }) {
  const pathname=usePathname(); const admin=pathname.startsWith("/admin"); const canAdmin=user.role==="ADMIN"||user.role==="SUPER_ADMIN";
  const userLinks=[["/dashboard",labels.home,Gauge],["/dashboard/profiles",labels.myProfiles,Users],["/dashboard/profile",labels.imageEditor,UserRound],["/dashboard/cards",labels.myLinks,CreditCard],["/dashboard/uploads",labels.myFiles,Upload],["/dashboard/tags",labels.myCards,Nfc],["/dashboard/appearance",labels.appearance,Palette],["/dashboard/settings",labels.settings,Settings]] as const;
  const adminLinks=[["/admin",labels.overview,Gauge],["/admin/users",labels.users,Users],["/admin/cards",labels.cardsBatches,Nfc],["/admin/inventory",labels.inventory,Package],["/admin/suppliers",labels.suppliers,Truck],["/admin/purchases",labels.purchases,ShoppingCart],["/admin/expenses",labels.expenses,Receipt],["/admin/customers",labels.customers,Users],["/admin/orders",labels.orders,WalletCards],["/admin/links",labels.links,Link2],["/admin/uploads",labels.uploads,FileText],["/admin/plans",labels.plans,Layers3],["/admin/themes",labels.themes,Palette],["/admin/branding",labels.branding,Building2],["/admin/limits",labels.limits,SlidersHorizontal],["/admin/settings",labels.settings,Settings],["/admin/audit",labels.audit,ScrollText]] as const;
  const links=admin?[...adminLinks,["/admin/sms",labels.sms,MessageSquareText] as const]:userLinks;
  const logoutUrl=admin?"/admin/login":"/login";
  return <div className="mx-auto min-h-screen max-w-[1600px] lg:grid lg:grid-cols-[270px_1fr]"><aside className="border-b border-white/10 bg-black/20 p-4 lg:sticky lg:top-0 lg:h-screen lg:overflow-y-auto lg:border-b-0 lg:border-e lg:p-6"><div className="flex items-center justify-between"><Link href="/" className="text-lg font-black"><span className="text-brand-400">POPWAM</span> Tap</Link><button onClick={()=>signOut({callbackUrl:logoutUrl})} className="text-slate-500 lg:hidden" aria-label={labels.signOut}><LogOut size={19}/></button></div><nav className="mt-5 flex gap-2 overflow-x-auto lg:mt-8 lg:block lg:space-y-1">{links.map(([href,label,Icon])=>{const active=href===(admin?"/admin":"/dashboard")?pathname===href:pathname.startsWith(href);return <Link key={href} href={href} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active?"bg-brand-500/10 text-brand-400":"text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon size={17}/>{label}</Link>;})}{!admin&&user.role==="ADMIN"&&<Link href="/admin" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-400 hover:bg-white/5 hover:text-white"><Shield size={17}/>{labels.admin}</Link>}{admin&&<Link href="/dashboard" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-400 hover:bg-white/5 hover:text-white"><Gauge size={17}/>{locale==="ar"?"لوحة المستخدم":"User dashboard"}</Link>}</nav><div className="mt-8 hidden border-t border-white/10 pt-5 lg:block"><div className="flex items-center gap-3"><ProfileAvatar name={user.name} email={user.email} imageUrl={user.image} size={40}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{user.name||"POPWAM"}</p><p className="truncate text-xs text-slate-500" dir="ltr">{user.email}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><LocaleSwitcher locale={locale} label={languageLabel}/><button onClick={()=>signOut({callbackUrl:logoutUrl})} className="btn-secondary"><LogOut size={14}/>{labels.signOut}</button></div></div></aside><main className="min-w-0 p-4 sm:p-7 lg:p-10">{children}</main></div>;
}
