"use client";

import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown,ArrowUp,Eye,EyeOff,FileText,Trash2,Upload } from "lucide-react";
import { moveUploadedFile,toggleUploadedFileVisibility } from "@/app/actions";
type Item={id:string;title:string|null;originalFilename:string;publicUrl:string;sizeBytes:string;isVisible:boolean;sortOrder:number};
export function FileManager({profileId,initialFiles,allowed,usageLabel}:{profileId:string;initialFiles:Item[];allowed:boolean;usageLabel:string}){const [status,setStatus]=useState("");const [pending,setPending]=useState(false);const form=useRef<HTMLFormElement>(null);const router=useRouter();async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!form.current)return;setPending(true);setStatus("");const response=await fetch("/api/upload/file",{method:"POST",body:new FormData(form.current)});const result=await response.json();setPending(false);if(!response.ok)setStatus(result.error||"UPLOAD_FAILED");else{form.current.reset();setStatus("Uploaded");router.refresh();}}async function remove(id:string){if(!window.confirm("Delete this uploaded file?"))return;const response=await fetch(`/api/upload/file?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok)router.refresh();else setStatus("DELETE_FAILED");}
return <><div className="mb-5 flex items-center justify-between"><p className="text-sm text-slate-400">{usageLabel}</p></div>{allowed?<form ref={form} onSubmit={upload} className="card mb-5 grid gap-4 p-5 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="profileId" value={profileId}/><label><span className="label">Public title</span><input className="input" name="title"/></label><label><span className="label">File</span><input className="input" type="file" name="file" required accept=".pdf,.vcf,.txt,.jpg,.jpeg,.png,.webp"/></label><button className="btn-primary self-end" disabled={pending}><Upload size={15}/>Upload</button>{status&&<p className="text-sm text-amber-300 sm:col-span-3">{status}</p>}</form>:<div className="card mb-5 p-5 text-amber-200">File uploads are not enabled by your current plan.</div>}<div className="grid gap-3">{initialFiles.map(file=><article className={`card flex items-center gap-4 p-4 ${file.isVisible?"":"opacity-60"}`} key={file.id}><FileText className="text-brand-400"/><div className="min-w-0 flex-1"><a href={file.publicUrl} target="_blank" className="font-semibold">{file.title||file.originalFilename}</a><p className="text-xs text-slate-500">{Math.ceil(Number(file.sizeBytes)/1024)} KB · {file.isVisible?"Visible":"Hidden"}</p></div><div className="flex flex-wrap gap-1"><form action={toggleUploadedFileVisibility}><input type="hidden" name="id" value={file.id}/><button className="btn-secondary" title={file.isVisible?"Hide":"Show"}>{file.isVisible?<Eye size={14}/>:<EyeOff size={14}/>}</button></form><form action={moveUploadedFile}><input type="hidden" name="id" value={file.id}/><input type="hidden" name="direction" value="up"/><button className="btn-secondary"><ArrowUp size={14}/></button></form><form action={moveUploadedFile}><input type="hidden" name="id" value={file.id}/><input type="hidden" name="direction" value="down"/><button className="btn-secondary"><ArrowDown size={14}/></button></form><button className="btn-danger" onClick={()=>remove(file.id)}><Trash2 size={14}/></button></div></article>)}</div></>;
}
