"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { signIn } from "next-auth/react";
import { getCountries, getCountryCallingCode, type CountryCode } from "libphonenumber-js/min";
import { FlaskConical, MessageCircle, Phone, ShieldCheck } from "lucide-react";

const flag=(country:string)=>country.replace(/./g,char=>String.fromCodePoint(127397+char.charCodeAt(0)));
export function OtpForm({ purpose, locale, initialPhone = "", callbackUrl = "/dashboard" }: { purpose:"LOGIN"|"ACTIVATION";locale:"ar"|"en";initialPhone?:string;callbackUrl?:string }) {
  const ar=locale==="ar";const [phone,setPhone]=useState(initialPhone);const [country,setCountry]=useState<CountryCode>("EG");const [channel,setChannel]=useState<"sms"|"whatsapp">("sms");const [channels,setChannels]=useState<Array<"sms"|"whatsapp">>(["sms"]);const [digits,setDigits]=useState(["","","","",""]);const [sent,setSent]=useState(false);const [pending,setPending]=useState(false);const [message,setMessage]=useState("");const [testOtp,setTestOtp]=useState("");const [countdown,setCountdown]=useState(0);const inputs=useRef<Array<HTMLInputElement|null>>([]);
  const channelLabels={whatsapp:ar?"واتساب":"WhatsApp",sms:ar?"رسالة نصية":"SMS"};
  const countryNames=useMemo(()=>new Intl.DisplayNames([locale],{type:"region"}),[locale]);
  const countries=useMemo(()=>getCountries().map(code=>({code,name:countryNames.of(code)||code,calling:`+${getCountryCallingCode(code)}`})).sort((a,b)=>a.name.localeCompare(b.name,locale)),[countryNames,locale]);
  useEffect(()=>{const saved=localStorage.getItem("pop.phoneCountry") as CountryCode|null;const region=navigator.language.split("-")[1]?.toUpperCase() as CountryCode|undefined;const suggested=saved&&getCountries().includes(saved)?saved:region&&getCountries().includes(region)?region:"EG";setCountry(suggested)},[]);
  useEffect(()=>{localStorage.setItem("pop.phoneCountry",country);fetch(`/api/otp/channels?countryIso2=${country}`,{cache:"no-store"}).then(r=>r.json()).then(value=>{const available=Array.isArray(value.channels)?value.channels.filter((item:unknown)=>item==="sms"||item==="whatsapp"):[];setChannels(available);if(available.length&&!available.includes(channel))setChannel(available[0])}).catch(()=>setChannels([]))},[country,channel]);
  useEffect(()=>{if(countdown<=0)return;const timer=window.setInterval(()=>setCountdown(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[countdown]);
  async function send(){setPending(true);setMessage("");setTestOtp("");const response=await fetch("/api/otp/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,countryIso2:country,channel,purpose,locale})});const result=await response.json().catch(()=>({}));setPending(false);if(response.ok){setSent(true);setDigits(["","","","",""]);setCountdown(result.resendAfter||60);setMessage(`${ar?"أُرسل الرمز إلى":"Code sent to"} ${result.maskedPhone}`);if(result.testingOnly===true&&typeof result.testOtp==="string")setTestOtp(result.testOtp);setTimeout(()=>inputs.current[0]?.focus(),50);return}const errors:Record<string,string>={PHONE_INVALID:ar?"أدخل رقم هاتف صالحًا للدولة المحددة.":"Enter a valid phone for the selected country.",COUNTRY_INVALID:ar?"اختر دولة صالحة.":"Select a valid country.",OTP_COOLDOWN:ar?"انتظر قبل إعادة الإرسال.":"Wait before resending.",OTP_LIMIT_REACHED:ar?"تم بلوغ حد الإرسال.":"The hourly limit was reached.",OTP_SEND_FAILED:ar?"قناة الإرسال غير متاحة لهذا الرقم الآن.":"This delivery channel is not available for that number."};setMessage(errors[result.error]||(ar?"تعذر إرسال الرمز.":"The code could not be sent."))}
  function paste(value:string){const numeric=value.replace(/\D/g,"").slice(0,6);setDigits(Array.from({length:6},(_,i)=>numeric[i]||""));inputs.current[Math.min(numeric.length,5)]?.focus()}
  async function verify(event:React.FormEvent){event.preventDefault();const code=digits.join("");if(code.length!==6)return;setPending(true);const response=await fetch("/api/otp/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const result=await response.json().catch(()=>({}));if(!response.ok){setPending(false);setMessage(ar?"الرمز غير صحيح أو منتهي أو مستخدم.":"The code is invalid, expired, or already used.");return}const login=await signIn("phone-otp",{ticket:result.ticket,redirect:false});if(login?.error){setPending(false);setMessage(ar?"تعذر تسجيل الدخول.":"Sign-in failed.");return}const safe=callbackUrl.startsWith("/")&&!callbackUrl.startsWith("//")?callbackUrl:"/dashboard";window.location.assign(purpose==="ACTIVATION"?result.nextUrl||"/dashboard":result.passkeyRecommended?`/onboarding/passkey?next=${encodeURIComponent(safe)}`:safe)}
  return <form onSubmit={verify} className="space-y-5">
    <label><span className="label">{ar?"الدولة ورقم الهاتف":"Country and phone number"}</span><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]" dir="ltr"><select className="input" aria-label={ar?"الدولة":"Country"} value={country} onChange={e=>setCountry(e.target.value as CountryCode)} disabled={sent}>{countries.map(item=><option key={item.code} value={item.code}>{flag(item.code)} {item.name} {item.calling}</option>)}</select><div className="relative"><Phone className="absolute left-3 top-3 text-slate-500" size={18}/><input className="input pl-10" dir="ltr" inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder={country==="EG"?"1001234567":"Phone number"} disabled={sent} required/></div></div></label>
    {!sent&&channels.length>1&&<div className="grid grid-cols-2 gap-2" dir="ltr"><button type="button" className={channel==="whatsapp"?"btn-primary":"btn-secondary"} onClick={()=>setChannel("whatsapp")}><MessageCircle size={16}/>{channelLabels.whatsapp}</button><button type="button" className={channel==="sms"?"btn-primary":"btn-secondary"} onClick={()=>setChannel("sms")}><Phone size={16}/>{channelLabels.sms}</button></div>}
    {!sent?<button type="button" onClick={send} disabled={pending||channels.length===0} className="btn-primary w-full py-3">{pending?(ar?"جارٍ الإرسال…":"Sending…"):(ar?"إرسال رمز التحقق":"Send verification code")}</button>:<><div><span className="label">{ar?"رمز التحقق":"Verification code"}</span><div className="grid grid-cols-6 gap-2" dir="ltr" onPaste={e=>{e.preventDefault();paste(e.clipboardData.getData("text"))}}>{digits.map((digit,index)=><input key={index} ref={el=>{inputs.current[index]=el}} className="min-w-0 rounded-xl border border-white/10 bg-black/30 px-0 py-3 text-center font-mono text-xl outline-none focus:border-brand-400" inputMode="numeric" autoComplete={index===0?"one-time-code":"off"} value={digit} onChange={e=>{const value=e.target.value.replace(/\D/g,"");if(value.length>1)return paste(value);setDigits(current=>current.map((d,i)=>i===index?value:d));if(value&&index<5)inputs.current[index+1]?.focus()}}/>)}</div></div>{testOtp&&<div className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-4 text-amber-100"><p className="flex items-center gap-2 text-xs font-black"><FlaskConical size={16}/>{ar?"للاختبار فقط":"Testing only"}</p><p className="mt-2 text-center font-mono text-2xl font-black tracking-[.35em]" dir="ltr">{testOtp}</p></div>}<button className="btn-primary w-full py-3" disabled={pending||digits.join("").length!==6}><ShieldCheck size={17}/>{ar?"تحقق وتابع":"Verify and continue"}</button><div className="flex justify-between text-sm"><button type="button" onClick={()=>setSent(false)}>{ar?"تغيير الرقم":"Change number"}</button><button type="button" disabled={countdown>0||pending} onClick={send} className="text-brand-400 disabled:text-slate-600">{countdown>0?`${countdown}s`:(ar?"إعادة الإرسال":"Resend")}</button></div></>}
    {message&&<p role="status" className="rounded-xl bg-white/5 p-3 text-sm">{message}</p>}<p className="text-center text-xs leading-6 text-slate-500">{ar?"يُحفظ الرقم بصيغة E.164 ويستخدم كهوية الحساب الأساسية.":"Your number is stored in canonical E.164 form as the primary account identity."}</p>
  </form>;
}
