"use client";
import { useEffect, useRef, useState } from "react";
import { signIn } from "next-auth/react";
import { Phone, ShieldCheck } from "lucide-react";

export function OtpForm({ purpose, locale, initialPhone = "", callbackUrl = "/dashboard" }: { purpose:"LOGIN"|"ACTIVATION"; locale:"ar"|"en"; initialPhone?:string; callbackUrl?:string }) {
  const ar = locale === "ar"; const [phone,setPhone] = useState(initialPhone); const [digits,setDigits] = useState(["","","","","",""]); const [sent,setSent] = useState(false); const [pending,setPending] = useState(false); const [message,setMessage] = useState(""); const [countdown,setCountdown] = useState(0); const inputs = useRef<Array<HTMLInputElement|null>>([]);
  useEffect(()=>{ if(countdown<=0)return; const timer=window.setInterval(()=>setCountdown(value=>Math.max(0,value-1)),1000); return()=>window.clearInterval(timer); },[countdown]);
  async function send() { setPending(true); setMessage(""); const response=await fetch("/api/otp/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,purpose,locale})}); const result=await response.json().catch(()=>({})); setPending(false); if(response.ok){setSent(true);setDigits(["","","","","",""]);setCountdown(result.resendAfter||60);setMessage(`${ar?"أُرسل الرمز إلى":"Code sent to"} ${result.maskedPhone}${result.developmentCode?` · DEV ${result.developmentCode}`:""}`);setTimeout(()=>inputs.current[0]?.focus(),50);}else{const errors:Record<string,string>=ar?{PHONE_INVALID:"أدخل رقم هاتف صحيحًا.",OTP_COOLDOWN:"انتظر قبل إعادة الإرسال.",OTP_LIMIT_REACHED:"تم بلوغ حد 5 رسائل خلال ساعة.",OTP_SEND_FAILED:"تعذر إرسال الرمز الآن. حاول لاحقًا."}:{PHONE_INVALID:"Enter a valid phone number.",OTP_COOLDOWN:"Wait before resending.",OTP_LIMIT_REACHED:"The limit of 5 codes per hour was reached.",OTP_SEND_FAILED:"The code could not be sent. Try later."};setMessage(errors[result.error]||(ar?"تعذر إرسال الرمز الآن.":"The code could not be sent."));} }
  function setDigit(index:number,value:string){const numeric=value.replace(/\D/g,""); if(numeric.length>1){paste(numeric);return;} setDigits(current=>current.map((digit,i)=>i===index?numeric:digit));if(numeric&&index<5)inputs.current[index+1]?.focus();}
  function paste(value:string){const numeric=value.replace(/\D/g,"").slice(0,6);if(!numeric)return;setDigits(Array.from({length:6},(_,index)=>numeric[index]||""));inputs.current[Math.min(numeric.length,5)]?.focus();}
  async function verify(event:React.FormEvent){event.preventDefault();const code=digits.join("");if(code.length!==6)return;setPending(true);setMessage("");const response=await fetch("/api/otp/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const result=await response.json().catch(()=>({}));if(!response.ok){setPending(false);setMessage(ar?"الرمز غير صحيح أو منتهي أو استُخدم من قبل.":"The code is invalid, expired, or already used.");return;}const login=await signIn("phone-otp",{ticket:result.ticket,redirect:false});if(login?.error){setPending(false);setMessage(ar?"تعذر تسجيل الدخول. أعد المحاولة.":"Sign-in failed. Try again.");return;}const safeCallback=callbackUrl.startsWith("/")&&!callbackUrl.startsWith("//")?callbackUrl:"/dashboard";window.location.assign(purpose==="ACTIVATION"?result.nextUrl||"/dashboard":safeCallback);}
  return <form onSubmit={verify} className="space-y-5"><label><span className="label">{ar?"رقم الهاتف":"Phone number"}</span><div className="flex gap-2" dir="ltr"><select className="input w-24" aria-label={ar?"كود الدولة":"Country code"} disabled={sent}><option value="+20">🇪🇬 +20</option></select><div className="relative flex-1"><Phone className="absolute left-3 top-3 text-slate-500" size={18}/><input className="input pl-10" dir="ltr" inputMode="tel" autoComplete="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="01012345678" disabled={sent} required/></div></div></label>{!sent?<button type="button" onClick={send} disabled={pending} className="btn-primary w-full py-3">{pending?(ar?"جارٍ الإرسال…":"Sending…"):(ar?"إرسال رمز التحقق":"Send verification code")}</button>:<><div><span className="label">{ar?"رمز التحقق":"Verification code"}</span><div className="grid grid-cols-6 gap-2" dir="ltr" onPaste={event=>{event.preventDefault();paste(event.clipboardData.getData("text"))}}>{digits.map((digit,index)=><input key={index} ref={element=>{inputs.current[index]=element}} className="min-w-0 rounded-xl border border-white/10 bg-black/30 px-0 py-3 text-center font-mono text-xl outline-none focus:border-brand-400" inputMode="numeric" autoComplete={index===0?"one-time-code":"off"} value={digit} onChange={event=>setDigit(index,event.target.value)} onKeyDown={event=>{if(event.key==="Backspace"&&!digits[index]&&index>0)inputs.current[index-1]?.focus()}} aria-label={`${ar?"الرقم":"Digit"} ${index+1}`}/>)}</div></div><button className="btn-primary w-full py-3" disabled={pending||digits.join("").length!==6}><ShieldCheck size={17}/>{pending?(ar?"جارٍ التحقق…":"Verifying…"):(ar?"تحقق وتابع":"Verify and continue")}</button><div className="flex items-center justify-between text-sm"><button type="button" className="text-slate-400 hover:text-white" onClick={()=>{setSent(false);setMessage("");setCountdown(0)}}>{ar?"تغيير الرقم":"Change number"}</button><button type="button" disabled={countdown>0||pending} onClick={send} className="text-brand-400 disabled:text-slate-600">{countdown>0?`${ar?"إعادة الإرسال بعد":"Resend in"} ${countdown}s`:(ar?"إعادة إرسال الرمز":"Resend code")}</button></div></>}{message&&<p role="status" className="rounded-xl bg-white/5 p-3 text-sm text-slate-200">{message}</p>}<p className="text-center text-xs leading-6 text-slate-500">{ar?"الرمز صالح لمدة 5 دقائق، ولمرة واحدة فقط. لن نكشف إن كان الرقم مسجلاً مسبقًا.":"The code is valid for 5 minutes and one use. We never reveal whether a phone is already registered."}</p></form>;
}
