"use client";
import {startAuthentication,startRegistration} from "@simplewebauthn/browser";
import {signIn} from "next-auth/react";
import {useState} from "react";
import {KeyRound,Trash2} from "lucide-react";

export function PasskeyLogin({locale,callbackUrl="/dashboard"}:{locale:"ar"|"en";callbackUrl?:string}){const [pending,setPending]=useState(false);const [error,setError]=useState("");async function login(){setPending(true);setError("");try{const options=await fetch("/api/passkeys/authenticate/options",{method:"POST"}).then(r=>r.json());const response=await startAuthentication({optionsJSON:options});const verified=await fetch("/api/passkeys/authenticate/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(response)}).then(r=>r.json());if(!verified.ticket)throw new Error();const result=await signIn("phone-otp",{ticket:verified.ticket,redirect:false});if(result?.error)throw new Error();window.location.assign(callbackUrl.startsWith("/")&&!callbackUrl.startsWith("//")?callbackUrl:"/dashboard")}catch{setPending(false);setError(locale==="ar"?"تعذر استخدام مفتاح المرور. استخدم رقم الهاتف بدلًا منه.":"Passkey sign-in was unavailable. Use your phone instead.")}}return <div className="mb-5"><button type="button" onClick={login} disabled={pending} className="btn-secondary w-full py-3"><KeyRound size={18}/>{pending?(locale==="ar"?"جارٍ التحقق…":"Checking…"):(locale==="ar"?"جرّب مفتاح المرور":"Try a passkey")}</button>{error&&<p className="mt-2 text-xs text-amber-300">{error}</p>}<div className="my-4 flex items-center gap-3 text-xs text-slate-600"><span className="h-px flex-1 bg-white/10"/>{locale==="ar"?"أو استخدم رقم الهاتف":"or use your phone"}<span className="h-px flex-1 bg-white/10"/></div></div>}

export type PasskeyItem={id:string;name:string|null;deviceType:string|null;backedUp:boolean;createdAt:string;lastUsedAt:string|null};
export function PasskeyManager({initial,locale}:{initial:PasskeyItem[];locale:"ar"|"en"}){const [items,setItems]=useState(initial);const [message,setMessage]=useState("");async function add(){setMessage("");try{const options=await fetch("/api/passkeys/register/options",{method:"POST"}).then(r=>r.json());const response=await startRegistration({optionsJSON:options});const result=await fetch("/api/passkeys/register/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(response)});if(!result.ok)throw new Error();window.location.reload()}catch{setMessage(locale==="ar"?"لم يُنشأ مفتاح المرور.":"The passkey was not created.")}}async function remove(id:string){if(!confirm(locale==="ar"?"إزالة مفتاح المرور؟":"Remove this passkey?"))return;const result=await fetch(`/api/passkeys/${id}`,{method:"DELETE"});if(result.ok)setItems(current=>current.filter(item=>item.id!==id))}return <div className="space-y-4"><button className="btn-primary" onClick={add}><KeyRound size={17}/>{locale==="ar"?"إنشاء مفتاح مرور":"Create passkey"}</button>{message&&<p className="text-sm text-amber-300">{message}</p>}<div className="grid gap-3">{items.map(item=><div key={item.id} className="card flex items-center justify-between p-4"><div><p className="font-semibold">{item.name||item.deviceType||(locale==="ar"?"مفتاح مرور":"Passkey")}</p><p className="mt-1 text-xs text-slate-500">{locale==="ar"?"أُضيف":"Added"} {new Date(item.createdAt).toLocaleDateString(locale)} · {item.lastUsedAt?(locale==="ar"?`آخر استخدام ${new Date(item.lastUsedAt).toLocaleDateString(locale)}`:`Last used ${new Date(item.lastUsedAt).toLocaleDateString(locale)}`):(locale==="ar"?"لم يُستخدم بعد":"Not used yet")}</p></div><button className="btn-secondary" onClick={()=>remove(item.id)}><Trash2 size={16}/></button></div>)}{!items.length&&<p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-400">{locale==="ar"?"لا توجد مفاتيح مرور بعد. يمكنك تخطي هذه الخطوة والاعتماد دائمًا على OTP.":"No passkeys yet. This is optional; phone OTP always remains available."}</p>}</div></div>}
