"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { Plan } from "@popwam/db";
import { BarChart3, Check, Database, Layers3, MessagesSquare, Palette, ShieldCheck, SlidersHorizontal, UserRound } from "lucide-react";
import { saveAdminPlan, type PlanActionState } from "@/app/actions";
import type { ProfileOpenPolicy } from "@/lib/plan-open-policy";

type SerializablePlan = Omit<Plan, "maxStorageBytes" | "createdAt" | "updatedAt"> & { maxStorageBytes: string };
const messages: Record<string, { ar: string; en: string }> = {
  PLAN_INVALID_TEXT: { ar: "الاسم والرمز المختصر والاختيارات مطلوبة.", en: "Localized names, slug, and valid catalog choices are required." },
  PLAN_INVALID_LIMIT: { ar: "يجب أن تكون الحدود أرقامًا صحيحة غير سالبة.", en: "Limits must be non-negative whole numbers." },
  PLAN_INVALID_OPEN_POLICY: { ar: "حد الفتحات يجب أن يكون غير محدود أو رقمًا موجبًا ضمن مدة صحيحة.", en: "Profile opens must be unlimited or a positive daily/monthly limit." },
  PLAN_FEATURE_CONFLICT: { ar: "راجع توافق أنواع الملفات وخيارات القوالب مع الميزات المفعلة.", en: "Profile types or theme choices conflict with the enabled features." },
  PLAN_INVALID_STOREFRONT: { ar: "راجع حد العرض وتوافق إعدادات واجهة المتجر مع ملفات الأعمال.", en: "Check the storefront limit and its compatibility with business profiles." },
  PLAN_SLUG_IN_USE: { ar: "رمز الباقة مستخدم بالفعل.", en: "This plan slug is already in use." },
  PLAN_SAVE_FAILED: { ar: "تعذر حفظ الباقة.", en: "The plan could not be saved." },
};
const profileTypes = ["PERSONAL", "PROFESSIONAL", "CREATOR", "BUSINESS"];
const themeTypes = ["CLASSIC_DARK", "CLASSIC_LIGHT", "ELEGANT_DARK", "ELEGANT_LIGHT", "BUSINESS_DARK", "BUSINESS_LIGHT"];

function Section({ title, note, icon: Icon, children }: { title: string; note?: string; icon: typeof UserRound; children: React.ReactNode }) {
  return <section className="admin-section-card"><header className="mb-5 flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-500/10 text-brand-300"><Icon size={19}/></span><div><h2>{title}</h2>{note&&<p className="mt-1 text-xs text-slate-500">{note}</p>}</div></header>{children}</section>;
}

function Toggle({ name, label, checked }: { name: string; label: string; checked?: boolean }) {
  return <label className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm"><span>{label}</span><input className="size-5 accent-brand-400" type="checkbox" name={name} defaultChecked={checked}/></label>;
}

export function PlanForm({ plan, locale, openPolicy }: { plan?: SerializablePlan; locale: "ar" | "en"; openPolicy: ProfileOpenPolicy }) {
  const ar = locale === "ar";
  const [state, action, pending] = useActionState(saveAdminPlan, { ok: false } as PlanActionState);
  const router = useRouter();
  const [openMode, setOpenMode] = useState(openPolicy.mode);
  const [storefrontLimitMode,setStorefrontLimitMode]=useState<"UNLIMITED"|"FIXED">(plan?.storefrontMaxItems==null?"UNLIMITED":"FIXED");
  const [profiles, setProfiles] = useState<string[]>(Array.isArray(plan?.availableProfileTypes) ? plan.availableProfileTypes.map(String) : ["PERSONAL"]);
  const [themes, setThemes] = useState<string[]>(Array.isArray(plan?.availableThemes) ? plan.availableThemes.map(String) : ["CLASSIC_DARK"]);
  useEffect(() => { if (state.ok) router.push("/admin/plans"); }, [state, router]);
  const number = (key: keyof SerializablePlan, fallback = 0) => String(plan?.[key] ?? fallback);
  const choose = (value: string, current: string[], update: (next: string[]) => void) => update(current.includes(value) ? current.filter(item => item !== value) : [...current, value]);
  return <form action={action} className="grid max-w-6xl gap-4">
    {plan&&<input type="hidden" name="id" value={plan.id}/>}<input type="hidden" name="availableProfileTypes" value={JSON.stringify(profiles)}/><input type="hidden" name="availableThemes" value={JSON.stringify(themes)}/>
    <Section title={ar?"هوية الباقة":"Identity"} icon={Layers3}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">English name</span><input className="input" name="nameEn" required maxLength={100} defaultValue={plan?.nameEn||plan?.name||""}/></label><label><span className="label">الاسم العربي</span><input className="input" name="nameAr" required maxLength={100} defaultValue={plan?.nameAr||""} dir="rtl"/></label><label><span className="label">Slug</span><input className="input" name="slug" required pattern="[a-z0-9-]{2,48}" defaultValue={plan?.slug||""} dir="ltr"/></label><label><span className="label">{ar?"ترتيب العرض":"Sort order"}</span><input className="input" type="number" min="0" name="sortOrder" required defaultValue={number("sortOrder")}/></label><label><span className="label">English description</span><textarea className="input min-h-24" name="descriptionEn" maxLength={500} defaultValue={plan?.descriptionEn||plan?.description||""}/></label><label><span className="label">الوصف العربي</span><textarea className="input min-h-24" name="descriptionAr" maxLength={500} defaultValue={plan?.descriptionAr||""} dir="rtl"/></label></div></Section>
    <Section title={ar?"الملفات وأنواع الحساب":"Profiles"} note={ar?"هذه حدود الباقة الافتراضية؛ تجاوزات المستخدم تبقى مستقلة.":"Plan defaults only; user-specific overrides remain separate."} icon={UserRound}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">{ar?"أقصى عدد للملفات":"Maximum profiles"}</span><input className="input" type="number" min="0" name="maxProfiles" required defaultValue={number("maxProfiles",1)}/></label><label><span className="label">{ar?"أقصى عدد للبطاقات الافتراضية":"Maximum virtual profiles"}</span><input className="input" type="number" min="0" name="maxVirtualCards" required defaultValue={number("maxVirtualCards",1)}/></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{profileTypes.map(value=><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-xs font-bold" key={value}><input type="checkbox" checked={profiles.includes(value)} onChange={()=>choose(value,profiles,setProfiles)}/>{value}</label>)}</div></Section>
    <Section title={ar?"المحتوى والوسائط":"Content, links and media"} icon={Database}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["maxLinks",ar?"الروابط الإضافية":"Extra links"],["maxCustomFields",ar?"الحقول المخصصة":"Custom fields"],["maxCards",ar?"الكروت والعلامات":"Physical cards / tags"],["maxFiles",ar?"الملفات المرفوعة":"Uploaded files"]].map(([key,label])=><label key={key}><span className="label">{label}</span><input className="input" type="number" min="0" name={key} required defaultValue={number(key as keyof SerializablePlan)}/></label>)}<label><span className="label">{ar?"التخزين (MB)":"Storage (MB)"}</span><input className="input" type="number" min="0" name="maxStorageMegabytes" required defaultValue={plan?String(BigInt(plan.maxStorageBytes)/1048576n):"0"}/></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Toggle name="allowFileUploads" label={ar?"رفع الملفات":"File uploads"} checked={plan?.allowFileUploads}/><Toggle name="allowCustomIcons" label={ar?"أيقونات مخصصة":"Custom icons"} checked={plan?.allowCustomIcons}/><Toggle name="allowCustomLinks" label={ar?"روابط خارجية مخصصة":"Custom external links"} checked={plan?.allowCustomLinks}/></div></Section>
    <Section title={ar?"حد فتح الملف":"Profile opens configuration"} note={ar?"إعداد entitlement فقط حاليًا؛ لا يمنع فتح الملف العام.":"Configuration only; public profile visits are not currently blocked."} icon={SlidersHorizontal}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">{ar?"السياسة":"Policy"}</span><select className="input" name="profileOpenMode" value={openMode} onChange={event=>setOpenMode(event.target.value as typeof openMode)}><option value="UNLIMITED">{ar?"غير محدود":"Unlimited"}</option><option value="DAILY">{ar?"حد يومي":"Per day"}</option><option value="MONTHLY">{ar?"حد شهري":"Per month"}</option></select></label>{openMode!=="UNLIMITED"&&<label><span className="label">{ar?"عدد الفتحات":"Open count"}</span><input className="input" type="number" min="1" max="1000000000" name="profileOpenLimit" required defaultValue={openPolicy.mode!=="UNLIMITED"?openPolicy.limit:1000}/></label>}</div></Section>
    <Section title={ar?"التحليلات":"Analytics"} note={ar?"المتاح حاليًا: الإجمالي والتجميع اليومي/الشهري للفتحات.":"Currently collected: total opens and daily/monthly open aggregates."} icon={BarChart3}><Toggle name="analyticsAllowed" label={ar?"إتاحة التحليلات الأساسية":"Basic opens analytics"} checked={plan?.analyticsAllowed}/><p className="mt-3 text-xs text-slate-500">{ar?"المصدر والجغرافيا والجهاز والقراءة المتقدمة غير متاحة في الدومين الحالي.":"Source, geography, device, and advanced-read analytics are not available in the current domain."}</p></Section>
    <Section title={ar?"الميزات والمظهر":"Features and appearance"} icon={Palette}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Toggle name="customSlugAllowed" label={ar?"رابط ملف مخصص":"Custom profile address"} checked={plan?.customSlugAllowed}/><Toggle name="allowThemes" label={ar?"القوالب":"Templates"} checked={plan?.allowThemes}/><Toggle name="allowCustomTheme" label={ar?"تخصيص المظهر":"Custom appearance"} checked={plan?.allowCustomTheme}/><Toggle name="allowBusinessCards" label={ar?"ملفات الأعمال":"Business profiles"} checked={plan?.allowBusinessCards}/><Toggle name="allowWalletPasses" label={ar?"بطاقات المحفظة":"Wallet passes"} checked={plan?.allowWalletPasses}/><Toggle name="allowInstallableProfiles" label={ar?"ملفات قابلة للتثبيت":"Installable profiles"} checked={plan?.allowInstallableProfiles}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{themeTypes.map(value=><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-xs font-bold" key={value}><input type="checkbox" checked={themes.includes(value)} onChange={()=>choose(value,themes,setThemes)}/>{value.replaceAll("_"," ")}</label>)}</div></Section>
    <Section title={ar?"واجهة العرض والطلب":"Storefront showcase"} note={ar?"عرض منتجات/خدمات واتصال فقط؛ لا سلة ولا دفع ولا شحن.":"Products/services showcase and contact only; no cart, payment, or shipping."} icon={MessagesSquare}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Toggle name="storefrontEnabled" label={ar?"إتاحة قوالب المتجر":"Enable storefront templates"} checked={plan?.storefrontEnabled}/><Toggle name="storefrontProductsEnabled" label={ar?"عرض المنتجات":"Products showcase"} checked={plan?.storefrontProductsEnabled}/><Toggle name="storefrontServicesEnabled" label={ar?"عرض الخدمات":"Services showcase"} checked={plan?.storefrontServicesEnabled}/><Toggle name="storefrontWhatsappOrder" label={ar?"الطلب عبر واتساب":"WhatsApp enquiry"} checked={plan?.storefrontWhatsappOrder}/><Toggle name="storefrontEmailOrder" label={ar?"الطلب عبر البريد":"Email enquiry"} checked={plan?.storefrontEmailOrder}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="label">{ar?"حد العناصر":"Item limit"}</span><select className="input" name="storefrontLimitMode" value={storefrontLimitMode} onChange={event=>setStorefrontLimitMode(event.target.value as "UNLIMITED"|"FIXED")}><option value="UNLIMITED">{ar?"غير محدود":"Unlimited"}</option><option value="FIXED">{ar?"حد ثابت":"Fixed limit"}</option></select></label>{storefrontLimitMode==="FIXED"&&<label><span className="label">{ar?"أقصى عدد للعناصر":"Maximum items"}</span><input className="input" name="storefrontMaxItems" type="number" min="0" max="10000" required defaultValue={plan?.storefrontMaxItems??12}/></label>}</div></Section>
    <Section title={ar?"الإتاحة والحماية":"Availability"} icon={ShieldCheck}><Toggle name="isActive" label={ar?"الباقة متاحة للتعيين والاشتراك":"Plan available for assignment"} checked={plan?.isActive ?? true}/><p className="mt-3 text-xs text-slate-500">{ar?"تعطيل الباقة لا يحذف الاشتراكات التاريخية.":"Disabling never deletes historical subscriptions."}</p></Section>
    {state.code&&<p className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-300">{messages[state.code]?.[locale]||messages.PLAN_SAVE_FAILED[locale]}</p>}
    <footer className="sticky bottom-3 z-10 flex justify-end gap-3 rounded-2xl border border-white/10 bg-slate-950/90 p-3 shadow-xl backdrop-blur"><a href="/admin/plans" className="btn-secondary">{ar?"إلغاء":"Cancel"}</a><button className="btn-primary" disabled={pending||!profiles.length||!themes.length}><Check size={16}/>{pending?(ar?"جارٍ الحفظ…":"Saving…"):(ar?"حفظ الباقة":"Save plan")}</button></footer>
  </form>;
}
