import type { Prisma,ProfileFieldType } from "@popwam/db";
import { Download,ExternalLink,FileText,MapPin } from "lucide-react";
import { isSafeDestinationUrl,normalizeDestination } from "@/lib/url";
import { getI18n } from "@/lib/i18n";
import { ProfileAvatar } from "@/components/profile-avatar";
import { DestinationVisual } from "@/components/destination-visual";

export type PublicProfileData=Prisma.ProfileGetPayload<{include:{user:{select:{email:true}};fields:true;uploads:true;destinations:true}}>;

function link(title:string,type:Parameters<typeof normalizeDestination>[0],value?:string|null){if(!value)return null;const url=normalizeDestination(type,value);return isSafeDestinationUrl(url)?{title,type,url}:null;}
function fieldUrl(field:{type:ProfileFieldType;value:string;actionUrl:string|null}){if(field.actionUrl){const url=normalizeDestination(field.type,field.actionUrl);return isSafeDestinationUrl(url)?url:null;}const map:Partial<Record<ProfileFieldType,string>>={PHONE:"PHONE",EMAIL:"EMAIL",WHATSAPP:"WHATSAPP_PRIVATE",URL:"WEBSITE",FILE:"FILE",LOCATION:"LOCATION",SOCIAL:"SOCIAL"};const type=map[field.type];if(!type)return null;const url=field.type==="LOCATION"&&!/^https?:/i.test(field.value)?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(field.value)}`:normalizeDestination(type,field.value);return isSafeDestinationUrl(url)?url:null;}

export async function PublicProfile({profile}:{profile:PublicProfileData}){
  const {dictionary:d}=await getI18n();
  const contacts=[profile.showWhatsappBusiness?link("WhatsApp Business","WHATSAPP_BUSINESS",profile.whatsappBusiness):null,profile.showWhatsappPrivate?link("WhatsApp","WHATSAPP_PRIVATE",profile.whatsappPrivate):null,profile.showPhone?link("Call","PHONE",profile.phone):null,profile.showEmail?link("Email","EMAIL",profile.email):null,profile.showWebsite?link("Website","WEBSITE",profile.website):null].filter(Boolean) as Array<{title:string;type:"WHATSAPP_BUSINESS"|"WHATSAPP_PRIVATE"|"PHONE"|"EMAIL"|"WEBSITE";url:string}>;
  const socials=profile.showSocialLinks?[link("Facebook","FACEBOOK",profile.facebook),link("LinkedIn","LINKEDIN",profile.linkedin),link("GitHub","GITHUB",profile.github),link("TikTok","TIKTOK",profile.tiktok)].filter(Boolean) as Array<{title:string;type:"FACEBOOK"|"LINKEDIN"|"GITHUB"|"TIKTOK";url:string}>:[];
  const vcf=profile.showSaveContact?link("Save contact","VCF",profile.vcfUrl):null; const fields=profile.showCustomFields?profile.fields.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[]; const files=profile.showUploadedFiles?profile.uploads.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[]; const destinations=profile.destinations.filter(x=>x.isVisible&&x.isActive&&x.type!=="PROFILE").sort((a,b)=>a.sortOrder-b.sortOrder);
  return <main data-theme={profile.theme} className={`public-theme theme-${profile.theme.toLowerCase()} min-h-screen py-0 sm:py-10`}><article className="profile-card mx-auto max-w-xl overflow-hidden sm:rounded-[var(--profile-radius)]">
    {profile.showCover&&profile.coverUrl&&<div className="profile-cover h-48 sm:h-56"><img src={profile.coverUrl} alt="" className="size-full object-cover"/></div>}
    <div className="relative px-5 pb-8 sm:px-8">{profile.showAvatar&&<div className={profile.showCover&&profile.coverUrl?"-mt-14 pt-0":"pt-8"}><ProfileAvatar name={profile.showDisplayName?profile.displayName:null} email={profile.email||profile.user.email} imageUrl={profile.avatarUrl} size={112} className="profile-avatar ring-4 ring-[var(--profile-bg)]"/></div>}{profile.showDisplayName&&<h1 className="profile-name mt-5 text-3xl font-black tracking-tight">{profile.displayName}</h1>}{profile.showTitle&&profile.title&&<p className="profile-accent mt-2">{profile.title}</p>}{profile.showBio&&profile.bio&&<p className="profile-muted mt-4 whitespace-pre-line text-sm leading-7">{profile.bio}</p>}{profile.showLocation&&profile.locationText&&<p className="profile-muted mt-4 flex items-center gap-2 text-sm"><MapPin size={15}/>{profile.locationText}</p>}
      {vcf&&<a href={vcf.url} className="profile-button mt-6 flex w-full items-center justify-center gap-2"><Download size={16}/>{d.profile.saveContact}</a>}
      {!!contacts.length&&<section className="mt-7 grid grid-cols-2 gap-3">{contacts.map(item=><a href={item.url} key={item.title} className="profile-item flex min-h-20 flex-col items-center justify-center rounded-[var(--item-radius)] p-3 text-center"><DestinationVisual type={item.type} className="profile-icon"/><span className="mt-2 text-xs font-semibold">{item.title}</span></a>)}</section>}
      {!!socials.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.social}</p><div className="grid gap-2">{socials.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.title} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] px-4 py-3 text-sm"><DestinationVisual type={item.type} className="profile-icon"/>{item.title}</a>)}</div></section>}
      {!!destinations.length&&<section className="mt-7"><p className="profile-section-label">{d.nav.links}</p><div className="grid gap-2">{destinations.map(item=><a href={item.url} target={item.url.startsWith("http")?"_blank":undefined} rel="noreferrer" key={item.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><DestinationVisual type={item.type} iconKey={item.iconKey} customIconUrl={item.customIconUrl} className="profile-icon"/><span className="min-w-0 flex-1"><strong className="block text-sm">{item.title}</strong><span className="profile-muted block truncate text-xs">{item.url}</span></span><ExternalLink size={15}/></a>)}</div></section>}
      {!!fields.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.more}</p><div className="grid gap-2">{fields.map(field=>{const url=fieldUrl(field);const content=<><span className="profile-icon flex size-10 shrink-0 items-center justify-center rounded-xl"><ExternalLink size={17}/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{field.label}</strong><span className="profile-muted mt-0.5 block break-words text-xs">{field.value}</span></span></>;return url?<a key={field.id} href={url} target={url.startsWith("http")?"_blank":undefined} rel="noreferrer" className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</a>:<div key={field.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</div>;})}</div></section>}
      {!!files.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.files}</p><div className="grid gap-2">{files.map(file=><a href={file.publicUrl} target="_blank" rel="noreferrer" key={file.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><FileText size={20}/><span className="min-w-0 flex-1 truncate text-sm font-semibold">{file.title||file.originalFilename}</span><Download size={16}/></a>)}</div></section>}
    </div></article><p className="profile-muted mt-6 text-center text-xs">Powered by <span className="font-bold">POPWAM Tap</span></p></main>;
}
