import type { Prisma,ProfileFieldType } from "@popwam/db";
import { Download,ExternalLink,FileText,MapPin } from "lucide-react";
import { isSafeDestinationUrl,normalizeDestination } from "@/lib/url";
import { getI18n } from "@/lib/i18n";
import { ProfileAvatar } from "@/components/profile-avatar";
import { DestinationVisual } from "@/components/destination-visual";
import { LocaleSwitcher } from "@/components/locale-switcher";
import { ProfileInstallButton } from "@/components/profile-install-button";
import { templateCssVariables, templateLayoutClass } from "@/lib/profile-templates";
import type { CSSProperties } from "react";

export type PublicProfileData=Prisma.ProfileGetPayload<{include:{user:{select:{email:true}};fields:true;uploads:true;destinations:true;services:true;branches:true;virtualCard:{include:{template:true}}}}>;

function link(title:string,type:Parameters<typeof normalizeDestination>[0],value?:string|null){if(!value)return null;const url=normalizeDestination(type,value);return isSafeDestinationUrl(url)?{title,type,url}:null;}
function fieldUrl(field:{type:ProfileFieldType;value:string;actionUrl:string|null}){if(field.actionUrl){const url=normalizeDestination(field.type,field.actionUrl);return isSafeDestinationUrl(url)?url:null;}const map:Partial<Record<ProfileFieldType,string>>={PHONE:"PHONE",EMAIL:"EMAIL",WHATSAPP:"WHATSAPP_PRIVATE",URL:"WEBSITE",FILE:"FILE",LOCATION:"LOCATION",SOCIAL:"SOCIAL"};const type=map[field.type];if(!type)return null;const url=field.type==="LOCATION"&&!/^https?:/i.test(field.value)?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(field.value)}`:normalizeDestination(type,field.value);return isSafeDestinationUrl(url)?url:null;}

export async function PublicProfile({profile}:{profile:PublicProfileData}){
  const {dictionary:d,locale}=await getI18n();const ar=locale==="ar";
  const localized=(arValue:string|null,enValue:string|null,legacy?:string|null)=>ar?(arValue||enValue||legacy||""):(enValue||arValue||legacy||"");
  const isOrg=profile.type==="ORGANIZATION";
  const name=isOrg?localized(profile.organizationNameAr,profile.organizationNameEn,profile.displayName):localized(profile.displayNameAr,profile.displayNameEn,profile.displayName);
  const title=isOrg?localized(profile.industryAr,profile.industryEn,profile.title):localized(profile.jobTitleAr,profile.jobTitleEn,profile.title);
  const bio=isOrg?localized(profile.descriptionAr,profile.descriptionEn,profile.bio):localized(profile.bioAr,profile.bioEn,profile.bio);
  const address=localized(profile.addressAr,profile.addressEn,profile.locationText);
  const image=isOrg?(profile.logoUrl||profile.avatarUrl):profile.avatarUrl;
  const contacts=[profile.showWhatsappBusiness?link(ar?"واتساب الأعمال":"WhatsApp Business","WHATSAPP_BUSINESS",profile.whatsappBusiness):null,profile.showWhatsappPrivate?link(ar?"واتساب":"WhatsApp","WHATSAPP_PRIVATE",profile.whatsappPrivate):null,profile.showPhone?link(ar?"اتصال":"Call","PHONE",profile.phone):null,profile.showEmail?link(ar?"البريد":"Email","EMAIL",profile.email):null,profile.showWebsite?link(ar?"الموقع":"Website","WEBSITE",profile.website):null].filter(Boolean) as Array<{title:string;type:"WHATSAPP_BUSINESS"|"WHATSAPP_PRIVATE"|"PHONE"|"EMAIL"|"WEBSITE";url:string}>;
  const socials=profile.showSocialLinks?[link("Facebook","FACEBOOK",profile.facebook),link("LinkedIn","LINKEDIN",profile.linkedin),link("GitHub","GITHUB",profile.github),link("TikTok","TIKTOK",profile.tiktok)].filter(Boolean) as Array<{title:string;type:"FACEBOOK"|"LINKEDIN"|"GITHUB"|"TIKTOK";url:string}>:[];
  const fields=profile.showCustomFields?profile.fields.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[];const files=profile.showUploadedFiles?profile.uploads.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[];const destinations=profile.destinations.filter(x=>x.isVisible&&x.isActive&&x.type!=="PROFILE"&&x.type!=="VCF").sort((a,b)=>a.sortOrder-b.sortOrder);
  const selectedTemplate=profile.virtualCard?.template;const templateStyle=templateCssVariables(selectedTemplate?.configuration) as CSSProperties;const templateLayout=templateLayoutClass(selectedTemplate?.configuration);
  return <main data-theme={profile.theme} data-template={selectedTemplate?.slug||"legacy"} style={templateStyle} className={`public-theme theme-${profile.theme.toLowerCase()} ${templateLayout} ${isOrg?"organization-profile":"personal-profile"} min-h-screen py-0 sm:py-10`}><article className="profile-card mx-auto max-w-xl overflow-hidden sm:rounded-[var(--profile-radius)]">
    {profile.showCover&&profile.coverUrl&&<div className="profile-cover h-48 sm:h-56"><img src={profile.coverUrl} alt="" className="size-full object-cover"/></div>}
    <div className="relative px-5 pb-8 sm:px-8"><div className="flex justify-end pt-4"><LocaleSwitcher locale={locale} label={ar?"English":"العربية"}/></div>{profile.showAvatar&&<div className={profile.showCover&&profile.coverUrl?"-mt-10 pt-0":"pt-4"}><ProfileAvatar name={name} email={profile.email||profile.user.email} imageUrl={image} size={isOrg?96:112} className={`profile-avatar ring-4 ring-[var(--profile-bg)] ${isOrg?"rounded-xl":""}`}/></div>}{profile.showDisplayName&&<h1 className="profile-name mt-5 text-3xl font-black tracking-tight">{name}</h1>}{profile.showTitle&&title&&<p className="profile-accent mt-2">{title}</p>}{isOrg&&profile.company&&<p className="profile-muted mt-1 text-sm">{profile.company}</p>}{profile.showBio&&bio&&<p className="profile-muted mt-4 whitespace-pre-line text-sm leading-7">{bio}</p>}{profile.showLocation&&address&&<p className="profile-muted mt-4 flex items-center gap-2 text-sm"><MapPin size={15}/>{address}</p>}
      {profile.showSaveContact&&<a href={`/api/profiles/${profile.id}/contact.vcf`} className="profile-button mt-6 flex w-full items-center justify-center gap-2"><Download size={16}/>{ar?"حفظ جهة الاتصال":"Save Contact"}</a>}
      <ProfileInstallButton name={name} locale={locale}/>
      {!!contacts.length&&<section className="mt-7 grid grid-cols-2 gap-3">{contacts.map(item=><a href={item.url} key={item.title} className="profile-item flex min-h-20 flex-col items-center justify-center rounded-[var(--item-radius)] p-3 text-center"><DestinationVisual type={item.type} className="profile-icon"/><span className="mt-2 text-xs font-semibold">{item.title}</span></a>)}</section>}
      {isOrg&&!!profile.services.length&&<section className="mt-7"><p className="profile-section-label">{ar?"الخدمات":"Services"}</p><div className="grid gap-2">{profile.services.filter(x=>x.isVisible).map(item=><div key={item.id} className="profile-item rounded-[var(--item-radius)] p-4"><strong className="text-sm">{localized(item.nameAr,item.nameEn)}</strong>{localized(item.descriptionAr,item.descriptionEn)&&<p className="profile-muted mt-1 text-xs leading-6">{localized(item.descriptionAr,item.descriptionEn)}</p>}</div>)}</div></section>}
      {isOrg&&!!profile.branches.length&&<section className="mt-7"><p className="profile-section-label">{ar?"الفروع":"Branches"}</p><div className="grid gap-2">{profile.branches.filter(x=>x.isVisible).map(item=><div key={item.id} className="profile-item rounded-[var(--item-radius)] p-4"><strong className="text-sm">{localized(item.nameAr,item.nameEn)}</strong><p className="profile-muted mt-1 text-xs">{localized(item.addressAr,item.addressEn)}{item.phone?` · ${item.phone}`:""}</p></div>)}</div></section>}
      {!!socials.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.social}</p><div className="grid gap-2">{socials.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.title} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] px-4 py-3 text-sm"><DestinationVisual type={item.type} className="profile-icon"/>{item.title}</a>)}</div></section>}
      {!!destinations.length&&<section className="mt-7"><p className="profile-section-label">{d.nav.links}</p><div className="grid gap-2">{destinations.map(item=><a href={item.url} target={item.url.startsWith("http")?"_blank":undefined} rel="noreferrer" key={item.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><DestinationVisual type={item.type} iconKey={item.iconKey} customIconUrl={item.customIconUrl} className="profile-icon"/><span className="min-w-0 flex-1"><strong className="block text-sm">{localized(item.titleAr,item.titleEn,item.title)}</strong><span className="profile-muted block truncate text-xs" dir="ltr">{item.url}</span></span><ExternalLink size={15}/></a>)}</div></section>}
      {!!fields.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.more}</p><div className="grid gap-2">{fields.map(field=>{const url=fieldUrl(field);const content=<><span className="profile-icon flex size-10 shrink-0 items-center justify-center rounded-xl"><ExternalLink size={17}/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{localized(field.labelAr,field.labelEn,field.label)}</strong><span className="profile-muted mt-0.5 block break-words text-xs">{field.value}</span></span></>;return url?<a key={field.id} href={url} target={url.startsWith("http")?"_blank":undefined} rel="noreferrer" className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</a>:<div key={field.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</div>})}</div></section>}
      {!!files.length&&<section className="mt-7"><p className="profile-section-label">{d.profile.files}</p><div className="grid gap-2">{files.map(file=><a href={file.publicUrl} target="_blank" rel="noreferrer" key={file.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><FileText size={20}/><span className="min-w-0 flex-1 truncate text-sm font-semibold">{localized(file.displayTitleAr,file.displayTitleEn,file.title||file.originalName||file.originalFilename)}</span><Download size={16}/></a>)}</div></section>}
    </div></article><p className="profile-muted mt-6 text-center text-xs">Powered by <span className="font-bold">POPWAM Tap</span></p></main>;
}
