import type { ProfileFieldType } from "@popwam/db";
import { Download,ExternalLink,FileText,MapPin } from "lucide-react";
import { isSafeDestinationUrl,normalizeDestination } from "@/lib/url";
import { getI18n } from "@/lib/i18n";
import { ProfileAvatar } from "@/components/profile-avatar";
import { DestinationVisual } from "@/components/destination-visual";
import { LocaleSwitcher } from "@/components/locale-switcher";
import { ProfileInstallButton } from "@/components/profile-install-button";
import { resolveApprovedTemplate, templateCssVariables, templateLayoutClass } from "@/lib/profile-templates";
import { loadProfileTemplateFrame } from "@/lib/profile-template-renderer";
import type { CSSProperties } from "react";
import type { FriendPrivacyView } from "@/lib/friend-privacy";
import { ProfileShareActions } from "@/components/profile-share-actions";
import { FriendProfileAction } from "@/components/friend-profile-action";
import { moduleUsesCanonicalPublicState, type PublicProfileProjectionData } from "@/lib/profile-projection";
import { publicProfileFieldRows } from "@/lib/profile-public-fields";
import { getUserEntitlements } from "@/lib/plans";
import { canonicalProfileUrl, DISABLED_STOREFRONT_POLICY, selectStorefrontItems, storefrontContactChannels, type StorefrontPolicy } from "@/lib/storefront-order";
import { StorefrontOrderActions } from "@/components/storefront-order-actions";

export type PublicProfileData=PublicProfileProjectionData;
export type AdminTemplatePreviewContext={locale:"ar"|"en";storefrontPolicy:StorefrontPolicy};

async function storefrontPolicyFor(ownerId?:string|null):Promise<StorefrontPolicy>{if(!ownerId)return DISABLED_STOREFRONT_POLICY;try{const {effective}=await getUserEntitlements(ownerId);return{enabled:effective.storefrontEnabled,products:effective.storefrontProductsEnabled,services:effective.storefrontServicesEnabled,maxItems:effective.storefrontMaxItems,whatsapp:effective.storefrontWhatsappOrder,email:effective.storefrontEmailOrder};}catch{return DISABLED_STOREFRONT_POLICY;}}

function link(title:string,type:Parameters<typeof normalizeDestination>[0],value?:string|null){if(!value)return null;const url=normalizeDestination(type,value);return isSafeDestinationUrl(url)?{title,type,url}:null;}
function fieldUrl(field:{type:ProfileFieldType;value:string;actionUrl:string|null}){if(field.actionUrl){const url=normalizeDestination(field.type,field.actionUrl);return isSafeDestinationUrl(url)?url:null;}const map:Partial<Record<ProfileFieldType,string>>={PHONE:"PHONE",EMAIL:"EMAIL",WHATSAPP:"WHATSAPP_PRIVATE",URL:"WEBSITE",FILE:"FILE",LOCATION:"LOCATION",SOCIAL:"SOCIAL"};const type=map[field.type];if(!type)return null;const url=field.type==="LOCATION"&&!/^https?:/i.test(field.value)?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(field.value)}`:normalizeDestination(type,field.value);return isSafeDestinationUrl(url)?url:null;}

export async function PublicProfile({profile,ownerId,privacy,audience="PUBLIC",showFriendAction=false,adminPreviewContext}:{profile:PublicProfileData;ownerId?:string|null;privacy?:FriendPrivacyView|null;audience?:"PUBLIC"|"FRIEND";showFriendAction?:boolean;adminPreviewContext?:AdminTemplatePreviewContext}){
  const i18n=await getI18n();const d=i18n.dictionary;const locale=adminPreviewContext?.locale??i18n.locale;const ar=locale==="ar";
  const localized=(arValue:string|null,enValue:string|null,legacy?:string|null)=>ar?(arValue||enValue||legacy||""):(enValue||arValue||legacy||"");
  const isOrg=profile.profileKind==="BUSINESS"||profile.type==="ORGANIZATION";
  const identityVisible=moduleUsesCanonicalPublicState(profile,"IDENTITY",true,audience);
  const aboutVisible=moduleUsesCanonicalPublicState(profile,"ABOUT",true,audience);
  const contactVisible=moduleUsesCanonicalPublicState(profile,"CONTACT",true,audience);
  const socialVisible=moduleUsesCanonicalPublicState(profile,"SOCIAL",true,audience);
  const linksVisible=moduleUsesCanonicalPublicState(profile,"LINKS",true,audience);
  const galleryVisible=moduleUsesCanonicalPublicState(profile,"GALLERY",true,audience);
  const servicesVisible=moduleUsesCanonicalPublicState(profile,"SERVICES",true,audience);
  const branchesVisible=moduleUsesCanonicalPublicState(profile,"BRANCHES",true,audience);
  const fullAccess=!privacy||privacy.level==="FULL_PROFILE"||(privacy.level==="BUSINESS_ONLY"&&isOrg);const contactOnly=privacy?.level==="CONTACT_ONLY";const selectedOnly=privacy?.level==="SELECTED_LINKS";
  const name=isOrg?localized(profile.organizationNameAr,profile.organizationNameEn,profile.displayName):localized(profile.displayNameAr,profile.displayNameEn,profile.displayName);
  const title=isOrg?localized(profile.industryAr,profile.industryEn,profile.title):localized(profile.jobTitleAr,profile.jobTitleEn,profile.title);
  const bio=isOrg?localized(profile.descriptionAr,profile.descriptionEn,profile.bio):localized(profile.bioAr,profile.bioEn,profile.bio);
  const address=localized(profile.addressAr,profile.addressEn,profile.locationText);
  const image=isOrg?(profile.logoUrl||profile.avatarUrl):profile.avatarUrl;
  const contacts=(fullAccess||contactOnly)&&contactVisible?[profile.showWhatsappBusiness?link(ar?"واتساب الأعمال":"WhatsApp Business","WHATSAPP_BUSINESS",profile.whatsappBusiness):null,profile.showWhatsappPrivate?link(ar?"واتساب":"WhatsApp","WHATSAPP_PRIVATE",profile.whatsappPrivate):null,profile.showPhone?link(ar?"اتصال":"Call","PHONE",profile.phone):null,profile.showEmail?link(ar?"البريد":"Email","EMAIL",profile.email):null,profile.showWebsite?link(ar?"الموقع":"Website","WEBSITE",profile.website):null].filter(Boolean) as Array<{title:string;type:"WHATSAPP_BUSINESS"|"WHATSAPP_PRIVATE"|"PHONE"|"EMAIL"|"WEBSITE";url:string}>:[];
  const socials=fullAccess&&socialVisible&&profile.showSocialLinks?[link("Facebook","FACEBOOK",profile.facebook),link("LinkedIn","LINKEDIN",profile.linkedin),link("GitHub","GITHUB",profile.github),link("TikTok","TIKTOK",profile.tiktok)].filter(Boolean) as Array<{title:string;type:"FACEBOOK"|"LINKEDIN"|"GITHUB"|"TIKTOK";url:string}>:[];
  const fields=fullAccess&&aboutVisible&&profile.showCustomFields?profile.fields.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[];const files=fullAccess&&galleryVisible&&profile.showUploadedFiles?profile.uploads.filter(x=>x.isVisible).sort((a,b)=>a.sortOrder-b.sortOrder):[];const media=fullAccess&&galleryVisible?profile.media.filter(x=>x.visibility==="PUBLIC"&&isSafeDestinationUrl(x.publicUrl)).sort((a,b)=>a.sortOrder-b.sortOrder):[];const selectedIds=new Set(privacy?.selectedDestinationIds||[]);const destinations=linksVisible?profile.destinations.filter(x=>x.isVisible&&x.isActive&&x.type!=="PROFILE"&&x.type!=="VCF"&&(fullAccess||(selectedOnly&&selectedIds.has(x.id)))).sort((a,b)=>a.sortOrder-b.sortOrder):[];
  const structuredFields=fullAccess?publicProfileFieldRows({kind:profile.profileKind==="BUSINESS"||profile.type==="ORGANIZATION"?"BUSINESS":"PERSONAL",categoryKey:profile.categorySlug||null,locale,entries:profile.sectionEntries}):[];
  const selectedTemplate=profile.virtualCard?.template;
  const approvedTemplate=resolveApprovedTemplate({slug:selectedTemplate?.slug,profileKind:isOrg?"BUSINESS":"PERSONAL"});
  const configuration=selectedTemplate?.slug===approvedTemplate.slug&&selectedTemplate.configuration&&typeof selectedTemplate.configuration==="object"&&!Array.isArray(selectedTemplate.configuration)?{...approvedTemplate.configuration,...selectedTemplate.configuration}:approvedTemplate.configuration;
  const storefrontPolicy=approvedTemplate.family==="storefront"?(adminPreviewContext?.storefrontPolicy??await storefrontPolicyFor(ownerId)):DISABLED_STOREFRONT_POLICY;
  const allVisibleServices=profile.services.filter(x=>x.isVisible);
  const visibleServices=approvedTemplate.family==="storefront"?selectStorefrontItems(allVisibleServices,storefrontPolicy):allVisibleServices;
  const storefrontProfileUrl=canonicalProfileUrl(profile.slug);
  const orderChannels=storefrontContactChannels(storefrontPolicy,{contactPublic:contactVisible&&fullAccess,whatsapp:(profile.showWhatsappBusiness?profile.whatsappBusiness:null)||(profile.showWhatsappPrivate?profile.whatsappPrivate:null),email:profile.showEmail?profile.email:null});
  const orderWhatsapp=orderChannels.whatsapp;const orderEmail=orderChannels.email;
  const templateStyle=templateCssVariables(configuration) as CSSProperties;const templateLayout=templateLayoutClass(configuration);
  const TemplateFrame=await loadProfileTemplateFrame(approvedTemplate.family);
  const fidelityTemplate=approvedTemplate.source>=1&&approvedTemplate.source<=6;
  const businessFidelityTemplate=approvedTemplate.source>=7&&approvedTemplate.source<=10;
  const connectContact=contacts.find(item=>item.type==="EMAIL")??contacts[0];
  const cvFile=files[0];
  const rendered=<TemplateFrame slug={approvedTemplate.slug} theme={profile.theme} style={templateStyle} layoutClass={templateLayout} organization={isOrg}>
    {identityVisible&&profile.showCover&&profile.coverUrl&&<div className="profile-cover h-48 sm:h-56"><img src={profile.coverUrl} alt="" className="size-full object-cover"/></div>}
    <div className="profile-identity-content relative px-5 pb-8 sm:px-8"><div className="profile-locale-row flex justify-end pt-4"><LocaleSwitcher locale={locale} label={ar?"English":"العربية"}/></div>{identityVisible&&profile.showAvatar&&<div className={`profile-avatar-wrap flex ${profile.showCover&&profile.coverUrl?"-mt-10 pt-0":"pt-4"}`}><ProfileAvatar name={name} email={profile.email||undefined} imageUrl={image} size={isOrg?96:112} className={`profile-avatar ring-4 ring-[var(--profile-bg)] ${isOrg?"rounded-xl":""}`}/></div>}{identityVisible&&profile.showDisplayName&&<h1 className="profile-name mt-5 text-3xl font-black tracking-tight">{name}</h1>}{identityVisible&&profile.showTitle&&title&&<p className="profile-title profile-accent mt-2">{title}</p>}{fullAccess&&identityVisible&&isOrg&&profile.company&&<p className="profile-company profile-muted mt-1 text-sm">{profile.company}</p>}{fullAccess&&aboutVisible&&profile.showBio&&bio&&<p className="profile-bio profile-muted mt-4 whitespace-pre-line text-sm leading-7">{bio}</p>}{(fullAccess||contactOnly)&&contactVisible&&profile.showLocation&&address&&<p className="profile-location profile-muted mt-4 flex items-center gap-2 text-sm"><MapPin size={15}/>{address}</p>}
      {fidelityTemplate&&(connectContact||cvFile)&&approvedTemplate.source<=3&&<div className="profile-source-actions">{connectContact&&<a href={connectContact.url} className="profile-source-action profile-source-action-primary">{ar?"لنتواصل":"Let's connect"}<ExternalLink size={17}/></a>}{cvFile&&<a href={cvFile.publicUrl} target="_blank" rel="noreferrer" className="profile-source-action profile-source-action-secondary"><Download size={17}/>{ar?"تحميل السيرة الذاتية":"Download CV"}</a>}</div>}
      {businessFidelityTemplate&&(connectContact||visibleServices.length>0)&&<div className="profile-business-actions">{connectContact&&<a href={connectContact.url} className="profile-business-action profile-business-action-primary">{ar?"تواصل معنا":"Contact us"}<ExternalLink size={17}/></a>}{visibleServices.length>0&&<a href="#services" className="profile-business-action profile-business-action-secondary">{approvedTemplate.source===9?(ar?"عرض المجموعة":"View collection"):(ar?"استكشف خدماتنا":"Explore services")}</a>}</div>}
      {(fullAccess||contactOnly)&&contactVisible&&profile.showSaveContact&&<a href={`/api/profiles/${profile.id}/contact.vcf`} className="profile-button mt-6 flex w-full items-center justify-center gap-2"><Download size={16}/>{ar?"حفظ جهة الاتصال":"Save Contact"}</a>}
      {fullAccess&&profile.allowInstallable&&<ProfileInstallButton name={name} locale={locale}/>}
      <ProfileShareActions name={name} locale={locale}/>
      {showFriendAction&&profile.slug&&<FriendProfileAction profileSlug={profile.slug} copy={d.friendsCenter}/>}
      {!!contacts.length&&<section className="profile-contacts mt-7 grid grid-cols-2 gap-3">{contacts.map(item=><a href={item.url} key={item.title} className="profile-item flex min-h-20 flex-col items-center justify-center rounded-[var(--item-radius)] p-3 text-center"><DestinationVisual type={item.type} className="profile-icon"/><span className="mt-2 text-xs font-semibold">{item.title}</span></a>)}</section>}
      {fullAccess&&servicesVisible&&isOrg&&visibleServices.length>0&&(approvedTemplate.family!=="storefront"||storefrontPolicy.enabled)&&<section id="services" className={`profile-services mt-7 ${approvedTemplate.family==="storefront"?"profile-catalog":""}`}><p className="profile-section-label">{approvedTemplate.family==="storefront"?(ar?"المنتجات والخدمات":"Products & services"):(ar?"الخدمات":"Services")}</p><div className="grid gap-2">{visibleServices.map(item=>{const itemName=localized(item.nameAr,item.nameEn);const itemPrice=item.price!=null?new Intl.NumberFormat(locale,{style:"currency",currency:item.currency||"EGP"}).format(Number(item.price)):null;const itemUrl=`${storefrontProfileUrl}#item-${encodeURIComponent(item.id)}`;return <article id={`item-${item.id}`} key={item.id} data-storefront-type={item.itemType.toLowerCase()} data-storefront-featured={item.featured?"true":"false"} className={`profile-item scroll-mt-5 overflow-hidden rounded-[var(--item-radius)] p-4 ${approvedTemplate.family==="storefront"?"profile-catalog-item":""}`}>{item.imageUrl&&isSafeDestinationUrl(item.imageUrl)&&<img src={item.imageUrl} alt={itemName} loading={adminPreviewContext?"eager":"lazy"} className={`mb-3 aspect-[4/3] w-full rounded-[calc(var(--item-radius)*.75)] object-cover ${approvedTemplate.family==="storefront"?"profile-catalog-image":""}`}/>}<div className="profile-catalog-heading flex flex-wrap items-start justify-between gap-2"><strong className="text-sm">{itemName}</strong>{approvedTemplate.family==="storefront"&&<span className="profile-muted text-[10px] font-bold uppercase">{item.itemType==="PRODUCT"?(ar?"منتج":"Product"):(ar?"خدمة":"Service")}</span>}</div>{item.category&&<p className="profile-catalog-category profile-muted mt-1 text-[10px]">{item.category}</p>}{localized(item.descriptionAr,item.descriptionEn)&&<p className="profile-catalog-description profile-muted mt-1 text-xs leading-6">{localized(item.descriptionAr,item.descriptionEn)}</p>}{itemPrice&&<p className="profile-catalog-price profile-accent mt-2 text-sm font-black" dir="ltr">{itemPrice}</p>}{approvedTemplate.family==="storefront"&&<StorefrontOrderActions locale={locale} businessName={name} itemName={itemName} price={itemPrice} profileUrl={itemUrl} whatsapp={orderWhatsapp} email={orderEmail}/>}</article>})}</div></section>}
      {fullAccess&&branchesVisible&&isOrg&&!!profile.branches.length&&<section className="profile-branches mt-7"><p className="profile-section-label">{ar?"الفروع":"Branches"}</p><div className="grid gap-2">{profile.branches.filter(x=>x.isVisible).map(item=><div key={item.id} className="profile-item rounded-[var(--item-radius)] p-4"><strong className="text-sm">{localized(item.nameAr,item.nameEn)}</strong><p className="profile-muted mt-1 text-xs">{localized(item.addressAr,item.addressEn)}{item.phone?` · ${item.phone}`:""}</p></div>)}</div></section>}
      {!!socials.length&&<section className="profile-socials mt-7"><p className="profile-section-label">{d.profile.social}</p><div className="grid gap-2">{socials.map(item=><a href={item.url} target="_blank" rel="noreferrer" key={item.title} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] px-4 py-3 text-sm"><DestinationVisual type={item.type} className="profile-icon"/>{item.title}</a>)}</div></section>}
      {!!destinations.length&&<section className="profile-links mt-7"><p className="profile-section-label">{d.nav.links}</p><div className="grid gap-2">{destinations.map(item=><a href={item.url} target={item.url.startsWith("http")?"_blank":undefined} rel="noreferrer" key={item.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><DestinationVisual type={item.type} iconKey={item.iconKey} customIconUrl={item.customIconUrl} className="profile-icon"/><span className="min-w-0 flex-1"><strong className="block text-sm">{localized(item.titleAr,item.titleEn,item.title)}</strong><span className="profile-muted block truncate text-xs" dir="ltr">{item.url}</span></span><ExternalLink size={15}/></a>)}</div></section>}
      {!!fields.length&&<section className="profile-fields mt-7"><p className="profile-section-label">{d.profile.more}</p><div className="grid gap-2">{fields.map(field=>{const url=fieldUrl(field);const content=<><span className="profile-icon flex size-10 shrink-0 items-center justify-center rounded-xl"><ExternalLink size={17}/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{localized(field.labelAr,field.labelEn,field.label)}</strong><span className="profile-muted mt-0.5 block break-words text-xs">{field.value}</span></span></>;return url?<a key={field.id} href={url} target={url.startsWith("http")?"_blank":undefined} rel="noreferrer" className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</a>:<div key={field.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</div>})}</div></section>}
      {!!structuredFields.length&&<section className="profile-structured mt-7"><p className="profile-section-label">{ar?"تفاصيل الملف":"Profile details"}</p><div className="grid gap-2">{structuredFields.map(field=>{const content=<span className="min-w-0 flex-1"><strong className="block text-sm">{field.label}</strong><span className="profile-muted mt-0.5 block break-words text-xs" dir={field.direction}>{field.primary}</span>{field.secondary&&<span className="profile-muted mt-1 block break-words text-xs">{field.secondary}</span>}</span>;return field.href?<a key={field.id} href={field.href} target={field.href.startsWith("http")?"_blank":undefined} rel="noreferrer" className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}<ExternalLink size={15}/></a>:<div key={field.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3">{content}</div>})}</div></section>}
      {!!media.length&&<section className="profile-gallery mt-7"><p className="profile-section-label">{ar?"أعمال مختارة":"Selected work"}</p><div className="grid grid-cols-2 gap-3">{media.map(item=><img key={item.id} src={item.publicUrl} alt="" loading={adminPreviewContext?"eager":"lazy"} className="profile-item aspect-[4/3] size-full rounded-[var(--item-radius)] object-cover"/>)}</div></section>}
      {!!files.length&&<section className="profile-files mt-7"><p className="profile-section-label">{d.profile.files}</p><div className="grid gap-2">{files.map(file=><a href={file.publicUrl} target="_blank" rel="noreferrer" key={file.id} className="profile-item flex items-center gap-3 rounded-[var(--item-radius)] p-3"><FileText size={20}/><span className="min-w-0 flex-1 truncate text-sm font-semibold">{localized(file.displayTitleAr,file.displayTitleEn,file.title||file.originalName||file.originalFilename)}</span><Download size={16}/></a>)}</div></section>}
    </div></TemplateFrame>;
  return adminPreviewContext?<div lang={locale} dir={ar?"rtl":"ltr"} data-template-review-ready="true" data-preview-name={name} data-preview-item-count={visibleServices.length}>{rendered}</div>:rendered;
}
