import Link from "next/link";
import { Eye, LockKeyhole } from "lucide-react";
import { prisma } from "@popwam/db";
import { selectProfileTemplate } from "@/app/catalog-actions";
import { PageHeading } from "@/components/page-heading";
import { requireUser } from "@/lib/session";
import { getUserEntitlements } from "@/lib/plans";
import { templateCssVariables, templateLayoutClass } from "@/lib/profile-templates";
import { templateAllowed } from "@/lib/virtual-cards";

export default async function TemplatesPage() {
  const user = await requireUser();
  const [cards, templates, { plan }] = await Promise.all([prisma.virtualCard.findMany({ where: { userId: user.id, status: "ACTIVE" }, orderBy: { createdAt: "asc" } }), prisma.profileTemplate.findMany({ where: { isActive: true }, orderBy: [{ sortOrder: "asc" }, { nameEn: "asc" }] }), getUserEntitlements(user.id)]);
  return <><PageHeading eyebrow="Appearance" title="Template catalog / كتالوج القوالب" description="Templates change cover, avatar, identity alignment, contacts, links, spacing, and desktop behavior—not only colors."/><div className="space-y-7">{cards.map(card => <section key={card.id}><h2 className="mb-3 text-lg font-bold">{card.name}</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{templates.map(template => { const allowed = templateAllowed(plan.slug, template.minimumPlan); const style = templateCssVariables(template.configuration); const layout=templateLayoutClass(template.configuration);return <article className={`overflow-hidden rounded-3xl border border-white/10 ${layout}`} style={{ background: style["--profile-bg"] || "#111313", color: style["--profile-text"] || "#fff", borderRadius: style["--profile-radius"] }} key={template.id}>{template.previewImageUrl?<img src={template.previewImageUrl} alt={`${template.nameEn} preview`} className="h-48 w-full object-cover"/>:<div className="h-48 p-4" style={{ background: style["--profile-panel"] || "#191c1c" }}><div className="profile-cover h-14 rounded-lg" style={{background:style["--profile-accent"]||"#55d6a5",opacity:.28}}/><div className="profile-avatar-wrap -mt-5 flex"><div className="size-12 rounded-full border-4" style={{background:style["--profile-bg"]||"#111",borderColor:style["--profile-panel"]||"#222"}}/></div><div className="profile-name mt-2 h-3 w-1/2 rounded bg-current opacity-80"/><div className="mt-2 h-2 w-3/4 rounded bg-current opacity-25"/><div className="mt-4 grid grid-cols-2 gap-2"><div className="h-9 rounded-lg bg-current opacity-10"/><div className="h-9 rounded-lg bg-current opacity-10"/></div></div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div><strong>{template.nameEn} / {template.nameAr}</strong><p className="mt-1 text-xs opacity-60">{template.category} · {template.minimumPlan.toUpperCase()}+</p></div>{!allowed&&<LockKeyhole size={17} className="text-amber-300"/>}</div><div className="mt-3 flex gap-2"><Link className="btn-secondary flex-1" href={`/dashboard/templates/preview/${template.id}?card=${card.id}`}><Eye size={14}/>Preview</Link>{allowed?<form action={selectProfileTemplate} className="flex-1"><input type="hidden" name="virtualCardId" value={card.id}/><input type="hidden" name="templateId" value={template.id}/><button className="btn-primary w-full" disabled={card.themeId === template.id}>{card.themeId === template.id ? "Applied" : "Apply"}</button></form>:<Link className="btn-primary flex-1" href="/dashboard/plans">Upgrade / Buy</Link>}</div>{!allowed&&<p className="mt-3 rounded-xl bg-amber-400/10 p-3 text-xs text-amber-200">Requires the {template.minimumPlan.toUpperCase()} plan. Preview remains available before purchase.</p>}</div></article>; })}</div></section>)}</div></>;
}
