import {notFound} from "next/navigation";
import {prisma} from "@popwam/db";
import {markChatRead,reportMessage,sendMessage} from "@/app/social-actions";
import {PageHeading} from "@/components/page-heading";
import {requireUser} from "@/lib/session";

export default async function ChatPage({params}:{params:Promise<{chatId:string}>}){const user=await requireUser();const {chatId}=await params;const membership=await prisma.chatMember.findUnique({
  where:{chatId_userId:{chatId,userId:user.id}},
  include:{chat:{include:{
    members:{include:{user:{select:{id:true,name:true,username:true}}}},
    messages:{take:100,orderBy:{createdAt:"asc"},include:{sender:{select:{id:true,name:true,username:true}},attachment:true,reports:{where:{reporterId:user.id},select:{id:true,status:true}}}},
  }}},
});if(!membership)notFound();const [files]=await Promise.all([prisma.uploadedFile.findMany({where:{uploaderUserId:user.id},select:{id:true,title:true,originalFilename:true},orderBy:{createdAt:"desc"},take:30})]);const other=membership.chat.members.find(item=>item.userId!==user.id)?.user;return <><PageHeading eyebrow="Private chat" title={other?.name||`@${other?.username}`} description="Messages are not available in the general admin interface. Reporting preserves the evidence for restricted, audited review."/><form action={markChatRead} className="mb-3"><input type="hidden" name="chatId" value={chatId}/><button className="btn-secondary">Mark as read / تحديد كمقروء</button></form><section className="card max-h-[58vh] space-y-3 overflow-y-auto p-5">{membership.chat.messages.map(message=><article className={`max-w-[85%] rounded-2xl p-4 ${message.senderId===user.id?"ms-auto bg-brand-500/15":"bg-white/5"}`} key={message.id}><p className="text-xs font-bold text-slate-500">{message.sender.name||`@${message.sender.username}`}</p>{message.body&&<p className="mt-1 whitespace-pre-wrap text-sm">{message.body}</p>}{message.attachment&&<a className="mt-2 block text-sm text-brand-300 underline" href={message.attachment.publicUrl} target="_blank" rel="noreferrer">{message.attachment.title||message.attachment.originalFilename}</a>}{message.senderId!==user.id&&(message.reports.length?<p className="mt-2 text-xs text-amber-300">Reported · {message.reports[0].status}</p>:<details className="mt-2"><summary className="cursor-pointer text-xs text-slate-500">Report message / إبلاغ</summary><form action={reportMessage} className="mt-2 flex gap-2"><input type="hidden" name="messageId" value={message.id}/><input className="input" name="reason" placeholder="Reason" required/><button className="btn-secondary">Report</button></form></details>)}</article>)}{!membership.chat.messages.length&&<p className="text-center text-sm text-slate-500">Start the conversation.</p>}</section><form action={sendMessage} className="card mt-4 grid gap-3 p-4 sm:grid-cols-[1fr_220px_auto]"><input type="hidden" name="chatId" value={chatId}/><textarea className="input min-h-20" name="body" placeholder="Write a message…" maxLength={4000}/><select className="input" name="attachmentFileId"><option value="">No attachment</option>{files.map(file=><option value={file.id} key={file.id}>{file.title||file.originalFilename}</option>)}</select><button className="btn-primary self-end">Send / إرسال</button></form></>}
