import Link from "next/link";
import { Eye, Layers3, Settings2 } from "lucide-react";
import { prisma } from "@popwam/db";
import { saveProfileTemplate } from "@/app/catalog-actions";
import { DashboardPageHeader, FilterBar, StatusBadge } from "@/components/admin-ui";
import { TemplatePreviewCard } from "@/components/template-preview-card";
import { ensureApprovedProfileTemplates } from "@/lib/figma-templates";
import { getI18n } from "@/lib/i18n";
import { APPROVED_PROFILE_TEMPLATES } from "@/lib/profile-templates";

export default async function TemplatesAdminPage({searchParams}:{searchParams:Promise<{family?:string}>}) {
  await ensureApprovedProfileTemplates();
  const [{locale},{family}] = await Promise.all([getI18n(),searchParams]); const ar=locale==="ar";
  const rows=await prisma.profileTemplate.findMany({where:{slug:{in:APPROVED_PROFILE_TEMPLATES.map(item=>item.slug)}},orderBy:{sortOrder:"asc"}});
  const bySlug=new Map(rows.map(row=>[row.slug,row])); const families=[...new Set(APPROVED_PROFILE_TEMPLATES.map(item=>item.family))];
  const shown=family?APPROVED_PROFILE_TEMPLATES.filter(item=>item.family===family):APPROVED_PROFILE_TEMPLATES;
  const copy=ar?{eyebrow:"نظام القوالب العام",title:"قوالب الملفات",description:"17 تصميمًا معتمدًا تُعرض ببيانات النسخة المنشورة وتحترم الخصوصية والخطة ونوع الحساب.",all:"كل العائلات",source:"التصميم",manage:"إدارة",preview:"معاينة",active:"مفعل",save:"حفظ الإعدادات",plan:"الحد الأدنى للخطة",kind:"نوع الملف"}:{eyebrow:"Public template system",title:"Profile templates",description:"17 approved designs rendered from published profile data with privacy, plan, and account-type eligibility.",all:"All families",source:"Design",manage:"Manage",preview:"Preview",active:"Active",save:"Save settings",plan:"Minimum plan",kind:"Profile kind"};
  return <><DashboardPageHeader eyebrow={copy.eyebrow} title={copy.title} description={copy.description} action={<div className="admin-metric-icon"><Layers3 size={20}/></div>}/>
    <FilterBar><div className="flex flex-wrap gap-2"><Link className={!family?"btn-primary":"btn-secondary"} href="/admin/templates">{copy.all}</Link>{families.map(value=><Link className={family===value?"btn-primary":"btn-secondary"} href={`/admin/templates?family=${value}`} key={value}>{value}</Link>)}</div></FilterBar>
    <div className="mt-5 grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{shown.map(definition=>{const row=bySlug.get(definition.slug);return <article className="admin-section-card overflow-hidden !p-0" key={definition.slug}><TemplatePreviewCard slug={definition.slug}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="admin-eyebrow">{copy.source} {definition.source} · {definition.family}</p><h2 className="mt-1 text-lg font-black">{ar?definition.nameAr:definition.nameEn}</h2><p className="mt-1 text-xs text-slate-500" dir="ltr">{definition.slug}</p></div><StatusBadge value={row?.isActive===false?"DISABLED":"ACTIVE"}/></div>
      <div className="mt-4 flex flex-wrap gap-2"><span className="admin-chip">{copy.kind}: {definition.profileKind}</span><span className="admin-chip">{copy.plan}: {(row?.minimumPlan||definition.minimumPlan).toUpperCase()}</span>{definition.supportedModules.slice(0,4).map(module=><span className="admin-chip" key={module}>{module}</span>)}{definition.supportedModules.length>4&&<span className="admin-chip">+{definition.supportedModules.length-4}</span>}</div><div className="mt-4 flex gap-2"><Link className="btn-secondary flex-1" href={`/admin/templates/preview/${definition.slug}`}><Eye size={15}/>{copy.preview}</Link><details className="relative flex-1"><summary className="btn-primary cursor-pointer list-none"><Settings2 size={15}/>{copy.manage}</summary><form action={saveProfileTemplate} className="card absolute bottom-12 end-0 z-20 w-[min(88vw,24rem)] space-y-3 p-4">
        {row&&<input type="hidden" name="id" value={row.id}/>}<input type="hidden" name="slug" value={definition.slug}/><input type="hidden" name="nameAr" value={definition.nameAr}/><input type="hidden" name="nameEn" value={definition.nameEn}/><input type="hidden" name="category" value={definition.family}/><input type="hidden" name="sortOrder" value={100+definition.source}/><input type="hidden" name="configuration" value={JSON.stringify(definition.configuration)}/><label className="label">{copy.plan}</label><select className="input" name="minimumPlan" defaultValue={row?.minimumPlan||definition.minimumPlan}>{["free","personal","pro","business"].map(value=><option key={value}>{value}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={row?.isActive??true}/>{copy.active}</label><button className="btn-primary w-full">{copy.save}</button>
      </form></details></div></div></article>})}</div></>;
}
