import type { ProfileTemplate } from "@popwam/db";
import { prisma } from "@popwam/db";
import { saveProfileTemplate } from "@/app/catalog-actions";
import { Badge } from "@/components/badge";
import { PageHeading } from "@/components/page-heading";

function TemplateFields({ template }: { template?: ProfileTemplate }) {
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{template && <input type="hidden" name="id" value={template.id}/>}<input className="input" name="nameEn" defaultValue={template?.nameEn} placeholder="English name" required/><input className="input" name="nameAr" defaultValue={template?.nameAr} placeholder="الاسم العربي" required/><input className="input" name="slug" defaultValue={template?.slug} placeholder="slug" required pattern="[a-z0-9-]+"/><select className="input" name="category" defaultValue={template?.category || "Minimal"}>{["Minimal","Professional","Creator","Elegant","Portfolio","Business"].map(value => <option key={value}>{value}</option>)}</select><select className="input" name="minimumPlan" defaultValue={template?.minimumPlan || "free"}>{["free","personal","pro","business"].map(value => <option key={value}>{value}</option>)}</select><input className="input" name="sortOrder" type="number" min="0" defaultValue={template?.sortOrder || 0}/><input className="input xl:col-span-2" name="previewImageUrl" defaultValue={template?.previewImageUrl || ""} placeholder="Preview image URL" dir="ltr"/><textarea className="input min-h-32 font-mono sm:col-span-2 xl:col-span-4" name="configuration" defaultValue={JSON.stringify(template?.configuration || { background: "#111313", panel: "#191c1c", accent: "#55d6a5", radius: "1.5rem", linkLayout: "list" }, null, 2)} dir="ltr"/><label className="flex items-center gap-2"><input type="checkbox" name="isActive" defaultChecked={template?.isActive ?? true}/>Active</label></div>;
}

export default async function TemplatesAdminPage() {
  const templates = await prisma.profileTemplate.findMany({ orderBy: [{ sortOrder: "asc" }, { nameEn: "asc" }] });
  return <><PageHeading eyebrow="Design catalog" title="Profile templates / قوالب الملفات" description="Templates are database-driven, plan-gated, previewable, and applied to the public page through a safe CSS token allowlist."/><details className="card mb-6 p-5"><summary className="cursor-pointer font-bold">Add template</summary><form action={saveProfileTemplate} className="mt-4"><TemplateFields/><button className="btn-primary mt-4">Save template</button></form></details><div className="space-y-3">{templates.map(template => <details className="card p-5" key={template.id}><summary className="flex cursor-pointer list-none justify-between gap-3"><span><strong>{template.nameEn} / {template.nameAr}</strong><span className="ms-3 text-xs text-slate-500">{template.category} · {template.minimumPlan}+</span></span><Badge value={template.isActive ? "ACTIVE" : "DISABLED"}/></summary><form action={saveProfileTemplate} className="mt-4 border-t border-white/10 pt-4"><TemplateFields template={template}/><button className="btn-secondary mt-4">Save changes</button></form></details>)}</div></>;
}
