import { ProfileFieldType,ProfileTheme,prisma } from "@popwam/db";
import { getPublicAppUrl } from "@popwam/shared";
import { isStorageEnabled } from "@popwam/storage";
import { requireUser } from "@/lib/session";
import { getUserEntitlements,getUserUsage } from "@/lib/plans";
import { getI18n } from "@/lib/i18n";
import { createProfileField,deleteProfileField,moveProfileField,updateProfile,updateProfileField } from "@/app/actions";
import { PageHeading } from "@/components/page-heading";
import { ImageField } from "@/components/image-field";
import { ThemePicker } from "@/components/theme-picker";
import { ProfileSaveForm } from "@/components/profile-save-form";
import { ArrowDown,ArrowUp,ExternalLink,Plus,Trash2 } from "lucide-react";

const visibility=["showAvatar","showCover","showDisplayName","showTitle","showBio","showPhone","showEmail","showWebsite","showLocation","showWhatsappBusiness","showWhatsappPrivate","showSocialLinks","showCustomFields","showUploadedFiles","showSaveContact"] as const;
const visibilityLabels:Record<(typeof visibility)[number],string>={showAvatar:"Avatar",showCover:"Cover",showDisplayName:"Display name",showTitle:"Job title",showBio:"Bio",showPhone:"Phone",showEmail:"Email",showWebsite:"Website",showLocation:"Location",showWhatsappBusiness:"WhatsApp Business",showWhatsappPrivate:"WhatsApp Private",showSocialLinks:"Social links",showCustomFields:"Custom fields",showUploadedFiles:"Uploaded files",showSaveContact:"Save contact button"};
const themeKeys:Record<ProfileTheme,"classicDark"|"classicLight"|"elegantDark"|"elegantLight"|"businessDark"|"businessLight">={CLASSIC_DARK:"classicDark",CLASSIC_LIGHT:"classicLight",ELEGANT_DARK:"elegantDark",ELEGANT_LIGHT:"elegantLight",BUSINESS_DARK:"businessDark",BUSINESS_LIGHT:"businessLight"};
export default async function ProfilePage(){const user=await requireUser();const [{dictionary:d},profile,{effective},usage]=await Promise.all([getI18n(),prisma.profile.findFirst({where:{userId:user.id,organizationId:null},include:{fields:{orderBy:{sortOrder:"asc"}}}}),getUserEntitlements(user.id),getUserUsage(user.id)]);if(!profile)return <div className="card p-8 text-amber-200">{d.errors.missingProfile}</div>;const publicPath=profile.slug?`/p/${profile.slug}`:`/p/id/${profile.id}`;const publicUrl=`${getPublicAppUrl()}${publicPath}`;const themeLabels=Object.fromEntries(Object.values(ProfileTheme).map(theme=>[theme,d.profile[themeKeys[theme]]])) as Record<ProfileTheme,string>;
  return <><PageHeading eyebrow="Public identity" title={d.nav.profile} description="Edit your profile in clear sections. Hidden items are removed from public HTML immediately." action={<a href={publicPath} target="_blank" className="btn-secondary">Open public profile <ExternalLink size={15}/></a>}/><div className="mb-5 rounded-2xl border border-brand-400/20 bg-brand-400/5 p-4"><p className="text-xs text-slate-500">Public URL</p><code className="mt-1 block break-all text-sm text-brand-400" dir="ltr">{publicUrl}</code></div>
  <ProfileSaveForm action={updateProfile} saveLabel={d.common.save}><input type="hidden" name="profileId" value={profile.id}/>
    <details open className="card p-5"><summary className="cursor-pointer text-lg font-bold">1. Basic information</summary><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="label">Display name</span><input className="input" name="displayName" required defaultValue={profile.displayName}/></label><label><span className="label">Public slug</span><input className="input" name="slug" defaultValue={profile.slug||""} disabled={!effective.allowCustomSlug}/>{!effective.allowCustomSlug&&<input type="hidden" name="slug" value={profile.slug||""}/>}</label><label><span className="label">Job title</span><input className="input" name="title" defaultValue={profile.title||""}/></label><label className="sm:col-span-2"><span className="label">Bio</span><textarea className="input min-h-28" name="bio" defaultValue={profile.bio||""}/></label><label className="flex items-center gap-2 sm:col-span-2"><input type="checkbox" name="isPublic" defaultChecked={profile.isPublic}/> Profile enabled</label><label className={`flex items-center gap-2 rounded-xl border p-4 sm:col-span-2 ${effective.allowInstallableProfiles?"border-white/10":"border-amber-400/20 text-amber-200"}`}><input type="checkbox" name="allowInstallable" defaultChecked={profile.allowInstallable} disabled={!effective.allowInstallableProfiles}/> {effective.allowInstallableProfiles?"Allow visitors to install this profile as an app":"Installable profiles are available on Personal plans and above"}</label></div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">2. Cover and avatar</summary><div className="mt-5 grid gap-5 sm:grid-cols-2"><ImageField type="avatar" initialUrl={profile.avatarUrl} initialKey={profile.avatarStorageKey} storageEnabled={isStorageEnabled()}/><ImageField type="cover" initialUrl={profile.coverUrl} initialKey={profile.coverStorageKey} storageEnabled={isStorageEnabled()}/></div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">3. Contact details</summary><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["email","Email"],["phone","Phone"],["whatsappBusiness","WhatsApp Business"],["whatsappPrivate","WhatsApp Private"],["website","Website"],["vcfUrl","vCard / VCF"],["locationText","Location"]].map(([key,label])=><label key={key}><span className="label">{label}</span><input className="input" name={key} defaultValue={String(profile[key as keyof typeof profile]||"")} dir={key==="locationText"?undefined:"ltr"}/></label>)}</div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">4. Social links</summary><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["facebook","Facebook"],["linkedin","LinkedIn"],["github","GitHub"],["tiktok","TikTok"]].map(([key,label])=><label key={key}><span className="label">{label}</span><input className="input" name={key} defaultValue={String(profile[key as keyof typeof profile]||"")} dir="ltr"/></label>)}</div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">5. Custom fields <span className="text-sm text-slate-500">({usage.customFields}/{effective.maxCustomFields})</span></summary><p className="mt-4 text-sm text-slate-400">Manage individual custom fields below this profile form.</p></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">6. Files</summary><div className="mt-4 flex items-center justify-between"><p className="text-sm text-slate-400">{usage.uploads}/{effective.maxUploads} uploaded files</p><a href="/dashboard/uploads" className="btn-secondary">Manage files</a></div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">7. Visibility</summary><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visibility.map(key=><label key={key} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3 text-sm"><span>{visibilityLabels[key]}</span><input type="checkbox" name={key} defaultChecked={profile[key]} className="size-5 accent-brand-400"/></label>)}</div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">8. Appearance</summary><div className="mt-5"><ThemePicker current={profile.theme} canChange={effective.allowThemes} labels={themeLabels}/></div></details>
    <details className="card p-5"><summary className="cursor-pointer text-lg font-bold">9. Public preview</summary><div className="mt-5"><div className="mx-auto h-[620px] max-w-sm overflow-hidden rounded-[2rem] border-8 border-slate-800 bg-white"><iframe title="Public profile preview" src={publicPath} className="size-full"/></div></div></details>
  </ProfileSaveForm>
  <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{d.profile.fields}</h2><span className="text-sm text-slate-500">{usage.customFields}/{effective.maxCustomFields}</span></div><details className="card mb-4 p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-bold"><Plus size={17}/>{d.profile.newField}</summary><form action={createProfileField} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="profileId" value={profile.id}/><label><span className="label">{d.profile.label}</span><input className="input" name="label" required/></label><label><span className="label">{d.profile.type}</span><select className="input" name="type">{Object.values(ProfileFieldType).map(type=><option key={type}>{type}</option>)}</select></label><label><span className="label">{d.profile.value}</span><input className="input" name="value" required/></label><label><span className="label">{d.profile.actionUrl}</span><input className="input" name="actionUrl" dir="ltr"/></label><input type="hidden" name="isVisible" value="on"/><button className="btn-primary sm:col-span-2 sm:justify-self-start">{d.common.create}</button></form></details><div className="space-y-3">{profile.fields.map(field=><details className="card p-5" key={field.id}><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><strong>{field.label}</strong><span className="text-sm text-slate-500">{field.isVisible?d.common.enabled:d.common.disabled}</span></div></summary><form action={updateProfileField} className="mt-5 grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-2"><input type="hidden" name="id" value={field.id}/><input className="input" name="label" defaultValue={field.label} required/><select className="input" name="type" defaultValue={field.type}>{Object.values(ProfileFieldType).map(type=><option key={type}>{type}</option>)}</select><input className="input" name="value" defaultValue={field.value} required/><input className="input" name="actionUrl" defaultValue={field.actionUrl||""}/><label className="flex items-center gap-2"><input type="checkbox" name="isVisible" defaultChecked={field.isVisible}/>{d.profile.visible}</label><button className="btn-primary">{d.common.save}</button></form><div className="mt-3 flex gap-2"><form action={moveProfileField}><input type="hidden" name="id" value={field.id}/><input type="hidden" name="direction" value="up"/><button className="btn-secondary"><ArrowUp size={14}/></button></form><form action={moveProfileField}><input type="hidden" name="id" value={field.id}/><input type="hidden" name="direction" value="down"/><button className="btn-secondary"><ArrowDown size={14}/></button></form><form action={deleteProfileField}><input type="hidden" name="id" value={field.id}/><button className="btn-danger"><Trash2 size={14}/>{d.common.delete}</button></form></div></details>)}</div></section></>;
}
