import Link from "next/link";
import { prisma } from "@popwam/db";
import { requireUser } from "@/lib/session";
import { getI18n } from "@/lib/i18n";
import { Activity, ArrowUpLeft, FileUp, MousePointer2, Nfc, QrCode, UserRound } from "lucide-react";

export const metadata = { title: "Dashboard" };
export default async function DashboardPage() {
  const [user,{locale,dictionary:d}] = await Promise.all([requireUser(),getI18n()]); const ar=locale==="ar"; const dashboardCopy=d.dashboard;
  const [cards,profile] = await Promise.all([prisma.card.findMany({where:{ownerId:user.id},orderBy:{assignedAt:"desc"},select:{id:true,serialNumber:true,publicSlug:true,cardStatus:true,openCount:true,lastOpenedAt:true,activeDestination:{select:{title:true,type:true}}}}),prisma.profile.findFirst({where:{userId:user.id,organizationId:null},select:{id:true}})]);
  const active=cards.filter(card=>card.cardStatus==="ACTIVE").length; const suspended=cards.filter(card=>["PAUSED","LOST","DISABLED"].includes(card.cardStatus)).length; const opens=cards.reduce((sum,card)=>sum+card.openCount,0); const lastOpened=[...cards].filter(card=>card.lastOpenedAt).sort((a,b)=>b.lastOpenedAt!.getTime()-a.lastOpenedAt!.getTime())[0];
  const stats=[[dashboardCopy.totalTags,cards.length,Nfc,"text-brand-400"],[dashboardCopy.activeTags,active,Activity,"text-emerald-300"],[dashboardCopy.suspendedTags,suspended,Nfc,"text-amber-300"],[dashboardCopy.totalScans,opens,MousePointer2,"text-violet-300"]] as const;
  return <><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-400">{ar?"مساحة العمل":"Workspace"}</p><h1 className="mt-2 text-3xl font-black">{ar?`مرحبًا${user.name?`، ${user.name.split(" ")[0]}`:""}`:`Hello${user.name?`, ${user.name.split(" ")[0]}`:""}`}</h1><p className="mt-2 text-slate-400">{ar?"نظرة مباشرة على كروتك وملفاتك وتفاعل الزوار.":"A live view of your cards, profiles and engagement."}</p></div><Link href="/activate/scan" className="btn-primary"><QrCode size={17}/>{ar?"إضافة أو تفعيل كارت":"Add or activate a card"}</Link></div><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,Icon,color])=><div className="card p-5" key={label}><div className="flex items-center justify-between"><p className="text-sm text-slate-400">{label}</p><Icon size={20} className={color}/></div><p className="mt-5 text-3xl font-black">{value}</p></div>)}</section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.07] p-5"><div><h2 className="font-bold">{ar?"كروتي":"My cards"}</h2><p className="mt-1 text-sm text-slate-500">{lastOpened?`${ar?"آخر كارت فُتح":"Last opened"}: ${lastOpened.serialNumber}`:(ar?"لا توجد عمليات فتح بعد":"No opens yet")}</p></div><Link href="/dashboard/tags" className="text-sm text-brand-400">{ar?"إدارة الكل":"Manage all"}</Link></div>{cards.length?<div className="divide-y divide-white/[.06]">{cards.slice(0,6).map(card=><div className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto] sm:items-center" key={card.id}><div><p className="font-mono text-sm" dir="ltr">{card.serialNumber}</p><p className="mt-1 text-xs text-slate-500">{card.activeDestination?.title||card.activeDestination?.type||(ar?"لا توجد وجهة نشطة":"No active destination")}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${card.cardStatus==="ACTIVE"?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-200"}`}>{card.cardStatus}</span><p className="text-sm text-slate-400">{card.openCount} {ar?"فتح":"opens"}</p></div>)}</div>:<div className="p-10 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-400/10 text-brand-400"><Nfc size={30}/></div><h3 className="mt-5 text-xl font-black">{ar?"لا يوجد لديك كروت حتى الآن":"You do not have any cards yet"}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-7 text-slate-400">{ar?"ابدأ بمسح QR الموجود مع كارت POPWAM واتبع خطوات التحقق.":"Scan the QR supplied with your POPWAM card and follow verification."}</p><div className="mt-6 flex flex-wrap justify-center gap-2"><Link href="/activate/scan" className="btn-primary">{ar?"تفعيل كارت جديد":"Activate a new card"}</Link><Link href="/activate/scan" className="btn-secondary"><QrCode size={16}/>{ar?"مسح QR":"Scan QR"}</Link><Link href="/#how" className="btn-secondary">{ar?"معرفة كيف يعمل":"How it works"}</Link></div></div>}</div>
      <div className="card p-5"><h2 className="font-bold">{ar?"إجراءات سريعة":"Quick actions"}</h2><div className="mt-4 grid gap-2"><Link href={profile?"/dashboard/profile":"/dashboard/profiles"} className="flex items-center justify-between rounded-xl border border-white/[.08] p-4 hover:bg-white/[.04]"><span className="flex items-center gap-3"><UserRound size={18} className="text-brand-400"/>{ar?"إنشاء Profile":"Create profile"}</span><ArrowUpLeft className="directional-icon" size={16}/></Link><Link href="/dashboard/uploads" className="flex items-center justify-between rounded-xl border border-white/[.08] p-4 hover:bg-white/[.04]"><span className="flex items-center gap-3"><FileUp size={18} className="text-brand-400"/>{ar?"رفع ملف":"Upload file"}</span><ArrowUpLeft className="directional-icon" size={16}/></Link><Link href="/activate/scan" className="flex items-center justify-between rounded-xl border border-white/[.08] p-4 hover:bg-white/[.04]"><span className="flex items-center gap-3"><QrCode size={18} className="text-brand-400"/>{ar?"مسح QR":"Scan QR"}</span><ArrowUpLeft className="directional-icon" size={16}/></Link></div></div></section></>;
}
