import Link from "next/link";
import { prisma } from "@popwam/db";
import { PageHeading } from "@/components/page-heading";
import { Badge } from "@/components/badge";
import { CopyUrl } from "@/components/copy-url";
import { ConfirmSubmit } from "@/components/confirm-submit";
import { getPermanentCardUrl } from "@popwam/shared";
import { unassignCard, updateCardState } from "@/app/business-actions";
import { getI18n } from "@/lib/i18n";

export default async function AdminCardsPage(){
  const [{locale,dictionary:d},cards]=await Promise.all([getI18n(),prisma.card.findMany({include:{batch:true,owner:true,organization:true,profile:true,activeDestination:true},orderBy:{createdAt:"desc"},take:1000})]);
  const copy=d.adminPages.cards;const common=d.adminPages.common;const dateLocale=locale==="ar"?"ar-EG":"en-US";
  const stateActions=[["pause",0],["restore",1],["lost",2],["disable",3],["archive",4]] as const;
  return <><PageHeading eyebrow={copy.eyebrow} title={copy.title} description={copy.description} action={<div className="flex gap-2"><Link className="btn-secondary" href="/admin/cards/batches">{copy.batches}</Link><Link className="btn-primary" href="/admin/cards/new">{copy.new}</Link></div>}/><div className="card overflow-x-auto"><table className="w-full min-w-[1800px] text-sm"><thead className="text-xs text-slate-500"><tr>{copy.headers.map(x=><th className="p-3 text-start" key={x}>{x}</th>)}</tr></thead><tbody>{cards.map(card=>{const url=getPermanentCardUrl(card.publicSlug);return <tr className="border-t border-white/10 align-top" key={card.id}><td className="p-3 font-mono" dir="ltr">{card.serialNumber}</td><td className="p-3"><Badge value={card.cardType}/></td><td className="p-3">{card.batch?.name||copy.legacy}</td><td className="p-3"><div className="flex items-center gap-2" dir="ltr"><a className="max-w-56 truncate text-brand-400" href={url} target="_blank">{url}</a><CopyUrl value={url}/></div></td><td className="p-3"><Badge value={card.assignmentStatus}/></td><td className="p-3"><Badge value={card.cardStatus}/></td><td className="p-3" dir="ltr">{card.owner?.email||common.notAvailable}</td><td className="p-3">{card.organization?.name||common.notAvailable}</td><td className="p-3">{card.profile?.displayName||common.notAvailable}</td><td className="p-3">{card.activeDestination?.title||common.notAvailable}</td><td className="p-3">{card.openCount}</td><td className="p-3">{card.createdAt.toLocaleDateString(dateLocale)}</td><td className="p-3">{card.assignedAt?.toLocaleDateString(dateLocale)||common.notAvailable}</td><td className="p-3"><div className="flex max-w-xl flex-wrap gap-2"><Link className="btn-secondary px-3 py-1.5" href={`/admin/cards/${card.id}`}>{common.view}</Link><Link className="btn-secondary px-3 py-1.5" href={`/admin/cards/${card.id}`}>{copy.nfcQr}</Link><form action={`/api/admin/cards/${card.id}/activation-qr`} method="post"><button className="btn-secondary px-3 py-1.5" disabled={Boolean(card.ownerId)} title={copy.rotateSecret}>{copy.activationQr}</button></form><Link className="btn-secondary px-3 py-1.5" href={`/admin/cards/${card.id}`}>{card.ownerId?copy.reassign:copy.assign}</Link>{card.ownerId&&<form action={unassignCard}><input type="hidden" name="cardId" value={card.id}/><ConfirmSubmit className="btn-secondary px-3 py-1.5" message={copy.unassignConfirm}>{copy.unassign}</ConfirmSubmit></form>}{stateActions.map(([action,index])=><form action={updateCardState} key={action}><input type="hidden" name="cardId" value={card.id}/><input type="hidden" name="cardAction" value={action}/><ConfirmSubmit className="btn-secondary px-3 py-1.5" message={`${copy.actions[index]}?`}>{copy.actions[index]}</ConfirmSubmit></form>)}</div></td></tr>})}</tbody></table>{!cards.length&&<p className="p-6 text-slate-500">{copy.empty}</p>}</div></>;
}
