import Link from "next/link";
import {prisma} from "@popwam/db";
import {isStorageEnabled} from "@popwam/storage";
import {saveOnboardingStep} from "@/app/onboarding-actions";
import {ImageField} from "@/components/image-field";
import {PageHeading} from "@/components/page-heading";
import {ProfileAvatar} from "@/components/profile-avatar";
import {ONBOARDING_STEPS} from "@/lib/onboarding";
import {requireUser} from "@/lib/session";
import {getUserEntitlements} from "@/lib/plans";
import {templateAllowed} from "@/lib/virtual-cards";
import {appleWalletConfigured,googleWalletConfigured} from "@/lib/wallet";

export default async function OnboardingPage({searchParams}:{searchParams:Promise<{step?:string}>}){const user=await requireUser();const {step:requested}=await searchParams;const [progress,card,cards,platforms,templates,entitlements]=await Promise.all([prisma.onboardingProgress.findUnique({where:{userId:user.id}}),prisma.virtualCard.findFirst({where:{userId:user.id,isDefault:true},include:{profile:true}}),prisma.virtualCard.findMany({where:{userId:user.id,status:"ACTIVE"},select:{id:true,name:true,isDefault:true}}),prisma.linkPlatform.findMany({where:{isActive:true},orderBy:[{sortOrder:"asc"},{nameEn:"asc"}]}),prisma.profileTemplate.findMany({where:{isActive:true},orderBy:{sortOrder:"asc"}}),getUserEntitlements(user.id)]);if(!card)return <div className="card p-6">Default virtual card is missing. Run the safe account repair.</div>;const saved=progress?.data&&typeof progress.data==="object"&&!Array.isArray(progress.data)?progress.data as Record<string,unknown>:{};const step=Math.min(ONBOARDING_STEPS,Math.max(1,Number(requested||progress?.currentStep||1)));const input=(name:string,label:string,options?:{required?:boolean;type?:string;dir?:"ltr"})=><label><span className="label">{label}</span><input className="input" name={name} type={options?.type} dir={options?.dir} required={options?.required} defaultValue={String(saved[name]||"")}/></label>;const checkbox=(name:string,label:string,value:boolean)=><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3"><input type="checkbox" name={name} defaultChecked={value}/>{label}</label>;const optional=![1,5,6,7,10,11,12,14,15].includes(step);return <main className="mx-auto min-h-screen max-w-3xl px-4 py-10"><PageHeading eyebrow={`Step ${step} of ${ONBOARDING_STEPS}`} title="Build your POPWAM identity" description="Every step is saved. Optional steps can be skipped and you can resume from the dashboard."/><div className="mb-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-brand-400" style={{width:`${step/ONBOARDING_STEPS*100}%`}}/></div><form action={saveOnboardingStep} className="card grid gap-5 p-6"><input type="hidden" name="step" value={step}/>
{step===1&&<><h2 className="text-xl font-black">What is your name? / ما اسمك؟</h2>{input("displayName","Display name",{required:true})}{input("preferredName","Preferred name")}</>}
{step===2&&<><h2 className="text-xl font-black">What do you do? / ماذا تعمل؟</h2>{input("jobTitle","Job title")}{input("profession","Profession or category")}</>}
{step===3&&<><h2 className="text-xl font-black">Where do you work? / أين تعمل؟</h2>{input("company","Company or business name")}<label><span className="label">Employment type</span><select className="input" name="employmentType" defaultValue={String(saved.employmentType||"EMPLOYEE")}><option>EMPLOYEE</option><option>FREELANCER</option><option>FOUNDER</option><option>STUDENT</option><option>OTHER</option></select></label>{input("organization","Optional organization")}</>}
{step===4&&<><h2 className="text-xl font-black">Do you have a website? / هل لديك موقع؟</h2>{input("website","Website",{type:"url",dir:"ltr"})}</>}
{step===5&&<><h2 className="text-xl font-black">Choose an avatar / اختر صورة</h2><div className="flex items-center gap-4"><ProfileAvatar name={card.name} email={user.email} imageUrl={card.profile.avatarUrl} size={72}/><p className="text-sm text-slate-500">Uploaded image, generated avatar, or initials.</p></div><ImageField type="avatar" initialUrl={card.profile.avatarUrl} initialKey={card.profile.avatarStorageKey} storageEnabled={isStorageEnabled()}/><div className="grid gap-3 sm:grid-cols-3">{[["UPLOADED","Uploaded"],["GENERATED","Generated"],["INITIALS","Initials"]].map(([value,label])=><label className="rounded-xl border border-white/10 p-3" key={value}><input type="radio" name="avatarKind" value={value} defaultChecked={(card.avatarKind||"INITIALS")===value}/> {label}</label>)}</div>{input("avatarValue","Generated avatar key (optional)")}</>}
{step===6&&<><h2 className="text-xl font-black">Choose profile type / اختر نوع الملف</h2><div className="grid gap-3 sm:grid-cols-2">{(entitlements.effective.availableProfileTypes as string[]).map(type=><label className="rounded-xl border border-white/10 p-4" key={type}><input type="radio" name="profileType" value={type} defaultChecked={card.type===type} required/> {type}</label>)}</div></>}
{step===7&&<><h2 className="text-xl font-black">Choose template / اختر القالب</h2><div className="grid gap-3 sm:grid-cols-2">{templates.map(template=>{const allowed=templateAllowed(entitlements.plan.slug,template.minimumPlan);return <label className={`rounded-xl border p-4 ${allowed?"border-white/10":"border-amber-400/20 text-slate-500"}`} key={template.id}><input type="radio" name="templateId" value={template.id} disabled={!allowed} defaultChecked={card.themeId===template.id} required/> {template.nameEn} / {template.nameAr}<small className="block">{template.minimumPlan.toUpperCase()}+</small></label>})}</div></>}
{step===8&&<><h2 className="text-xl font-black">Core contact data / بيانات الاتصال</h2>{input("phone","Phone",{dir:"ltr"})}{input("email","Email",{type:"email",dir:"ltr"})}{input("whatsapp","WhatsApp",{dir:"ltr"})}{input("website","Website",{type:"url",dir:"ltr"})}</>}
{step===9&&<><h2 className="text-xl font-black">Add a platform / أضف منصة</h2><label><span className="label">Platform</span><select className="input" name="linkPlatformId"><option value="">Choose platform</option>{platforms.map(platform=><option value={platform.id} key={platform.id}>{platform.nameEn} / {platform.nameAr}</option>)}</select></label>{input("url","Username, phone, or URL",{dir:"ltr"})}</>}
{step===10&&<><h2 className="text-xl font-black">Choose visibility / اختر الظهور</h2><div className="grid gap-3 sm:grid-cols-2">{checkbox("showAvatar","Avatar",card.profile.showAvatar)}{checkbox("showCover","Cover",card.profile.showCover)}{checkbox("showPhone","Phone",card.profile.showPhone)}{checkbox("showEmail","Email",card.profile.showEmail)}{checkbox("showWebsite","Website",card.profile.showWebsite)}{checkbox("showSocialLinks","Social links",card.profile.showSocialLinks)}{checkbox("showUploadedFiles","Attachments",card.profile.showUploadedFiles)}</div></>}
{step===11&&<><h2 className="text-xl font-black">Choose language / اختر اللغة</h2><select className="input" name="language" defaultValue={card.profile.primaryLanguage}><option value="ar">العربية فقط</option><option value="en">English only</option><option value="both">العربية وEnglish</option></select></>}
{step===12&&<><h2 className="text-xl font-black">Installable profile / تثبيت الملف كتطبيق</h2>{entitlements.effective.allowInstallableProfiles?checkbox("allowInstallable","Allow visitors to install this profile",card.profile.allowInstallable):<div className="rounded-xl border border-amber-400/20 bg-amber-400/10 p-4 text-amber-200">Available on Personal plans and above.</div>}</>}
{step===13&&<><h2 className="text-xl font-black">Wallet / المحفظة</h2><p className="text-sm text-slate-400">Google Wallet: {googleWalletConfigured()?"Ready":"Not configured"} · Apple Wallet: {appleWalletConfigured()?"Ready":"Not configured"}</p>{(googleWalletConfigured()||appleWalletConfigured())&&checkbox("walletRequested","Prepare Wallet access for this profile",Boolean(saved.walletRequested))}</>}
{step===14&&<><h2 className="text-xl font-black">Choose active profile / اختر الملف النشط</h2><select className="input" name="activeVirtualCardId" defaultValue={card.id}>{cards.map(item=><option value={item.id} key={item.id}>{item.name}{item.isDefault?" · Current":""}</option>)}</select></>}
{step===15&&<><h2 className="text-xl font-black">You are ready / أنت جاهز</h2><p className="leading-8 text-slate-300">Your identity, privacy, language, template, and active profile choices are saved. You can change any of them later from My Profiles.</p></>}
<div className="flex flex-wrap items-center justify-between gap-3">{step>1?<Link className="btn-secondary" href={`/onboarding?step=${step-1}`}>Back / السابق</Link>:<span/>}<div className="flex gap-2">{optional&&<button className="btn-secondary" name="skip" value="true">Skip / تخطي</button>}<button className="btn-primary">{step===ONBOARDING_STEPS?"Finish / إنهاء":"Save and continue / حفظ ومتابعة"}</button></div></div></form></main>}
