import Link from "next/link";
import { prisma } from "@popwam/db";
import { AdminCreateUserForm } from "@/components/admin-create-user-form";
import { PageHeading } from "@/components/page-heading";
import { Badge } from "@/components/badge";
import { getI18n } from "@/lib/i18n";
import { ArrowUpRight, Plus } from "lucide-react";

export const metadata = { title: "Admin users" };
export default async function AdminUsersPage() {
  const { locale } = await getI18n();
  const users = await prisma.user.findMany({ include: { accounts: { select: { provider: true }, take: 1 }, subscriptions: { where: { status: "ACTIVE" }, include: { plan: true }, take: 1 }, _count: { select: { profiles: true, destinations: true, profileFields: true, ownedTags: true, uploads: true } } }, orderBy: { createdAt: "desc" } });
  return <><PageHeading eyebrow="Administration" title="Users" description="Account state, provider, plan, resource usage, and direct management access."/><details className="card mb-6 p-5"><summary className="flex cursor-pointer list-none items-center gap-2 font-bold"><Plus size={18} className="text-brand-400"/> Create user</summary><AdminCreateUserForm locale={locale}/></details><div className="card overflow-x-auto"><table className="w-full min-w-[1150px] text-start text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">User</th><th className="p-4">Role / status</th><th className="p-4">Provider</th><th className="p-4">Plan</th><th className="p-4">Profiles</th><th className="p-4">Links</th><th className="p-4">Fields</th><th className="p-4">Tags</th><th className="p-4">Uploads</th><th className="p-4">Created</th><th className="p-4">Last login</th><th className="p-4"></th></tr></thead><tbody className="divide-y divide-white/10">{users.map(user => <tr key={user.id}><td className="p-4"><p className="font-semibold">{user.name || "—"}</p><p className="mt-1 text-xs text-slate-500">{user.email}</p></td><td className="p-4"><div className="flex gap-1"><Badge value={user.role}/><Badge value={user.status}/></div></td><td className="p-4">{user.accounts[0]?.provider || (user.passwordHash ? "credentials" : "—")}</td><td className="p-4">{user.subscriptions[0]?.plan.name || "FREE"}</td><td className="p-4">{user._count.profiles}</td><td className="p-4">{user._count.destinations}</td><td className="p-4">{user._count.profileFields}</td><td className="p-4">{user._count.ownedTags}</td><td className="p-4">{user._count.uploads}</td><td className="p-4 text-xs text-slate-500">{user.createdAt.toLocaleDateString(locale)}</td><td className="p-4 text-xs text-slate-500">{user.lastLoginAt?.toLocaleString(locale) || "—"}</td><td className="p-4"><Link href={`/admin/users/${user.id}`} className="btn-secondary">Manage <ArrowUpRight size={14}/></Link></td></tr>)}</tbody></table></div></>;
}
