import {NextResponse} from "next/server";
import {prisma,OtpPurpose} from "@popwam/db";
import {cookies} from "next/headers";
import {normalizePhone} from "@/lib/phone";
import {createOtpCode,hashOtp,hashPhone} from "@/lib/otp-crypto";
import {getSmsProvider} from "@/lib/sms";
import {ACTIVATION_COOKIE,OTP_COOKIE,secureCookie} from "@/lib/activation-session";
import {hashActivationToken} from "@/lib/card-tokens";

export async function POST(request:Request){const body=await request.json().catch(()=>({}));const normalized=normalizePhone(String(body.phone||""));if(!normalized.valid)return NextResponse.json({ok:false,error:normalized.error},{status:400});const purpose=body.purpose==="ACTIVATION"?OtpPurpose.ACTIVATION:OtpPurpose.LOGIN;let claimSessionId:string|null=null;if(purpose==="ACTIVATION"){const claimToken=(await cookies()).get(ACTIVATION_COOKIE)?.value;const claim=claimToken?await prisma.activationClaimSession.findUnique({where:{sessionTokenHash:hashActivationToken(claimToken)}}):null;if(!claim||claim.status!=="PENDING_OTP"||claim.expiresAt<=new Date())return NextResponse.json({ok:false,error:"SESSION_EXPIRED"},{status:400});claimSessionId=claim.id;}
  const now=new Date();const cooldown=Math.max(30,Number(process.env.OTP_SEND_COOLDOWN_SECONDS||60));const latest=await prisma.otpChallenge.findFirst({where:{phone:normalized.e164},orderBy:{createdAt:"desc"},select:{createdAt:true}});if(latest&&latest.createdAt>new Date(now.getTime()-cooldown*1000))return NextResponse.json({ok:false,error:"OTP_COOLDOWN"},{status:429});const phoneHash=hashPhone(normalized.e164);const dayStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const dailyLimit=Math.max(1,Number(process.env.OTP_DAILY_SEND_LIMIT||10));if(await prisma.otpSendLog.count({where:{phoneHash,createdAt:{gte:dayStart}}})>=dailyLimit)return NextResponse.json({ok:false,error:"OTP_LIMIT_REACHED"},{status:429});
  const code=createOtpCode();const expiryMinutes=Math.min(5,Math.max(3,Number(process.env.OTP_EXPIRY_MINUTES||5)));const provider=getSmsProvider();const challenge=await prisma.otpChallenge.create({data:{phone:normalized.e164,purpose,claimSessionId,otpHash:hashOtp(normalized.e164,code),expiresAt:new Date(now.getTime()+expiryMinutes*60_000),maxAttempts:Math.max(3,Number(process.env.OTP_MAX_ATTEMPTS||5)),provider:provider.name}});let delivery:{status:"SENT"|"FAILED";provider:string;messageId?:string};try{delivery=await provider.sendOtp({to:normalized.e164,code,expiresMinutes:expiryMinutes,locale:body.locale==="en"?"en":"ar"});}catch{delivery={status:"FAILED",provider:provider.name};}await prisma.$transaction([prisma.otpChallenge.update({where:{id:challenge.id},data:{deliveryStatus:delivery.status,providerMessageId:delivery.messageId}}),prisma.otpSendLog.create({data:{phoneHash,purpose,status:delivery.status,provider:provider.name}})]);if(delivery.status!=="SENT")return NextResponse.json({ok:false,error:"OTP_SEND_FAILED"},{status:503});const response=NextResponse.json({ok:true,maskedPhone:`${normalized.e164.slice(0,4)}••••${normalized.e164.slice(-3)}`,...(process.env.NODE_ENV!=="production"&&provider.name==="development"?{developmentCode:code}:{})});response.cookies.set(OTP_COOKIE,challenge.id,{...secureCookie,maxAge:expiryMinutes*60});return response;}
