import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {prisma} from "@popwam/db";
import {OTP_COOKIE,secureCookie} from "@/lib/activation-session";
import {otpMatches,hashPhone} from "@/lib/otp-crypto";
import {createOpaqueToken,hashActivationToken} from "@/lib/card-tokens";
import {ensureUserDefaultsInTransaction} from "@/lib/ensure-user";
import {normalizePhone} from "@/lib/phone";

export async function POST(request:Request){const code=String((await request.json().catch(()=>({}))).code||"").replace(/\D/g,"");const challengeId=(await cookies()).get(OTP_COOKIE)?.value;const generic=()=>NextResponse.json({ok:false,error:"OTP_INVALID"},{status:400});if(!challengeId||code.length!==6)return generic();try{const result=await prisma.$transaction(async tx=>{const challenge=await tx.otpChallenge.findUnique({where:{id:challengeId},include:{claimSession:{include:{card:{select:{publicSlug:true}}}}}});if(!challenge||challenge.consumedAt||challenge.deliveryStatus!=="SENT"||challenge.expiresAt<=new Date()||challenge.attempts>=challenge.maxAttempts)return null;if(!otpMatches(challenge.phone,code,challenge.otpHash)){await tx.otpChallenge.update({where:{id:challenge.id},data:{attempts:{increment:1}}});return null;}let user=await tx.user.findFirst({where:{OR:[{phoneE164:challenge.phone},{phone:challenge.phone}]}});if(user?.status!=="ACTIVE"&&user)return null;if(!user){const suffix=hashPhone(challenge.phone).slice(0,24);const parsed=normalizePhone(challenge.phone);if(!parsed.valid)return null;user=await tx.user.create({data:{email:`phone-${suffix}@otp.popwam.invalid`,phone:parsed.e164,phoneE164:parsed.e164,phoneCountryIso2:parsed.countryIso2,phoneCallingCode:parsed.callingCode,phoneVerifiedAt:new Date(),name:parsed.e164}});await ensureUserDefaultsInTransaction(tx,user.id);}else{await tx.user.update({where:{id:user.id},data:{phoneE164:user.phoneE164||challenge.phone,phoneVerifiedAt:user.phoneVerifiedAt||new Date(),lastLoginAt:new Date()}});await ensureUserDefaultsInTransaction(tx,user.id);}await tx.otpChallenge.update({where:{id:challenge.id},data:{consumedAt:new Date(),deliveryStatus:"VERIFIED"}});if(challenge.claimSessionId)await tx.activationClaimSession.update({where:{id:challenge.claimSessionId},data:{userId:user.id,phone:challenge.phone,status:"VERIFIED",verifiedAt:new Date()}});const ticket=createOpaqueToken();await tx.authTicket.create({data:{tokenHash:hashActivationToken(ticket),userId:user.id,expiresAt:new Date(Date.now()+2*60_000)}});const passkeyCount=await tx.passkeyCredential.count({where:{userId:user.id,revokedAt:null}});return{ticket,passkeyRecommended:passkeyCount===0,nextUrl:challenge.claimSession?.card?`/activate/card/${challenge.claimSession.card.publicSlug}/confirm`:"/dashboard"};},{isolationLevel:"Serializable"});if(!result)return generic();const response=NextResponse.json({ok:true,...result});response.cookies.set(OTP_COOKIE,"",{...secureCookie,maxAge:0});return response;}catch(error){console.error("OTP verification failed",{operation:"otp.verify",error:error instanceof Error?error.name:"unknown"});return generic();}}
