import "server-only";
import {createHash,randomBytes} from "node:crypto";
import type {ConnectedAccountProvider} from "@popwam/db";
import {PRODUCTION_APP_URL} from "@popwam/shared";

export type ProviderKey="meta"|"tiktok"|"google"|"linkedin"|"github";
export type ProviderProfile={id:string;displayName?:string;username?:string;avatarUrl?:string;profileUrl?:string;accountType?:string;metadata?:Record<string,unknown>;followersCount?:bigint};
type ProviderConfig={key:ProviderKey;db:ConnectedAccountProvider;enabledEnv:string;clientIdEnv:string;clientSecretEnv:string;redirectEnv:string;authorizeUrl:string;tokenUrl:string;scopes:string[];pkce:boolean};
export const providerConfigs:Record<ProviderKey,ProviderConfig>={
  meta:{key:"meta",db:"META",enabledEnv:"META_ENABLED",clientIdEnv:"META_APP_ID",clientSecretEnv:"META_APP_SECRET",redirectEnv:"META_REDIRECT_URI",authorizeUrl:"https://www.facebook.com/v23.0/dialog/oauth",tokenUrl:"https://graph.facebook.com/v23.0/oauth/access_token",scopes:["public_profile","pages_show_list","instagram_basic","threads_basic","whatsapp_business_management"],pkce:false},
  tiktok:{key:"tiktok",db:"TIKTOK",enabledEnv:"TIKTOK_ENABLED",clientIdEnv:"TIKTOK_CLIENT_KEY",clientSecretEnv:"TIKTOK_CLIENT_SECRET",redirectEnv:"TIKTOK_REDIRECT_URI",authorizeUrl:"https://www.tiktok.com/v2/auth/authorize/",tokenUrl:"https://open.tiktokapis.com/v2/oauth/token/",scopes:["user.info.basic","user.info.profile","user.info.stats"],pkce:true},
  google:{key:"google",db:"GOOGLE",enabledEnv:"GOOGLE_CONNECTED_ENABLED",clientIdEnv:"GOOGLE_CONNECTED_CLIENT_ID",clientSecretEnv:"GOOGLE_CONNECTED_CLIENT_SECRET",redirectEnv:"GOOGLE_CONNECTED_REDIRECT_URI",authorizeUrl:"https://accounts.google.com/o/oauth2/v2/auth",tokenUrl:"https://oauth2.googleapis.com/token",scopes:["openid","profile"],pkce:true},
  linkedin:{key:"linkedin",db:"LINKEDIN",enabledEnv:"LINKEDIN_ENABLED",clientIdEnv:"LINKEDIN_CLIENT_ID",clientSecretEnv:"LINKEDIN_CLIENT_SECRET",redirectEnv:"LINKEDIN_REDIRECT_URI",authorizeUrl:"https://www.linkedin.com/oauth/v2/authorization",tokenUrl:"https://www.linkedin.com/oauth/v2/accessToken",scopes:["openid","profile"],pkce:true},
  github:{key:"github",db:"GITHUB",enabledEnv:"GITHUB_ENABLED",clientIdEnv:"GITHUB_CLIENT_ID",clientSecretEnv:"GITHUB_CLIENT_SECRET",redirectEnv:"GITHUB_REDIRECT_URI",authorizeUrl:"https://github.com/login/oauth/authorize",tokenUrl:"https://github.com/login/oauth/access_token",scopes:["read:user"],pkce:true},
};
export const META_CALLBACK_URL=`${PRODUCTION_APP_URL}/api/integrations/meta/callback`;
export function isProviderKey(value:string):value is ProviderKey{return value in providerConfigs}
export function providerStatus(key:ProviderKey){const config=providerConfigs[key];const enabled=process.env[config.enabledEnv]==="true";const configured=Boolean(process.env[config.clientIdEnv]&&process.env[config.clientSecretEnv]&&process.env[config.redirectEnv]&&process.env.INTEGRATION_TOKEN_ENCRYPTION_KEY);return{enabled,configured,redirectUri:process.env[config.redirectEnv]||""}}
function assertCallbackUrl(key:ProviderKey,redirectUri:string){if(key==="meta"&&process.env.NODE_ENV==="production"&&redirectUri!==META_CALLBACK_URL)throw new Error("CALLBACK_URL_MISMATCH")}
export function createOAuthRequest(key:ProviderKey,state:string){const config=providerConfigs[key];const status=providerStatus(key);if(!process.env.INTEGRATION_TOKEN_ENCRYPTION_KEY)throw new Error("INTEGRATION_TOKEN_ENCRYPTION_KEY_REQUIRED");if(!status.enabled||!status.configured)throw new Error("PROVIDER_DISABLED");assertCallbackUrl(key,status.redirectUri);const verifier=config.pkce?randomBytes(48).toString("base64url"):undefined;const params=new URLSearchParams({client_id:process.env[config.clientIdEnv]!,redirect_uri:status.redirectUri,response_type:"code",scope:config.scopes.join(key==="tiktok"?",":" "),state});if(verifier){params.set("code_challenge",createHash("sha256").update(verifier).digest("base64url"));params.set("code_challenge_method","S256")}if(key==="google")params.set("access_type","offline");return{authorizeUrl:`${config.authorizeUrl}?${params}`,verifier}}
export async function exchangeOAuthCode(key:ProviderKey,code:string,verifier?:string|null){const config=providerConfigs[key];const status=providerStatus(key);if(!process.env.INTEGRATION_TOKEN_ENCRYPTION_KEY)throw new Error("INTEGRATION_TOKEN_ENCRYPTION_KEY_REQUIRED");if(!status.enabled||!status.configured)throw new Error("PROVIDER_DISABLED");assertCallbackUrl(key,status.redirectUri);const body=new URLSearchParams({client_id:process.env[config.clientIdEnv]!,client_secret:process.env[config.clientSecretEnv]!,code,redirect_uri:status.redirectUri,grant_type:"authorization_code"});if(verifier)body.set("code_verifier",verifier);const response=await fetch(config.tokenUrl,{method:"POST",headers:{accept:"application/json","content-type":"application/x-www-form-urlencoded"},body,cache:"no-store",signal:AbortSignal.timeout(10_000)});const result=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok||typeof result.access_token!=="string")throw new Error("TOKEN_EXCHANGE_FAILED");return{accessToken:result.access_token,refreshToken:typeof result.refresh_token==="string"?result.refresh_token:undefined,expiresIn:typeof result.expires_in==="number"?result.expires_in:undefined,scope:typeof result.scope==="string"?result.scope.split(/[ ,]+/):config.scopes}}
export async function fetchProviderProfile(key:ProviderKey,accessToken:string):Promise<ProviderProfile>{const endpoints:Record<ProviderKey,string>={meta:"https://graph.facebook.com/v23.0/me?fields=id,name,picture",tiktok:"https://open.tiktokapis.com/v2/user/info/?fields=open_id,avatar_url,display_name,username,bio_description,profile_deep_link,is_verified,follower_count,following_count,likes_count,video_count",google:"https://openidconnect.googleapis.com/v1/userinfo",linkedin:"https://api.linkedin.com/v2/userinfo",github:"https://api.github.com/user"};const response=await fetch(endpoints[key],{headers:{authorization:`Bearer ${accessToken}`,accept:"application/json"},cache:"no-store",signal:AbortSignal.timeout(10_000)});const raw=await response.json().catch(()=>({})) as Record<string,any>;if(!response.ok)throw new Error("PROFILE_FETCH_FAILED");const value=key==="tiktok"?(raw.data?.user||raw.data||raw):raw;const id=String(value.id||value.sub||value.open_id||"");if(!id)throw new Error("PROFILE_ID_MISSING");return{id,displayName:value.name||value.display_name||value.localizedFirstName,username:value.login||value.username,avatarUrl:value.picture?.data?.url||value.picture||value.avatar_url||value.avatar_url_100,profileUrl:value.html_url||value.profile_deep_link,metadata:{bio:value.bio||value.bio_description,verified:value.verified||value.is_verified,followingCount:value.following_count,likesCount:value.likes_count,videoCount:value.video_count},followersCount:value.followers?BigInt(value.followers):value.follower_count?BigInt(value.follower_count):undefined}}
