import "server-only";
import {createHmac,randomBytes,timingSafeEqual} from "node:crypto";
import {Prisma,prisma,type SystemRole} from "@popwam/db";

const enc=(value:string|Buffer)=>Buffer.from(value).toString("base64url");
const secret=()=>{const value=process.env.MOBILE_TOKEN_SECRET||process.env.NEXTAUTH_SECRET;if(!value||value.length<32)throw new Error("MOBILE_TOKEN_SECRET_REQUIRED");return value};
const digest=(value:string)=>createHmac("sha256",secret()).update(value).digest("base64url");
export type MobileClaims={sub:string;role:SystemRole;exp:number;iat:number;jti:string;typ:"access"};

export function createMobileAccessToken(user:{id:string;role:SystemRole}){const now=Math.floor(Date.now()/1000);const header=enc(JSON.stringify({alg:"HS256",typ:"JWT"}));const payload=enc(JSON.stringify({sub:user.id,role:user.role,iat:now,exp:now+15*60,jti:randomBytes(12).toString("hex"),typ:"access"} satisfies MobileClaims));return `${header}.${payload}.${digest(`${header}.${payload}`)}`}
export function verifyMobileAccessToken(token:string):MobileClaims|null{try{const [header,payload,signature,...rest]=token.split(".");if(!header||!payload||!signature||rest.length)return null;const expected=Buffer.from(digest(`${header}.${payload}`));const actual=Buffer.from(signature);if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return null;const claims=JSON.parse(Buffer.from(payload,"base64url").toString("utf8")) as MobileClaims;if(claims.typ!=="access"||!claims.sub||claims.exp<=Math.floor(Date.now()/1000))return null;return claims}catch{return null}}
export const hashMobileRefreshToken=(token:string)=>digest(`refresh:${token}`);
const newRefresh=()=>randomBytes(48).toString("base64url");
type Db=Prisma.TransactionClient|typeof prisma;
export async function issueMobileSession(db:Db,user:{id:string;role:SystemRole},deviceName?:string,familyId=randomBytes(16).toString("hex")){const refreshToken=newRefresh();await db.mobileRefreshToken.create({data:{tokenHash:hashMobileRefreshToken(refreshToken),familyId,userId:user.id,deviceName:deviceName?.slice(0,120),expiresAt:new Date(Date.now()+30*24*60*60_000)}});return{accessToken:createMobileAccessToken(user),refreshToken,accessExpiresIn:900,refreshExpiresIn:30*24*60*60,tokenType:"Bearer" as const}}
export async function rotateMobileSession(refreshToken:string,deviceName?:string){if(refreshToken.length<48)return null;return prisma.$transaction(async tx=>{const record=await tx.mobileRefreshToken.findUnique({where:{tokenHash:hashMobileRefreshToken(refreshToken)},include:{user:{select:{id:true,role:true,status:true}}}});if(!record)return null;if(record.revokedAt){await tx.mobileRefreshToken.updateMany({where:{familyId:record.familyId,revokedAt:null},data:{revokedAt:new Date()}});return null}if(record.expiresAt<=new Date()||record.user.status!=="ACTIVE"){await tx.mobileRefreshToken.update({where:{id:record.id},data:{revokedAt:new Date()}});return null}await tx.mobileRefreshToken.update({where:{id:record.id},data:{revokedAt:new Date(),lastUsedAt:new Date()}});return issueMobileSession(tx,record.user,deviceName||record.deviceName||undefined,record.familyId)},{isolationLevel:"Serializable"})}
export async function revokeMobileSession(refreshToken:string){if(refreshToken.length<48)return;const record=await prisma.mobileRefreshToken.findUnique({where:{tokenHash:hashMobileRefreshToken(refreshToken)},select:{familyId:true}});if(record)await prisma.mobileRefreshToken.updateMany({where:{familyId:record.familyId,revokedAt:null},data:{revokedAt:new Date()}})}
export async function getMobileUser(request:Request){const auth=request.headers.get("authorization")||"";const claims=verifyMobileAccessToken(auth.startsWith("Bearer ")?auth.slice(7):"");if(!claims)return null;return prisma.user.findFirst({where:{id:claims.sub,status:"ACTIVE"},select:{id:true,name:true,email:true,phone:true,role:true,locale:true,image:true}})}
export function mobileUnauthorized(){return Response.json({ok:false,error:"AUTH_REQUIRED"},{status:401,headers:{"cache-control":"no-store"}})}
export function mobileForbidden(){return Response.json({ok:false,error:"FORBIDDEN"},{status:403,headers:{"cache-control":"no-store"}})}
