import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { emailOrderUrl, selectStorefrontItems, storefrontContactChannels, storefrontMessage, whatsappOrderUrl } from "./storefront-order";

describe("contact-only storefront policy",()=>{
  it("builds localized, user-initiated WhatsApp enquiries from public data",()=>{const message=storefrontMessage({locale:"ar",businessName:"شركة اختبار",itemName:"خدمة تجريبية",profileUrl:"https://go.popwam.com/p/example"});const url=whatsappOrderUrl("+201001234567",message);expect(url).toContain("https://wa.me/201001234567?text=");expect(new URL(url!).searchParams.get("text")).toContain("خدمة تجريبية");expect(whatsappOrderUrl("not-a-phone",message)).toBeNull();});
  it("builds a safe mailto enquiry and rejects invalid email data",()=>{const input={locale:"en" as const,businessName:"Example Studio",itemName:"Design consultation",profileUrl:"https://go.popwam.com/p/example"};const url=emailOrderUrl("hello@example.test",input);expect(url).toContain("mailto:hello@example.test?subject=");expect(decodeURIComponent(url!)).toContain("Design consultation");expect(emailOrderUrl("javascript:alert(1)",input)).toBeNull();});
  it("adds only narrow plan/showcase fields and no commerce tables or actions",()=>{const schema=readFileSync(new URL("../../../../packages/db/prisma/schema.prisma",import.meta.url),"utf8");const migration=readFileSync(new URL("../../../../packages/db/prisma/migrations/20260908190000_plan_storefront_entitlements/migration.sql",import.meta.url),"utf8");for(const key of ["storefrontEnabled","storefrontProductsEnabled","storefrontServicesEnabled","storefrontMaxItems","storefrontWhatsappOrder","storefrontEmailOrder","ProfileShowcaseItemType","imageUrl","price","currency","category","featured"])expect(schema).toContain(key);expect(migration).not.toMatch(/CREATE TABLE|Cart|Checkout|Payment|Shipping/);});
  it("renders product-only, service-only, mixed, and capped showcase policies",()=>{const items=[{id:"p",itemType:"PRODUCT" as const,isVisible:true},{id:"s",itemType:"SERVICE" as const,isVisible:true},{id:"hidden",itemType:"PRODUCT" as const,isVisible:false}];const base={enabled:true,products:true,services:true,maxItems:null,whatsapp:false,email:false};expect(selectStorefrontItems(items,{...base,services:false}).map(x=>x.id)).toEqual(["p"]);expect(selectStorefrontItems(items,{...base,products:false}).map(x=>x.id)).toEqual(["s"]);expect(selectStorefrontItems(items,base).map(x=>x.id)).toEqual(["p","s"]);expect(selectStorefrontItems(items,{...base,maxItems:1})).toHaveLength(1);});
  it("calculates Email-only, WhatsApp-only, both, and no-channel states on the server",()=>{const input={contactPublic:true,whatsapp:"+201001234567",email:"hello@example.test"};const base={enabled:true,products:true,services:true,maxItems:null};expect(storefrontContactChannels({...base,whatsapp:false,email:true},input)).toEqual({whatsapp:null,email:"hello@example.test"});expect(storefrontContactChannels({...base,whatsapp:true,email:false},input)).toEqual({whatsapp:"+201001234567",email:null});expect(storefrontContactChannels({...base,whatsapp:true,email:true},input)).toEqual({whatsapp:"+201001234567",email:"hello@example.test"});expect(storefrontContactChannels({...base,whatsapp:true,email:true},{...input,contactPublic:false})).toEqual({whatsapp:null,email:null});});
  it("keeps price optional and includes it only when supplied",()=>{const base={locale:"en" as const,businessName:"Studio",itemName:"Consultation",profileUrl:"https://go.popwam.com/p/example#item-one"};expect(storefrontMessage(base)).not.toContain("undefined");expect(storefrontMessage({...base,price:"EGP 250.00"})).toContain("EGP 250.00");});
});
